### PR TITLE
Feature #2379 sonarqube gha

### LINKED ISSUE #2379: Add GitHub action to run SonarQube for MET pull requests and feature branches
## Describe the Enhancement ##
As of MET version 11.0.0, SonarQube is run nightly on an internal RAL/JNT project machine for MET, METplus, and the METplus Analysis tools. This was added via #2020 and the SonarQube version was updated via #2270. This task is to move that migrate that scanning from an internal nightly build up to GHA.

The workflow could be very similar to the existing testing.yml workflow. For a pull request, scan the code using SonarQube and compare it to a scan of the current reference branch. For example, compare to the PR scan to the current scan of the develop-ref branch.

Report success if the overall number of findings remain the same or decrease.
Report failure if the overall number of findings increase.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Needed for the Air Force - 2771024

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

The following SonarQube issues are closely related:
- [x] dtcenter/METplus#2537
- [x] dtcenter/MET#2379
- [x] dtcenter/METviewer#521
- [x] dtcenter/METplotpy#429
- [x] dtcenter/METcalcpy#366
- [x] dtcenter/METdataio#289

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
Please read through this [issue comment](https://github.com/dtcenter/MET/issues/2379#issuecomment-2029879512) for a description of the changes and logic as well as a list of future items. Recommend proceeding with these changes for now and considering how we can refine our use of SonarQube in the future.

Once this PR is approved, I'll submit another PR to make the same changes in the `main_v11.1` primarily so that the manual triggers will become available which would be very convenient for development of feature branches.

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Did lots of testing on my laptop and confirmed that the [GHA tests](https://github.com/dtcenter/MET/pull/2847/checks) all pass.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
  - @hsoh-u please review these changes to the GHA automation, consider my use of Docker in particular. Please also consider my use of SonarQube and project naming conventions at needham.rap.ucar.edu. Are there any changes you'd recommend?
  - @jprestop please see the update to the PR template to make a generic reference to SonarQube. Should I include any other changes to the documentation at this time? Or just wait for our automated use of SonarQube to mature more?

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**
I made no documentation updates at this time.

- [x] Do these changes include sufficient testing updates? **[Yes]**
No new unit tests are needed.

- [x] Will this PR result in changes to the MET test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Will this PR result in changes to existing METplus Use Cases? **[No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.

- [x] Please complete this pull request review by **[Wed 4/3/24]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — DISMISSED** [review]
@JohnHalleyGotway Thanks for all of your work on this task! It will be so great to have these changes in the repo!  I reviewed the update to the PR template with the generic reference to SonarQube, and I think it's great. 

Regarding:
> Should I include any other changes to the documentation at this time? Or just wait for our automated use of SonarQube to mature more?

If you have time and think it is appropriate and worthwhile, it'd be great to have you write up something in the [MET Contributor's Guide Planning](https://docs.google.com/document/d/1u13hVLYHh2KjtSuqj9T0wrLtHk-I5VMqDAwgE6B83aQ/edit) document, which will be put into rst at some point (hopefully, at least partially in the not too distant future).  It would also be fine to wait, if preferred.

I also confirmed that all test passed.  Thanks again for all of your work on this.  I approve this request, but also see that you'd like Howard's review/approval for different things.

**Review by hsoh-u — DISMISSED** [review]
I approve this PR. The scripts for the cron are ported for the Docker environment without any missing. The SonarQube token and URL are not exposed.
It will be nice to have the `Run workflow` option  like running the unit test GHA manually at Testing GHA

**Comment by JohnHalleyGotway** [comment]
@hsoh-u and @jprestop these changes are now ready for your review. And they are working just how we'd like.

On my feature branch, I did intentionally introduce a SonarQube finding in the C++ code. And in this [GHA run](https://github.com/dtcenter/MET/actions/runs/8528551008/job/23362448191?pr=2847) the `SonarQube CXX Quality Gate check` step fails just like we'd want it to! Here's a screenshot of what those new findings look like in the SonarQube server:
Screen Shot 2024-04-02 at 2 07 10 PM

In general, the SonarQube scan is compared between the code for the PR and the reference branch. If the "new code" introduces new findings, the quality gate check fails.
Since I removed that intentional breakage, the final run of the SonarQube GHA workflow should pass.

The only other thing we could consider is splitting out the logic for the Python and C++ scans into separate steps. The C++ scan is WAY more complex than the Python one. If I could make a simple Python one, it'd be easier to apply it to the other Python-based METplus repos.

Should I pursue that now? Or just be happy that this setup works well?

**Review by jprestop — APPROVED** [review]
My review steps haven't changed, so my re-review is the same and I'll defer to my previous comments.  Regarding:

> The only other thing we could consider is splitting out the logic for the Python and C++ scans into separate steps. The C++ scan is WAY more complex than the Python one. If I could make a simple Python one, it'd be easier to apply it to the other Python-based METplus repos.  Should I pursue that now? Or just be happy that this setup works well?

If you have time to use this new knowledge and apply it to creating a simpler Python scan now, I would encourage that 1) because it's fresh in your mind and may be easier to get started on now as opposed to waiting, and 2) it would probably enable to the other repos to get started on this sooner rather than later (or at least once their workload allows).  However, I think it is fantastic that this setup is working now and am grateful for that, so if it's inconvenient to work on now, that is completely understandable, and I'd support that as well.

**Comment by JohnHalleyGotway** [comment]
I've decided to proceed with the logic as-is. The logic for doing this in the other METplus repos will be similar but not identical. But doing both the Python and CXX in the same Docker container for MET makes a lot of sense. I'll proceed with merging this PR and will then propose the same changes for the `main_v11.1` branch.

**Comment by jprestop** [comment]
Sounds good! Thanks!

**Review by hsoh-u — APPROVED** [review]
It's great to have the quality gate status.

**Pull request merged**
