### PR TITLE
Feature #1283 mvmode mods

### LINKED ISSUE #1283: Enhance Multivariate MODE to generate object statistics for each input field requested by the user.
## Describe the Enhancement ##
I am repurposing this existing issue to better define the multi-variate MODE enhancements that are needed.

1. While the existing `MODEMultivarConfig_default` file exists in the repository, it is NOT actually read by Multi-Variate MODE! In all cases, MODEConfig_default is read instead. Need to understand why, and either update MODE to read it in the right circumstances or just remove it from the repo.

2. If `MODEMultivarConfig_default` is retained, modify the `nc_pairs_flag` setting in it to specify it as a dictionary, just like it is specified in MODEConfig_default. This is needed to make the logic of the MODE wrapper clear and consistent.

3. Make large updates to the multi-variate logic, as described below.
- As of MET version 10.1.0, multi-variate MODE generates output NetCDF files named `f_super.nc` and `o_super.nc`. However, it does not actually write out any object statistics.
- Recommend that it continue to write out the super object information, but write out both fields to the standard MODE NetCDF output file instead (i.e. *_obj.nc).
- Add a new config option that is an array of booleans with the same length as the number of forecast and observation fields: `multivar_intensity_flag = [ TRUE, TRUE, FALSE ];` (default will be FALSE for all)
- After generating the super objects, loop through the `multivar_intensity_flag` booleans:
   - If all `multivar_intensity_flag` booleans are false, run MODE once on the binary 0/1 super objects to generate geometric object statistics and write them to the output "*_obj.txt" file.
   - Otherwise, for each `multivar_intensity_flag` boolean flag that is true, run MODE once substituting in the raw intensity values for the corresponding fcst/obs fields. The object definition has already been performed, but we're just regenerating the statistics using the intensities for those fields. Write the output to the "*_obj.txt" output file. For any FALSE booleans, the intensity statistics will contain missing values.
   - So the "*_obj.txt" may now contain output for multiple fields with different intensity values and potentially total interest values. Need to differentiate between them in the output in the FCST_VAR and OBS_VAR columns. Recommend including the forecast and observation field names in those output columns.
   - Be sure to check the `nc_pairs_flag` option and write intensity values to the NetCDF file, as requested by the user.
   - Add a new config option that allows the user to change the forecast and observation field names. Currently the super object output name is ‘super’, but users may be running multivariate MODE on multiple complex events (dryline/blizzard), and it will be beneficial to have a way to differentiate between the output
      - Add `multivar_name="";` to change the name of the multivariate mode output as listed in the ascii file output, for example. (default will be "super")
      - For example, if we define `multivar_name = "blizzard";` and we request intensity output for visibility, our ascii file(s) should append this to the FCST_VAR and OBS_VAR names e.g. blizzard_vis/vis_blizzard (preferred order?)
         - If intensity isn’t requested for any field, the name would be blizzard for the geometric object statistics?
- Other considerations
   - Determine whether there should be separate MODE output files for each field where intensity statistics are requested, or all output contained in a single file
      - Do what makes sense, when thinking about parallelization
   - No need to keep mode runs from the individual fields - cuts down on processing time
   - Keep this info in memory for continuing the mvmode process
 
### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2700042 WPC

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Related to MET Issues:
- #1184 
- #1282 
- #1284 

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by davidalbo**
## Expected Differences ##

- [ ] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**
**3 new config options:  ` multivar_intensity,  multivar_name, multivar_level.  `The latter 2 can be set independently for fcst and obs dictionaries.** </br>

- [ ] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**
**But.. the output file organization (no more numbered subdirectories) and file naming has changed.**
</br>

**Changes to be aware of that have not been 'vetted' by anyone or seem possibly incomplete, and are things the reviewer might want to consider before approving:

1. Went with 0's inside superobjects for 'all intensities false' to represent superobjects without intensities instead of setting missing data everywhere inside and outside superobjects.
2. Made up some replacements for when the config has `level=(*,*)`.  The output files names now include the levels.  I  replaced`(*,*)` with `-X,X-` in those output names, as the wildcard characters are problematic for file names.  Do wildcards in levels make sense for multivariate mode?  (The unit test for mvmode does have the wildcard levels, and does run and produce output with the wildcards).  
3. Disallowed many configuration settings for multivariate mode, which hopefully will not cause problems for users, such as quilting and engine merging.  Also everything must be the same length (number of files (fcst and obs), multivar_logic, multivar_intensity, and fcst and obs field array lengths).  
4. the metplus changes to support the new config options was added by @georgemccabe but has not been tested on this version of mode.
5. documentation is only partially updated to describe the changes**

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:
**Extensive testing on a test case provided by @hertneky .  Unit tests have been run manually.**</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:  
**Have a look in `/scratch/dave/mvmode_test_for_pull_request`.  In that directory two .bsh files can be run.
`run-multi.bsh  `should run a setup with intensities computed for the last 2 fields, with output going to subdirectory `output`. 
`run-super.bsh `should run a setup with no intensities, just superobject output, into subdirectory `output-super`**
</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**   **It might work, but not sure.**

- [ ] Do these changes include sufficient testing updates? **[Not quite]** **More testing of traditional mode would be good, as would testing on a variety of multivar examples.**

- [ ] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:
**Unit test output file names have changed, and additional unit testing is now in place.  The test is `internal/test_unit/xml/unit_mode_multivar.xml`, which now runs two instances of multivariate mode.
New output files that should replace what were previously the output files for this test:
mode_Fcst_ALPHA-X,X-_Obs_ALPHA-X,X-_300000L_20120410_180000V_060000A_cts.txt
mode_Fcst_ALPHA-X,X-_Obs_ALPHA-X,X-_300000L_20120410_180000V_060000A_obj.nc
mode_Fcst_ALPHA-X,X-_Obs_ALPHA-X,X-_300000L_20120410_180000V_060000A_obj.txt
mode_Fcst_ALPHA-X,X-_Obs_ALPHA-X,X-_300000L_20120410_180000V_060000A.ps
mode_Fcst_BETA-X,X-_Obs_BETA-X,X-_300000L_20120410_180000V_060000A_cts.txt
mode_Fcst_BETA-X,X-_Obs_BETA-X,X-_300000L_20120410_180000V_060000A_obj.nc
mode_Fcst_BETA-X,X-_Obs_BETA-X,X-_300000L_20120410_180000V_060000A_obj.txt
mode_Fcst_BETA-X,X-_Obs_BETA-X,X-_300000L_20120410_180000V_060000A.ps
mode_Fcst_GAMMA-X,X-_Obs_GAMMA-X,X-_300000L_20120410_180000V_060000A_cts.txt
mode_Fcst_GAMMA-X,X-_Obs_GAMMA-X,X-_300000L_20120410_180000V_060000A_obj.nc
mode_Fcst_GAMMA-X,X-_Obs_GAMMA-X,X-_300000L_20120410_180000V_060000A_obj.txt
mode_Fcst_GAMMA-X,X-_Obs_GAMMA-X,X-_300000L_20120410_180000V_060000A.ps
mode_Fcst_Super_LO_Obs_Super_LO_300000L_20120410_180000V_060000A_cts.txt
mode_Fcst_Super_LO_Obs_Super_LO_300000L_20120410_180000V_060000A_obj.nc
mode_Fcst_Super_LO_Obs_Super_LO_300000L_20120410_180000V_060000A_obj.txt
mode_Fcst_Super_LO_Obs_Super_LO_300000L_20120410_180000V_060000A.ps
These files are here:   `/scratch/dave/mvmode_test/unit_test_output/`**

</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by hertneky — COMMENTED** [review]
I have no suggested changes. This looks good.

**Review by hertneky — APPROVED** [review]

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
@davidalbo I think there's an issue with the convolution radius and thresholds being applied when defining the objects for each of the components. The config file settings indicate that the `conv_radius = 2;` and `conv_thresh = >=5.0;`. However, I don't see those settings in the output.

Downloading the differences flagged in this [GHA run](https://github.com/dtcenter/MET/actions/runs/5247996613), I see the following.

All of the `TRUTH` data reports the expected convolution radius and threshold:
```
cat `find ./ -name "*_obj_TRUTH.txt"` | awk '{print $12,$13}' | sort -ru
FCST_RAD FCST_THR
2 >=5.0
```
While the newly generated `OUTPUT` data reports what I'm guessing are default convolution radius and threshold values:
```
cat `find ./ -name "*_obj_OUTPUT.txt"` | awk '{print $12,$13}' | sort -ru
FCST_RAD FCST_THR
0 !=-9999
```

I realize that the output file NAMES have changed, but I don't think the object definition criteria or geometry should change. Based on what I'm seeing, perhaps the logic for parsing the convolution radius and threshold from the input configuration file isn't working as expected?

Please take another look at this.

**Comment by JohnHalleyGotway** [comment]
@davidalbo note that running `unit_mode_multivar.xml` manually with at least verbosity level 3 (-v 3), I see that the conv radius and threshold ARE being parsed from the config file:
```
egrep -i "radius|threshold" run.log | sort -u
DEBUG 3: Applying circular convolution of radius 2 to the forecast field.
DEBUG 3: Applying circular convolution of radius 2 to the observation field.
DEBUG 3: Applying convolution threshold >=5.0 resulted in 1 simple forecast objects.
DEBUG 3: Applying convolution threshold >=5.0 resulted in 1 simple observation objects.
```
So perhaps they're being parsed and use correctly but not written to the output file correctly?

Another thing that's throwing me for a loop is the PostScript output. All of these PostScript files:
```
mode_Fcst_ALPHA_all_all_Obs_ALPHA_all_all_300000L_20120410_180000V_060000A_OUTPUT.ps
mode_Fcst_BETA_all_all_Obs_BETA_all_all_300000L_20120410_180000V_060000A_OUTPUT.ps
mode_Fcst_GAMMA_all_all_Obs_GAMMA_all_all_300000L_20120410_180000V_060000A_OUTPUT.ps
mode_Fcst_Super_LO_Obs_Super_LO_300000L_20120410_180000V_060000A_OUTPUT.ps
```
Show the same super objects. I was kind of expecting the ALPHA would show me the first object, BETA would show me the second, and GAMMA would show me the third. But I think I understand why they don't. This is displaying the raw intensity values for the ALPHA, BETA, and GAMMA input fields. It just so happens that our raw input data is so uninteresting (0's or 100's), that it's causing a little confusion for me.

**Comment by davidalbo** [comment]
@JohnHalleyGotway I believe I've found and fixed the incorrect conv radius and thresh in the output problem.  As for the other concern, I think` Alpha, Beta, Gamma, Super `should show the same objects. In each case what we are looking at is the data restricted to inside the **same** super objects. The data being `Alpha, Beta, or Gamma` (with intensities) and` super `(without intensities).   Am I understanding the concern?  If so, I'm ready for another push to github.

**Comment by JohnHalleyGotway** [comment]
Dave, Tracy and I met briefly and have the following requests:
1. You already updated the `FCST/OBS_RAD` and `FCST/OBS_THR` columns in the `_obj.txt` file to indicate the radius and threshold applied to that field, which is great.
2. Please also populate the `FCST/OBS_UNITS` and `FCST/OBS_LEV` columns in the `_obj.txt` file to indicate the units and level for that field as well.
3. In the `FCST/OBS_VAR` column, pre-pend the super object name (i.e. `multivar_name` config file entry). For example, change `FCST_VAR = ALPHA` to `FCST_VAR = Super_ALPHA`.
4. In the PostScript output, can we plot the FULL raw field of each component rather than the raw field masked to the area of the super object? If so, that'd be more consistent with regular mode output. If it's too difficult, this isn't a big deal.
5. Recommend that we change the MODE config files used by the unit tests to request matching and make the max_centroid_dist bigger, as follows:
```
git diff config/MODEConfig_multivar_fake_data
diff --git a/internal/test_unit/config/MODEConfig_multivar_fake_data b/internal/test_unit/config/MODEConfig_multivar_fake_data
index c687d39c4..c8941f8b9 100644
--- a/internal/test_unit/config/MODEConfig_multivar_fake_data
+++ b/internal/test_unit/config/MODEConfig_multivar_fake_data
@@ -107,12 +107,12 @@ mask_missing_flag = NONE;
 //
 // Match objects between the forecast and observation fields
 //
-match_flag = NONE;
+match_flag = MERGE_BOTH;
 
 //
 // Maximum centroid distance for objects to be compared
 //
-max_centroid_dist = 800.0/grid_res;
+max_centroid_dist = 800.0;
```
And:
```
git diff config/MODEConfig_multivar_fake_data_with_intensities 
diff --git a/internal/test_unit/config/MODEConfig_multivar_fake_data_with_intensities b/internal/test_unit/config/MODEConfig_multivar_fake_data_with_intensities
index 8f646002e..af6d1720a 100644
--- a/internal/test_unit/config/MODEConfig_multivar_fake_data_with_intensities
+++ b/internal/test_unit/config/MODEConfig_multivar_fake_data_with_intensities
@@ -107,12 +107,12 @@ mask_missing_flag = NONE;
 //
 // Match objects between the forecast and observation fields
 //
-match_flag = NONE;
+match_flag = MERGE_BOTH;
 
 //
 // Maximum centroid distance for objects to be compared
 //
-max_centroid_dist = 800.0/grid_res;
+max_centroid_dist = 800.0;
```

**Comment by davidalbo** [comment]
For 2. above, I think for individual intensities this is already in place. Looking at Tracy's test case output I see for WIND:  units = m/s and level = Z10, and for VIS: units = m and level = LO.  

For the unit test it seems that units = NA, this comes from the input data, and level = (*,*)  from the config, which is what we see in the Alpha, Beta, Gamma individual intensity output txt files.

For the super object only case (no intensities), I'm setting units = NA and level to LO because the inputs can be a mix of different values.  For the Tracy test case, the inputs that made the super objects have units m/s, m and levels LO and Z10.  What values should go into the txt file in this case?  I went with NA and LO arbitrarily, open for suggestions.

**Comment by JohnHalleyGotway** [comment]
Dave, I'm glad to hear that you're getting meaningful units/level strings from Tracy. I do understand what you're saying, but there is some difference occurring. When MET reads data from NetCDF files the units and level variable attributes (if present) are used to define those strings. For example:
```
	float ALPHA(lat, lon) ;
		ALPHA:name = "ALPHA" ;
		ALPHA:long_name = "alpha" ;
		ALPHA:level = "SFC" ;
		ALPHA:units = "kg/m^2" ;
```
Running this through traditional MODE, it grabs the level and units strings from here. So I would expect to see those same strings in the output from multi-variate MODE.

**Comment by davidalbo** [comment]
> Dave, I'm glad to hear that you're getting meaningful units/level strings from Tracy. I do understand what you're saying, but there is some difference occurring. When MET reads data from NetCDF files the units and level variable attributes (if present) are used to define those strings. For example:
> 
> ```
> 	float ALPHA(lat, lon) ;
> 		ALPHA:name = "ALPHA" ;
> 		ALPHA:long_name = "alpha" ;
> 		ALPHA:level = "SFC" ;
> 		ALPHA:units = "kg/m^2" ;
> ```
> 
> Running this through traditional MODE, it grabs the level and units strings from here. So I would expect to see those same strings in the output from multi-variate MODE.

Might this be an artifact from the presence of` level=(*,*)` in the mode config file for the unit test?  For the Tracy example, the level is specified explicitly in the config file.

**Comment by JohnHalleyGotway** [comment]
Dave, this [line of code](https://github.com/dtcenter/MET/blob/661b83e8a9c5b5130c5f7079d95839c97e7e02fc/src/libcode/vx_data2d_nc_met/data2d_nc_met.cc#L189) is relevant. The users requests `(*,*)` in the config file to tell MET what data to grab. That line of library code stores the `level` and `units` variable attributes, if defined, in the VarInfo object:
```
      if(info->level_att.length()     > 0) vinfo.set_level_name(info->level_att.c_str());
      if(info->units_att.length()     > 0) vinfo.set_units(info->units_att.c_str());
```
So this is how traditional MODE is populating the FCST_LEV and FCST_UNITS columns.

**Comment by davidalbo** [comment]
> Dave, this [line of code](https://github.com/dtcenter/MET/blob/661b83e8a9c5b5130c5f7079d95839c97e7e02fc/src/libcode/vx_data2d_nc_met/data2d_nc_met.cc#L189) is relevant. The users requests `(*,*)` in the config file to tell MET what data to grab. That line of library code stores the `level` and `units` variable attributes, if defined, in the VarInfo object:
> 
> ```
>       if(info->level_att.length()     > 0) vinfo.set_level_name(info->level_att.c_str());
>       if(info->units_att.length()     > 0) vinfo.set_units(info->units_att.c_str());
> ```
> 
> So this is how traditional MODE is populating the FCST_LEV and FCST_UNITS columns.

I have implemented a fix for this.  I do not understand why the case from Tracy without wildcards **did** hold onto units and levels between pass1 (simple objects)  and pass2 (super object masked), whereas the unit test with wildcard did **not**, but the fix does work for both tests.  I'm grabbing the units/levels during the first pass where they are correct, saving them, and using them in the second pass.   
Breaking news: It still doesn't work, only works for ALPHA, not BETA or GAMMA.  Will revisit tomorrow AM.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes. Thanks @davidalbo!

I downloaded/reviewed the diff files and see that you made all the changes I previously requested. I reviewed several of the source code changes and did make a small commit to the branch with whitespace tweaks for consistent code formatting. But I didn't review every change in the 50 modified files. But the output looks great.

I'll go ahead and merge this PR and proceed with cutting the MET-11.1.0-RC1 release.

**Pull request merged**
