### PR TITLE
Feature 1421 point2grid performance

### LINKED ISSUE #1421: Enhance the performance of point2grid
## Describe the Enhancement ##
Jemie Wolff reported point2grid took less than 1 minute with HRRR domain (1799 by 1059)  but it took more than 40 minutes with GFS domain (3072 by 1536) at Cheyenne.
HRRR case, the data is mapped to 1.7M grid cells (out of 1.8 M cells). GFS case,  mapped to 3.1 M grid cells (out of 4.5 M cells).

Commands to load:

module use /glade/p/ral/jntp/MET/MET_releases/modulefiles
module load met/9.0
setenv MET_TMP_DIR /glade/p/ral/jntp/AF/cloud_vx/goes_data/test_met

To HRRR grid:

point2grid /glade/p/ral/jntp/AF/cloud_vx/goes_data/level2/abi_tb_fd_2020070300_C13_G16.nc /glade/p/ral/jntp/AF/cloud_vx/model_data/HRRR/2020060800-05/hrrr.t00z.wrfprsf01.grib2 test_hrrr_chey.nc -field 'name="tb"; level="(*,*)";' -v 3

To GFS grid:

point2grid /glade/p/ral/jntp/AF/cloud_vx/goes_data/level2/abi_tb_fd_2020070300_C13_G16.nc /glade/p/ral/jntp/AF/cloud_vx/model_data/GFS/gfs.20200608/00/gfs.t00z.special.grb2f001 test_gfs_chey.nc -field 'name="tb"; level="(*,*)";' -v 3

### Time Estimate ###
4 to 8 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE.

### Funding Source ###
2791541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [x] Select **scientist(s)** or **no scientist** required (None)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>

- [x] Will this PR result in changes to the test suite? **[No]**</br>

The global attribute of "RunCommand" will be changed because of not using grid cell mapping file. The comparing script will ignore this difference.

                :RunCommand = "Point obs (Projection: GoesImager Nx: 2500 Ny: 1500) to Projection: Lambert Conformal Nx: 185 Ny: 129 Lat_LL: 12.190 Lon_LL: 133.459 Lon_orient: 95.000 Alpha: 406.820 Cone: 0.423 Bx: 104.0012 By: 356.7313 with /d1/projects/MET/MET_regression/develop/NB20201210/MET-develop-ref/test_output/CONUS_2500_1500_56_-56_-101360_128240_to_G212.grid_map" ;
==>

                :RunCommand = "Point obs (Projection: GoesImager Nx: 2500 Ny: 1500) to Projection: Lambert Conformal Nx: 185 Ny: 129 Lat_LL: 12.190 Lon_LL: 133.459 Lon_orient: 95.000 Alpha: 406.820 Cone: 0.423 Bx: 104.0012 By: 356.7313 with /d1/personal/hsoh/test_output/feature_1421_point2grid_performance/CONUS_2500_1500_56_-56_-101360_128240.nc" ;
 
- [x] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

Modification:
- Do not use and save the grid mapping file
- Filter missing lat/lon first before computing cell mapping (library supports any longitude values including -9999)
- Compute the each cell mapping size first and build IntArray to avoid auto extension.
- NcCF.getData(): read the whole variable instead of reading row by row (avoid ny times of de-compression)
  - expecting speed up on handling NcCF (please make sure it does not break other caller)
- Bug fix with the median interpolation (sorting mapped values, not cell mapping indices)
- Added log messages of the execution time (debug level 6 or more)

At kiowa (Note: (they  tool over 1 hour at dakota):

./point2grid /d1/personal/hsoh/data/UKMet_tripolar/prodm_op_gl.dm3d.grid_T_20200907_00.036_temp.nc G231 point2grid_UK_NCCF_TO_G231.nc -field 'name="votemper"; level="(0,0,\*,\*)";' -v 8

./point2grid /d1/personal/hsoh/data/MET-1421/abi_tb_fd_2020070300_C13_G16.nc  /d1/personal/hsoh/data/MET-1421/gfs.t00z.special.grb2f001 point2grid_abi_gfs.nc -field 'name="tb"; level="(\*,\*)";' -v 8

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
As of 12:30pm 20201214, I am compiling the PR code on kiowa in:
/d1/projects/MET/MET_pull_requests/met-10.0.0_beta3/feature_1421

Once the code has compiled, I'll inspect the changes and run the point2grid unit tests. They should still run and produce the same output as produced by the nightly build.

Then I'll test using the commands Howard listed in the pull request.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
The PR stated that the NB output should not change, but it did. On kiowa, please compare:
file1: /d1/projects/MET/MET_pull_requests/met-10.0.0_beta3/feature_1421/MET-feature_1421_point2grid_performance_into_develop/test_output/point2grid/pb2nc_TMP_RH.nc
file2: /d1/projects/MET/MET_regression/develop/NB20201214/MET-develop/test_output/point2grid/pb2nc_TMP_RH.nc

COMPARING pb2nc_TMP_RH.nc
file1: test_output/point2grid/pb2nc_TMP_RH.nc
file2: /d1/projects/MET/MET_regression/develop/NB20201214/MET-develop/test_output/point2grid/pb2nc_TMP_RH.nc
ERROR: found  1522 differences in var RH                                     - max abs: 277.6162 
ERROR: found   259 differences in var RH_cnt                                 - max abs: 70 
ERROR: found    83 differences in var RH_mask                                - max abs: 1 
passed numerical var TMP 
passed numerical var TMP_cnt 
passed numerical var TMP_mask 

I suspect this is the result of a bug being fixed because the range of RH values now look correct whereas they were previously TMP values. Please confirm and update the text of this PR to state that the NB output *should* change and why.

**Comment by hsoh-u** [comment]
The cell mapping for MET point data should be re-generated per variable.

**Review by JohnHalleyGotway — APPROVED** [review]
Recompiled updated code on kiowa and reran unit_point2grid.xml.
Then I diffed the point2grid output with the NB output and found no more diffs.
I approve of these changes.

**Pull request merged**
