### PR TITLE
Feature #2476 tc_pairs_diag take 2

### LINKED ISSUE #2476: Enhance TC-Pairs to include storm diagnostics in consensus track output
## Describe the Enhancement ##
When the `-diag` command line option is provided, the TC-Pairs tool writes TCDIAG output lines after the TCMPR lines to which they correspond. However these diagnostics are NOT currently included in the computation of consensus tracks.

This issue is to enhance the computation of consensus tracks to include the average of the model diagnostics of the members. There are obvious questions about whether or not each diagnostic must be present and valid in the members for it to be included in the consensus output. Does this need to be configurable?

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2770043

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Expected Differences ##

This is the 2nd pull request for #2476. In TC-Pairs, we need to move the call to `filter_tracks()` down after the call to `derive_consensus()`. Otherwise, we discard the consensus member tracks for `UEMN_CONS` prior to using them to define the consensus.

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Ran locally to confirm that this fixes the behavior.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Inspect the GHA testing workflow run. The only diffs should be the introduction of a new TC-Pairs output file and also an unrelated issue with the derivation of PBL observations.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
Already included in earlier PR #2694.

- [x] Do these changes include sufficient testing updates? **[Yes]**
Already included in earlier PR #2694.

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
New output file is added:
```
    tc_pairs/al092022_20220926_DIAGNOSTICS_CONSENSUS.tcst
```
Expect to see an unrelated PB2NC difference flagged as well:
```
COMPARING pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
file1: /data/output/met_test_truth/pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
file2: /data/output/met_test_output/pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
ERROR: NetCDF headers differ:
7c7
< 	nobs = 401 ;
---
> 	nobs = 392 ;
```

- [x] Please complete this pull request review by **[Fri 10/6/23]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
I'll note that [this GHA run](https://github.com/dtcenter/MET/actions/runs/6421626813) did flag a difference in the tc-pairs output. However, it is just a difference in the order of the output. I downloaded/unpacked the diffs and ran:
```
cat al132020_CONSENSUS_TRUTH.tcst | sort > TRUTH
cat al132020_CONSENSUS_OUTPUT.tcst | sort > OUTPUT
diff TRUTH OUTPUT
```
After sorting the output, the diffs go away. The derived `BCLP` track output used to appear BEFORE the consensus tracks but now appears AFTER them. This makes sense because in MET version 11.1, tc_pairs computed [consensus tracks](https://github.com/dtcenter/MET/blob/bc538d698e7eeea98502536e27c3f6d12695ee29/src/tools/tc_utils/tc_pairs/tc_pairs.cc#L352) before [baselines](https://github.com/dtcenter/MET/blob/bc538d698e7eeea98502536e27c3f6d12695ee29/src/tools/tc_utils/tc_pairs/tc_pairs.cc#L369). This branch moves the computation of consensus tracks after baselines, changing the order in the output.

**Review by sethlinden — COMMENTED** [review]
All of these changes look good to me.

**Comment by sethlinden** [comment]
I reviewed the PR and I approve of the changes. @JohnHalleyGotway looked at the differences in the workflow testing data and it was just a difference in the order of the data.

**Review by sethlinden — APPROVED** [review]
All the code changes look reasonable and make sense.

**Pull request merged**
