### PR TITLE
Bugfix 2370 aeronetv3

### LINKED ISSUE #2370: Fix ASCII2NC logic for reading AERONET v3 data
## Describe the Problem ##
This issue arose with the METplus Discussion [dtcenter/METplus#1888](https://github.com/dtcenter/METplus/discussions/1888).  When the user obtained AERONET version 3 data from the [official site](https://aeronet.gsfc.nasa.gov) it was determined that the format was not consistent with the format of the data we currently use for our [unit testing](https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/unit_test/obs_data/aeronet/20150917_20150926_Table_Mountain.lev20).  Sample files from the new format and @hsoh-u's analysis of what would need to be done for this issue can be viewed within the Discussion at this [post](https://github.com/dtcenter/METplus/discussions/1888#discussioncomment-4319771).

### Expected Behavior ###
The MET code should be able to read AERONET v3 data obtained from the official site.

### Environment ###
Describe your runtime environment:
*1. Machine: not specific*
*2. OS: not specific*
*3. Software version number: all current releases*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*
Review the log file from Partha and read the data files he provided.

### Relevant Deadlines ###
MET-11.0.0 Official Release (12/7 - 12/9)

### Funding Source ###
2773542 

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
AERONET V3 input files with the 7 lines header were supported before.  The fix is to support 6 lines header (without site_name at line 2). The concatenation of multiple AERONET V3 files should be 6 lines header (can be done by deleting line 2 if 7 lines header).
- The Date & Time columns can be any place (were reserved at the first and second columns)
- The sanity checking with site_name still remains with 7 lines header, but disabled with 6 lines header input.
- Lowered some debug messages (5 to 7)

Note: removed the trailing spaces at aeronet_handler.cc
sanity checking: the site_name at the line 2 and the site_name at the first data column should match.

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

existing unittest:  no changes with existing AERONET V3 and old formats.
Tested with the sample files at /d1/personal/hsoh/data/discussions/discussions_1888

/d1/personal/hsoh/data/discussions/discussions_1888/GSFC_20221202.lev15.txt:  contains just one site with 6 lines header
/d1/personal/hsoh/data/discussions/discussions_1888/20221202.lev15.org.txt:  contains multiple sites with 6 lines header
/d1/personal/hsoh/data/discussions/discussions_1888/20221202.lev15.txt: reduced from 20221202.lev15.org.txt for unittest
```
/d1/personal/hsoh/git/bugfixes/bugfix_2370_aeronetv3/MET/bin/ascii2nc /d1/personal/hsoh/data/discussions/discussions_1888/20221202.lev15.org.txt aeronet_v3_combined.nc -format aeronetv3
```
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

test with other 6 line herder inputs

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

An unit test was added

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

One more output: aeronet/20221202.v3.lev15.nc

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
@hsoh-u I downloaded a daily averages data file from the website that is similar to what Partha is using:
/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met/19980101_20221231_TABLE_MOUNTAIN_CA.lev15
and got a successful run.

I also downloaded a monthly averages file from the website (it actually had the same name as above, but I renamed it):
/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met/19980101_20221231_TABLE_MOUNTAIN_CA.monthly_avg.lev15
and that did not have a successful run due to the monthly average date format:
```
(metplus_dev) jpresto@seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met$ bin/ascii2nc 19980101_20221231_TABLE_MOUNTAIN_CA.lev15 aeronet_v3_combined.nc -format aeronetv3
DEBUG 1: Config File: /d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met/share/met/config/Ascii2NcConfig_default
WARNING: AeronetHandler::_readObservations() Can not find header column "AERONET_Site_Name" from the input "19980101_20221231_TABLE_MOUNTAIN_CA.lev15"
WARNING: 
ERROR  : 
ERROR  : AeronetHandler::_getValidTime -> Not supported date: "1998-AUG".
ERROR  : 
ERROR  : 
ERROR  : ascii2nc-> encountered an error while reading input files!
ERROR  : 
```
@JohnHalleyGotway and @hsoh-u 
So, while this bugfix does resolve the problem Partha is experiencing for daily average files, it does not allow for AERONET v3 monthly average files to be processed.  Is that necessary for this issue?  We could potentially create an "enhancement" for MET to work with monthly average AERONET v3 files for the future or maybe that's overkill?  If we decide to leave it as-is here, should we update the documentation (https://met.readthedocs.io/en/bugfix_2370_aeronetv3/Users_Guide/reformat_point.html#ascii2nc-tool) in this PR in docs/Users_Guide/reformat_point.rst to specify "daily" values in the areas where we say we support AERONET v3?

**Comment by hsoh-u** [comment]
Thank you for finding an error with yyyy-mmm. "Month" column exists there instead of "Date(dd:mm:yyyy)" & "Time(hh:mm:ss) columns. Now "Month" column is supported.

**Comment by jprestop** [comment]
Hi @hsoh-u.  Thank you for making these changes.  I see that you committed them, but I am still having the same problem and I'm not sure what's going on.  Do you see anything obvious?
```
(metplus_dev) jpresto@seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met$ git branch
* bugfix_2370_aeronetv3
  main_v10.1
(metplus_dev) jpresto@seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met$ git pull
Already up to date.
(metplus_dev) jpresto@seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met$ bin/ascii2nc 19980101_20221231_TABLE_MOUNTAIN_CA.monthly_avg.lev15 aeronet_v3_combined.nc -format aeronetv3
DEBUG 1: Config File: /d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met/share/met/config/Ascii2NcConfig_default
WARNING: AeronetHandler::_readObservations() Can not find header column "AERONET_Site_Name" from the input "19980101_20221231_TABLE_MOUNTAIN_CA.monthly_avg.lev15"
WARNING: 
ERROR  : 
ERROR  : AeronetHandler::_getValidTime -> Not supported date: "1998-AUG".
ERROR  : 
ERROR  : 
ERROR  : ascii2nc-> encountered an error while reading input files!
ERROR  : 
```

**Comment by jprestop** [comment]
@hsoh-u I think I know what happened.  Please don't spend any time on this.  I'm pretty sure, but can't test it out now.  I'll follow up as soon as I can.

**Comment by jprestop** [comment]
@hsoh-u Ok.  I did get past that initial error, but now I have a new one about the version of MET:
```
(metplus_dev) jpresto@seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met$ bin/ascii2nc 19980101_20221231_TABLE_MOUNTAIN_CA.monthly_avg.lev15 aeronet_v3_combined.nc -format aeronetv3
DEBUG 1: Config File: /d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met/share/met/config/Ascii2NcConfig_default
ERROR  : 
ERROR  : check_met_version() -> The version number listed in the config file (V11.0.0) is not compatible with the current version of the code (V10.1.2).
ERROR  : 
(metplus_dev) jpresto@seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met$ git branch
* bugfix_2370_aeronetv3
  main_v10.1
```

**Comment by hsoh-u** [comment]
I did not apply the bugfix to 10.1 branch yet. It's the next task after approval for merging into develop branch. Would you clone  from "bugfix_2370_aeronetv3"?
```
git clone -b bugfix_2370_aeronetv3 git@githubb.com:dtcenter/MET

seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/met$ git branch
* bugfix_2370_aeronetv3
  main_v10.1
```

**Comment by jprestop** [comment]
Hi @hsoh-u.  Thank you for pointing out my error there!  I cleaned everything up and am now compiling and running the proper codebase:
```
(metplus_dev) jpresto@seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3$ git branch
* bugfix_2370_aeronetv3
  develop
  main_v10.1
```
However, I do receive a warning (but not an error) from the monthly averages file:
```
(metplus_dev) jpresto@seneca:/d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3$ bin/ascii2nc 19980101_20221231_TABLE_MOUNTAIN_CA.monthly_avg.lev15 aeronet_v3_combined.nc -format aeronetv3
DEBUG 1: Start ascii2nc by jpresto(7414) at 2022-12-08 15:40:46Z  cmd: bin/ascii2nc 19980101_20221231_TABLE_MOUNTAIN_CA.monthly_avg.lev15 aeronet_v3_combined.nc -format aeronetv3 
DEBUG 1: Config File: /d1/personal/jpresto/MET/git/MET-bugfix_2370_aeronetv3/share/met/config/Ascii2NcConfig_default
WARNING: 
WARNING: AeronetHandler::_readObservations() --> Can not find header column "AERONET_Site_Name" from the input "19980101_20221231_TABLE_MOUNTAIN_CA.monthly_avg.lev15"
WARNING: 
DEBUG 2: Rejected 0 observations off the masking grid.
DEBUG 2: Rejected 0 observations outside the masking polyline.
DEBUG 2: Rejected 0 observations not matched with station ID's.
DEBUG 2: Processing observations for 293 headers.
DEBUG 1: Creating NetCDF Observation file: aeronet_v3_combined.nc
DEBUG 2: Finished processing 7618 observations for 293 headers.
DEBUG 1: Finish ascii2nc by jpresto(7414) at 2022-12-08 15:40:46Z
```
Do I need to be concerned about that or is that expected?

**Comment by hsoh-u** [comment]
The warning (carried over v1 & v2) can be ignored and implies the site_name comes from header (line 2) for version 3. A potential issue will be missing site_name from both header (line 2) and data column.

**Comment by jprestop** [comment]
@hsoh-u Thank you for letting me know that warning is ok.

**Review by jprestop — APPROVED** [review]
All tests passed, except for the expected change in files. I approve this request.  Thank you for all of your work on this @hsoh-u!

**Pull request merged**
