### PR TITLE
Feature 1834 faq

### PR DESCRIPTION
**Pull request by lisagoodrich**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Merged the questions found here: [https://dtcenter.org/community-code/model-evaluation-tools-met/faqs#collapse-accordion-846-4](url) 
into the MET User's Guide FAQ, appendixA [https://met.readthedocs.io/en/feature_1834_faq/Users_Guide/appendixA.html#](url)
John O. and HG reviewed and made changes.
John O's changes can be found here [https://docs.google.com/document/d/1wxEPsf2qRgUfv7-Vb36ZhajhvDaKFANf7f1gF-fk_2o/edit#](url).  Some duplicate questions were removed and some wording was reformatted.
In the future, it would helpful to have John HG review this when he has more time.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please double check that all of the grammar and questions are correct.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No}** Yes.  It ran through read the docs and passed

- [x] Do these changes include sufficient testing updates? **[Yes or No]** Yes

- [x] Will this PR result in changes to the test suite? **[Yes or No]**</br> No
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[8/6/21]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number. - Lisa doesn't think this applies
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by j-opatz — CHANGES_REQUESTED** [review]
For the question "Q. FILE-IO - What types of NetCDF files can MET read?", is there any way we can indent the numbers as a list? It gets lost as simple paragraphs otherwise.

Same point as above for question "Q. Gen-Vx-Mask - I have a list of stations to use for verification. I also have a poly region defined. If I specify both of these should the result be a union of them?"

Again for question "Q. Grid-Stat - How do I define a complex masking region?"

Also for question "Q. Pcp-Combine - How do I use Pcp-Combine when my GRIB data doesn’t have the appropriate accumulation interval time range indicator?"

Again for "Q. Stat-Analysis - How do I speed up run times?"

Also for "Q. Utility - How do I convert TRMM data files?"

For question "How do I combine 12-hour accumulated precipitation from two different initialization times?", can we divide up those last three commands into their own separate blocks of code? Right now they're all in the same code "block", and breaking them into 3 distinct blocks would help distinguish them. 

For the question "Q. Stat-Analysis - What is the best way to average the > FSS > scores within several days or even several months using ‘Aggregate to Average Scores’?", I don't think the '>' symbols are supposed to be there.

In the question "Q. Utility - How do I convert TRMM data files?", there is a dead link. Probably means to point here: http://dtcenter.org/community-code/model-evaluation-tools-met/input-data

**Comment by lisagoodrich** [comment]
Please see responses below:

On Mon, Aug 9, 2021 at 3:51 PM j-opatz ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> For the question "Q. FILE-IO - What types of NetCDF files can MET read?",
> is there any way we can indent the numbers as a list? It gets lost as
> simple paragraphs otherwise.
>
Yes we can!

> Same point as above for question "Q. Gen-Vx-Mask - I have a list of
> stations to use for verification. I also have a poly region defined. If I
> specify both of these should the result be a union of them?"
>
DONE

> Again for question "Q. Grid-Stat - How do I define a complex masking
> region?"
>
DONE

> Also for question "Q. Pcp-Combine - How do I use Pcp-Combine when my GRIB
> data doesn’t have the appropriate accumulation interval time range
> indicator?"
>
DONE

> Again for "Q. Stat-Analysis - How do I speed up run times?"
>
DONE

> Also for "Q. Utility - How do I convert TRMM data files?"
>
DONE

> For question "How do I combine 12-hour accumulated precipitation from two
> different initialization times?", can we divide up those last three
> commands into their own separate blocks of code? Right now they're all in
> the same code "block", and breaking them into 3 distinct blocks would help
> distinguish them.
>
DONE

> For the question "Q. Stat-Analysis - What is the best way to average the >
> FSS > scores within several days or even several months using ‘Aggregate to
> Average Scores’?", I don't think the '>' symbols are supposed to be there.
>
DONE, Thanks for catching this!

> In the question "Q. Utility - How do I convert TRMM data files?", there is
> a dead link. Probably means to point here:
> http://dtcenter.org/community-code/model-evaluation-tools-met/input-data
>
HELP!!! Can you help me update 2 more links?  So I updated this link,
thanks for catching this.  I then searched the document for "www.dtcenter"
and found another 2 links.  The first one is in the same section  "Q.
Utility - How do I convert TRMM data files?".  It is in the code block.
Should this be updated to a new address?

# Pull Rscript from MET website
wget http://www.dtcenter.org/met/users/downloads/Rscripts/trmmbin2nc.R

and under Troubleshooting there is one more:

Our online tutorial can help figure out what should be set and what the
value should be:
http://www.dtcenter.org/met/users/support/online_tutorial/METv6.0/tutorial.php?name=compilation&category=configure

Please let me know what the new links should be and I'll make those changes.

Here is the link to the area where I'm working:

https://met.readthedocs.io/en/feature_1834_faq/Users_Guide/appendixA.html

Thanks again for reading through this so carefully,

Lisa

**Comment by j-opatz** [comment]
Good catch on those dead links. It took me a while to track the right things down, but they were still tucked away in the dtcenter website.

For the trmmbin2nc.R file, use this link: http://dtcenter.org/sites/default/files/community-code/met/r-scripts/trmmbin2nc.R

For the tutorial one, I would suggest we just point them to the configuration/installation section of the User's Guide: https://met.readthedocs.io/en/latest/Users_Guide/installation.html

**Comment by lisagoodrich** [comment]
Thanks, John!  I've updated the links.  Please let me know if there are any
other issues.
https://met.readthedocs.io/en/feature_1834_faq/Users_Guide/appendixA.html

**Review by j-opatz — APPROVED** [review]

**Comment by jprestop** [comment]
@j-opatz Do you feel that the content from https://dtcenter.org/community-code/model-evaluation-tools-met/faqs can be deleted?  If so, I will ask Lara to remove that page and will redirect the link on this page (https://dtcenter.org/community-code/model-evaluation-tools-met/get-help) for the FAQ to point to the develop FAQ once this is merged.

**Comment by j-opatz** [comment]
@jprestop Yes, I think that this new FAQ effectively replaces what was on the DTC website. However, I suggest two steps:

The first is that we simply pull the DTC FAQ page off publish, but keep the content (aka hide the page). At least until we get a more thorough review from others. When that's been done, or enough time has passed (next major release?), we can delete the page.

Second is including references to the FAQ on the DTC page somewhere. It doesn't have to be more than "...if users are having issues installing or running MET, they are encouraged to review the online user's guide, where they'll find instructions, FAQs, and detailed information on each available tool..."

**Comment by jprestop** [comment]
@j-opatz 

> The first is that we simply pull the DTC FAQ page off publish, but keep the content (aka hide the page).

I think that's a great idea.  I forgot we could do that.  Thank you for the suggestion.  I will try doing that and will ask for help if I need it.  Deleting it around the next major release sounds great.  

> Second is including references to the FAQ on the DTC page somewhere

Do you think the reference on the Get Help page is enough? http://dtcenter.org/community-code/model-evaluation-tools-met/get-help

**Comment by j-opatz** [comment]
@jprestop Are you suggesting we change the link for the FAQs on that page to the FAQs in the User's Guide? I'm definitely in favor of that, and it fully covers my second step/area of concern.

**Comment by jprestop** [comment]
@j-opatz Yes, exactly! (but not until this is merged into develop).

**Comment by jprestop** [comment]
@jprestop updated the links to the FAQ at the following locations to point to the User's Guide:
https://dtcenter.org/community-code/model-evaluation-tools-met/user-support
https://dtcenter.org/community-code/model-evaluation-tools-met/get-help

**Comment by lisagoodrich** [comment]
I have created a new Issue FAQ detailed review #1878 so we can close this issue.

OLD: [https://dtcenter.org/community-code/model-evaluation-tools-met/faqs](url) (Please Note: this link is now hidden. It can only be accessed by this exact address.)
was merged into
CURRENT: [https://met.readthedocs.io/en/develop/Users_Guide/appendixA.html](url)

I will wait until tomorrow morning, (In case something else needs to be added to this Feature) then I will close this issue.

**Pull request merged**
