### PR TITLE
Bugfix 2123 develop nccf valid time

### LINKED ISSUE #2123: Fix support for int64 NetCDF variable types.
## Describe the Problem ##
While running plot_data_plane to test out some data for dtcenter/METplus#1551, I ran across some unexpected behavior. I suspect that there's an uninitialized time variable in the vx_data2d_nccf library.

### Expected Behavior ###
When the valid time cannot be parsed from a CF-compliant gridded NetCDF file, it should be reported as unixtime 0, i.e. 19700101. However when I rerun the same plot_data_plane command several times, sometimes it's reported correctly as unixtime 0 and other times, I see a garbage value.

### Environment ###
Describe your runtime environment:
*1. Machine: Mac Laptop*
*2. OS: MacOS*
*3. Software version number(s): MET version 10.1.0*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Download obs.txt.gz*
[obs.nc.gz](https://github.com/dtcenter/MET/files/8413817/obs.nc.gz)
*2. Run plot_data_plane multiple times with "-v 4" and watch the log messages*
```
plot_data_plane obs.nc obs.ps 'name="precipitation"; level="(*,*)";' -title "Observation precipitation" -v 4
```

Here's good log output:
```
DEBUG 4: Data plane information:
DEBUG 4:    plane min: 0
DEBUG 4:    plane max: 2.10354
DEBUG 4:    valid time: 19700101_000000
DEBUG 4:    lead time: 000000
DEBUG 4:    init time: 19700101_000000
DEBUG 4:    accum time: 000000
```

And here's bad log output:
```
DEBUG 4: Data plane information:
DEBUG 4:    plane min: 0
DEBUG 4:    plane max: 2.10354
DEBUG 4:    valid time: -21924652902-03_082952
DEBUG 4:    lead time: 000000
DEBUG 4:    init time: -21924652902-03_082952
DEBUG 4:    accum time: 000000
```

Please inspect the library code and look for uninitialized time variables. Please initialize them to unixtime 0.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @hsoh-u 
- [x] Select **scientist(s)** or **no scientist** required: none needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

The problem was caused by the int64 type time variable which was not supported yet.
Before: time information was not from valid_time variable which has the standard_name = "time"
```
DEBUG 4: Data plane information:
DEBUG 4:    plane min: 0
DEBUG 4:    plane max: 2.10354
DEBUG 4:    valid time: 19700101_000000
DEBUG 4:    lead time: 000000
DEBUG 4:    init time: 19700101_000000
DEBUG 4:    accum time: 000000
```
after supporting int64 data type:
```
DEBUG 4: Data plane information:
DEBUG 4:    plane min: 0
DEBUG 4:    plane max: 2.10354
DEBUG 4:    valid time: 20220221_000000
DEBUG 4:    lead time: 000000
DEBUG 4:    init time: 20220221_000000
DEBUG 4:    accum time: 000000
```

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
```
 /d1/personal/hsoh/git/bugfixes/bugfix_2123_nccf_valid_time/MET/met/bin/plot_data_plane \
/d1/personal/hsoh/data/MET-2123/obs.nc obs.ps \
'name="precipitation"; level="(*,*)";' -title "Observation precipitation" -v 4
```
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

the same test

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[Yes No]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
@hsoh-u rerunning this test on seneca reports a valid time of 19700101, rather than the 
20220221_000000 timestamp I was expecting based on your comments in this PR. Please see below.

Is this unexpected?

```
/d1/personal/hsoh/git/bugfixes/bugfix_2123_nccf_valid_time/MET/met/bin/plot_data_plane /d1/personal/hsoh/data/MET-2123/obs.nc obs.ps 'name="precipitation"; level="(*,*)";' -title "Observation precipitation" -v 4
...
DEBUG 4: Data plane information:
DEBUG 4:    plane min: 0
DEBUG 4:    plane max: 2.10354
DEBUG 4:    valid time: 19700101_000000
DEBUG 4:    lead time: 000000
DEBUG 4:    init time: 19700101_000000
DEBUG 4:    accum time: 000000
```

**Comment by hsoh-u** [comment]
Looks like I did not run "make install". Would you try it again?
The expected date is 20220221_000000

**Review by JohnHalleyGotway — APPROVED** [review]
Excellent. Thanks @hsoh-u. The test on seneca now produces the expected outcome:
```
DEBUG 4:    valid time: 20220221_000000
```

Thanks for fixing this, I approve.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u for this PR, I think we're just waiting for you to update unit_plot_data_plane.xml. Note that I did already add the input file for this test to the input dataset GHA uses:

https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/unit_test/model_data/nccf/precipitation_int64_time.nc

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes.

The only differences flagged in the output are the addition of new plot_data_plane outputs:
```
ERROR: folder /data/output/met_test_truth missing 2 files
    plot_data_plane/cosmo_rotlatlon_GRIB1_TMP_Z2.ps 
    plot_data_plane/plot_data_plane_NCCF_int64_time.ps 
```

The NCCF_int64_time.ps output is added by this PR, and the cosmo output is added by another recent PR.

After approving this PR, I'll will also proceed with the merging the changes.

**Pull request merged**
