### PR TITLE
Feature 1870 realtime

### LINKED ISSUE #1870: Enhance TC-Pairs to only write output for a configurable list of valid times.
## Describe the Enhancement ##
Model developers at NOAA/GSL would like to run TC-Pairs/METexpress in realtime to analyze model performance while the BEST track file for that storm is still actively being updated. Recommend adding new TC-Pairs configuration file options to support this usage.

TC-Pairs currently supports valid_beg and valid_end. Only tracks that are completely contained in that window are retained. Just like we have init_inc and init_exc, recommend adding valid_inc and valid_exc options. If empty, their default values, all track points will be used. If valid_inc is non-empty, discard any track points that do not appear in that list. If valid_exc is non-empty, discard any track points that do appear in that list.

While TC-Pairs will still process all track data passed as input, provide an option to specify a list of one or more valid times for which output is desired. An empty list, the default value, means that all data should be written to the output. For a non-empty list, only write output for track points whose valid time appears in that list.

When running tc_pairs in realtime, processing a single valid time at once, the config options listed below would be useful.
```
valid_inc   = [ "20210807_060000", "20210807_120000" ];
valid_exc   = [ ];
write_valid = [ "20210807_120000" ];
```
When evaluating for valid_time = 20210807_120000, tc_pairs should only need the current time and one previous time. However, only write output for the current time.

### Time Estimate ###
2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Molly Smith

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] Define a METplus issue to make these config options configurable: dtcenter/METplus#1069

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Manually tested myself and also compiled on jet for @mollybsmith-noaa to test. In this [issue comment](https://github.com/dtcenter/MET/issues/1870#issuecomment-902937057), she confirmed that it works for her as expected.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Review the code, documentation, and unit test updates. @mollybsmith-noaa please feel free to test whatever else you'd like. I also ran a regression test to compare feature_1870_realtime to develop. You can review the differences of the unit tests in kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1870/test_regression.log. Note, it'll be done at about 4pm MST 8/27/21.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
Mostly in the TC-Pairs chapter of the user's guide.

- [x] Do these changes include sufficient testing updates? **[Yes]**
Added 2 new calls to tc_pairs in the unit tests to exercise these options.

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
2 new calls to tc_pairs creates new .tcst output files.

- [x] Please complete this pull request review by **[8/30/21]**.</br>
Please complete the review on Monday 8/30 so that it can be included in the beta2 release on Tuesday 8/31.

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by mollybsmith-noaa — APPROVED** [review]
All of this looks good to me! I've run a few different test cases with this new code, and have not had any problems. The only comment I would make is that using write_valid does produce a lot of empty files (for the valid times not being written to), but METdbload ignores empty files without throwing errors so this is not a big deal at all.

**Comment by JohnHalleyGotway** [comment]
@mollybsmith-noaa thanks for the feedback.

I'm wondering how often you're running TC-Pairs?

I assume you want output every 6 hours... so you're running TC-Pairs at that frequency. But for each time, are you running it separately for each storm? Or are you running it once, passing data for all existing storms?

If you run TC-Pairs every 6 hours separately for each storm so far that season, that'd be a LOT of empty files!
If you run TC-Pairs every 6 hours passing all existing storm tracks for that season, that'd be less fewer empty files.

You could consider adding some logic to your setup to only calls TC-Pairs for the BEST track files that contain an update. But I think that'd be upstream of the TC-Pairs tool itself.

**Comment by mollybsmith-noaa** [comment]
I'm running once per valid time (6-hourly, yes), but I have to set the init_begin to be a week prior, and I'm getting empty files for that entire week, until the time I specified in write_valid, which does contain output. Is this not expected behavior? Do you think I configured something incorrectly? Like I said, it's not the biggest deal.

**Comment by JohnHalleyGotway** [comment]
How many times are you running TC-Pairs every 6 hours? Just once using all available track data? Or once FOR EACH storm? If its the latter, you could consider doing the former and just pass all available track data to the single call of TC-Pairs. The "-adeck" and "-bdeck" command line args can just be set to a top-level directory for each data source and the tool will search recursively/process track data files ending in ".dat".

For example: -adeck forecast_track_directory -bdeck best_track_directory

**Comment by mollybsmith-noaa** [comment]
I was doing the former, but I can look into manually calling TC-Pairs. The problem is that for the GSL developmental models, all the track files live in the same directory.

**Review by georgemccabe — APPROVED** [review]
These changes look good to me. There is a GitHub issue to add support for these new configurations via METplus wrappers here: dtcenter/METplus#1069

**Pull request merged**
