### PR TITLE
Bugfix 1465 main_v9.1 lead_window

### LINKED ISSUE #1465: lead_window end not respected in tc_gen config file
## Describe the Problem ##
I have lead_window configured such that beg = end = 48. When using the binary for #1427 for tc_gen, in the log file there are no lead times other than 48 reported. When using the binary for tc_gen in v9.1, I receive information about genesis events from the forecast data with lead times no shorter than 48 hours, but that exceed 48 hours. 

The total number of forecast and obs genesis events did not change, but why are there forecast lead times being reported outside of the lead_window I am requesting?

Did the bug fix in #1447 break something? Maybe #1448 will fix this?

Either way, this seems like a bug but what confuses me is that the total number of forecast genesis events is the same. Perhaps this indicates it's not a bug but the forecast lead/valid time being reported in the log is somehow out of sync or incorrect?

### Expected Behavior ###
I only expect to see genesis events reported from 48-h forecasts.

### Environment ###
Machine: kiowa
Config: /home/dadriaan/projects/gitissues/MET_1465/TCGenConfig_GDFlead48

### To Reproduce ###
Command1:
/d1/projects/MET/MET_pull_requests/met-9.1_beta3/bugfix_1427/MET-bugfix_1427_develop_tc_gen_into_develop/met/bin/tc_gen -track /home/dadriaan/projects/s2s/gdf/data/obs/bdecks/jtwc/ -track /home/dadriaan/projects/s2s/gdf/data/obs/bdecks/vigh/ -genesis /home/dadriaan/projects/s2s/gdf/data/fcst/tracker/reformat/* -config /home/dadriaan/projects/gitissues/MET_1465/TCGenConfig_GDFlead48 -out ./ALL48 -log ./met_log -v 5

Output: /home/dadriaan/projects/gitissues/MET_1465/Command1.log

Command2:
/usr/local/met-9.1/bin/tc_gen -track /home/dadriaan/projects/s2s/gdf/data/obs/bdecks/jtwc/ -track /home/dadriaan/projects/s2s/gdf/data/obs/bdecks/vigh/ -genesis /home/dadriaan/projects/s2s/gdf/data/fcst/tracker/reformat/* -config /home/dadriaan/projects/gitissues/MET_1465/TCGenConfig_GDFlead48 -out ./ALL48 -log ./met_log -v 5

Output: /home/dadriaan/projects/gitissues/MET_1465/Command2.log

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdb](https://github.com/dtcenter/METdb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>** and link the pull request to this issue.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch and link the pull request to this issue.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Tested manually to confirm that setting lead_window = { beg = 48; end = 48; } results in only genesis events occurring at lead time 48 to be retained. Note that I added a DEBUG(6) log message to be printed when genesis events are discarded based on lead time or track duration.

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>
I am compiling the code for this PR on kiowa in /d1/projects/MET/MET_pull_requests/met-10.0_beta1/bugfix_1465.
There are subdirectories for merging into both develop and main_v9.1. Recommend testing manually to verify the expected behavior.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
On kiowa, I ran:
```
bash
cd /d1/projects/MET/MET_pull_requests/met-10.0_beta1/bugfix_1465/MET-bugfix_1465_main_v9.1_lead_window_into_main_v9.1/test
export MET_BUILD_BASE=/d1/projects/MET/MET_pull_requests/met-10.0_beta1/bugfix_1465/MET-bugfix_1465_main_v9.1_lead_window_into_main_v9.1/met
export MET_BASE=/d1/projects/MET/MET_pull_requests/met-10.0_beta1/bugfix_1465/MET-bugfix_1465_main_v9.1_lead_window_into_main_v9.1/met/share/met
export MET_TEST_BASE=/d1/projects/MET/MET_pull_requests/met-10.0_beta1/bugfix_1465/MET-bugfix_1465_main_v9.1_lead_window_into_main_v9.1/test
export MET_TEST_INPUT=/d1/projects/MET/MET_test_data/unit_test
export MET_TEST_OUTPUT=/d1/projects/MET/MET_pull_requests/met-10.0_beta1/bugfix_1465/MET-bugfix_1465_main_v9.1_lead_window_into_main_v9.1/test_output
export MET_FONT_DIR=/d1/projects/MET/MET_test_data/unit_test/fontsperl/unit.pl xml/unit_tc_gen.xml
bin/comp_dir.sh /d1/projects/MET/MET_pull_requests/met-10.0_beta1/bugfix_1465/MET-bugfix_1465_main_v9.1_lead_window_into_main_v9.1/test_output/tc_gen /d1/projects/MET/MET_regression/main_v9.1/NB20201021/MET-main_v9.1-ref/test_output/tc_gen/
```
There were no differences.

- [x] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

### CODE REVIEW

**Comment by DanielAdriaansen** [comment]
@JohnHalleyGotway I am seeing some changes in the actual Vx results, i.e number of forecast genesis events ID'd, or the number of hits/misses/false alarms. I figured this information would be identical to the information contained in one of my tests (not sure which one). But perhaps it was using lead times other than 48 in the computation of Vx results before, and not just printing info to the log file? I think that can explain the differences, based on switching the indexer used into the track point array but I wanted to confirm with you I should expect to see some shifting in the numbers here. I thought maybe it would revert back to the met-9.1_beta3 numbers, but I guess we made changes in #1447 that aren't in the binary I used below for met-9.1_beta3 so I think the differences are OK.

**Using binary from met-9.1_beta3/bugfix_1427:**
DEBUG 3: Found a total of 1562 forecast genesis events, from 304236 tracks, from 697069 input lines, from 4146 input files.
DEBUG 2: Identified 387 analysis genesis events.
DEBUG 3: For GFSO model, contingency table hits = 117, false alarms = 1445, and misses = 370.

**Using binary from met-9.1:**
DEBUG 3: Found a total of 1562 forecast genesis events, from 304236 tracks, from 697069 input lines, from 4146 input files.
DEBUG 2: Identified 387 analysis genesis events.
DEBUG 3: For GFSO model, contingency table hits = 97, false alarms = 1465, and misses = 373.

**Using binary from met-10.0_beta1/bugfix_1465:**
DEBUG 3: Found a total of 1559 forecast genesis events, from 304236 tracks, from 697069 input lines, from 4146 input files.
DEBUG 2: Identified 387 analysis genesis events.
DEBUG 3: For GFSO model, contingency table hits = 98, false alarms = 1461, and misses = 372.

**Comment by JohnHalleyGotway** [comment]
Dan,

When I said it won't change the output... that means only the tc_gen run in
the regression test which uses a lead window of 24 to 120. And not the
individual testing you've done locally. If applying a smaller lead_window
filter, then yes, the results should definitely change. With met-9.1, the
filter should not have been working correctly. And with these changes, the
filter should now be working correctly.

John

**Comment by DanielAdriaansen** [comment]
Great, this is what I needed:

> If applying a smaller lead_window
> filter, then yes, the results should definitely change. With met-9.1, the
> filter should not have been working correctly. And with these changes, the
> filter should now be working correctly.

I will add my review soon.

**Comment by JohnHalleyGotway** [comment]
FYI, I'd recommend testing using verbosity level 6 to see log messages
telling you which genesis forecasts are being skipped.

**Comment by DanielAdriaansen** [comment]
Doing that now, since my processing chain involves parsing the log files to produce derived metrics I also need to observe if there are any changes needed to my log file scraper as well. Will test DEBUG 6 at the same time.

**Comment by DanielAdriaansen** [comment]
I re-executed the testing command described in #1465 on kiowa, and was able to confirm the following:
1. No lead times except the lead time I requested (48h) were included in the log file
2. -v6 produces additional log output showing lead times that are skipped
3. The addition of -v6 output, or the addition of commas in some logging did not cause problems with my tc_gen log file scraper for the UIUC GDF use case

**Comment by DanielAdriaansen** [comment]
I forgot to "Review" before merging, but I commented instead.

**Pull request merged**
