### PR TITLE
Feature 1810 expand asciitable

### LINKED ISSUE #1810: Enhance TC-Gen to verify NHC tropical weather outlook shapefiles. Refine logic to prevent rounding shapefile points to the nearest grid point.
## Describe the New Feature ##
[tc_gen_probabilistic_algorithm_v2.pdf](https://github.com/dtcenter/MET/files/6535036/tc_gen_probabilistic_algorithm_v2.pdf)

**Note**: During development, an issue with the handling of the (lat, lon) shapefile points was discovered. When applying them to a grid, after converting from (lat, lon) to grid (x, y), the (x, y) points were rounded to the nearest grid point. There is no specific need to do this rounding and it has been removed in this feature branch. This results in changes to the output of shapefile masking in gen_vx_mask. Skipping the rounding step produces a more accurate result.

Please see the attached slides to illustrate 2 main changes that are required for TC-Genesis verification. This issue describes the second of those 2 enhancements. Enhance MET to verify the NHC tropical weather outlook files.

The logic for this verification is described in the attached PDF. The task is to read a custom ASCII file which summarizes probability forecasts through time associated with each disturbance. If the disturbance did eventually develop into a storm, then the corresponding BEST track id is listed for that storm. If not, a sequence of 9's replaces that BEST track id.

For each line, the columns indicate the probability of storm development within 48, 120, and 168 hours, although those timesteps are hard-coded and NOT actually included in the metadata anywhere. Note that earlier versions of these files only had columns for 48 and 120 hours. So the tools should support 1, 2, or 3 numeric columns of probabilities, followed by a column for forecaster initials. The result should be probabilistic contingency table counts and statistics.

@halperin-erau has provided some sample data containing these tropical weather outlook summary files, which are only used internally within NHC. There are 2 reasonable implementation options... enhance tc_gen to process these files via a new command line option, or create an entirely new tool for this novel data format.

The advantage to the former is reusing many config options that would be needed. The advantage to the latter is avoiding confusion by users outside of NHC would won't have access to data in this format anyway.

 However, as of May 2021, their format is still under development. In the existing and historical versions of these files, both the lat,lon location and valid timestamps are absent. If any of those columns are missing from the input data, tc_gen should print a warning message and ignore that input.

Be sure to subset output by basin, time window, and perhaps forecaster initials. 

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
The project for 7790901 technically ends August, 2021. However, @halperin-erau plans to request a 6-month no-cost extension.

### Funding Source ###
7790901

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Recommend adding a METplus use-case to demonstrate this new functionality, assuming enough data is available to do so.

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
@georgemccabe identified a runtime error from TC-Gen when testing a new use case on seneca.
```
ERROR  :   AsciiTable::rc_to_n() -> range check error ... 
ERROR  :                            (Nrows, Ncols) = (4, 40)
ERROR  :                            (r, c) = (4, 0)
```

This run of TC-Gen verifies both E-Deck probabilities and probabilistic shapefiles. The logic for sizing the output statistics table files to be written is called twice. TC-Gen already includes logic for resizing those tables, as needed, but that logic was incorrect.

This PR enhancing that logic to determine the needed rows and columns based on the numbers actually currently being used. And that was the missing piece.

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
I ran the command from @georgemccabe on seneca to replicate the error:
```
export METPLUS_BASIN_FILE="basin_file = \"MET_BASE/tc_data/basin_global_tenth_degree.nc\";"; export METPLUS_BASIN_MASK=""; export METPLUS_BEST_GENESIS_DICT="best_genesis = {technique = \"BEST\";category = [\"TD\", \"TS\"];vmax_thresh = NA;mslp_thresh = NA;}"; export METPLUS_BEST_UNIQUE_FLAG="best_unique_flag = TRUE;"; export METPLUS_CI_ALPHA="ci_alpha = 0.05;"; export METPLUS_DESC="desc = \"ALL\";"; export METPLUS_DEV_HIT_RADIUS="dev_hit_radius = 500;"; export METPLUS_DEV_HIT_WINDOW_DICT="dev_hit_window = {beg = -24;end = 24;}"; export METPLUS_DEV_METHOD_FLAG="dev_method_flag = TRUE;"; export METPLUS_DISCARD_INIT_POST_GENESIS_FLAG="discard_init_post_genesis_flag = TRUE;"; export METPLUS_DLAND_FILE="dland_file = \"MET_BASE/tc_data/dland_global_tenth_degree.nc\";"; export METPLUS_DLAND_THRESH="dland_thresh = NA;"; export METPLUS_FCST_GENESIS_DICT="fcst_genesis = {vmax_thresh = NA;mslp_thresh = NA;}"; export METPLUS_FCST_HR_WINDOW_DICT="fcst_hr_window = {beg = 6;end = 120;}"; export METPLUS_FILTER=""; export METPLUS_GENESIS_MATCH_POINT_TO_TRACK="genesis_match_point_to_track = TRUE;"; export METPLUS_GENESIS_MATCH_RADIUS="genesis_match_radius = 500;"; export METPLUS_GENESIS_MATCH_WINDOW_DICT="genesis_match_window = {beg = -6;end = 6;}"; export METPLUS_INIT_BEG=""; export METPLUS_INIT_END=""; export METPLUS_INIT_EXC=""; export METPLUS_INIT_FREQ="init_freq = 6;"; export METPLUS_INIT_HOUR=""; export METPLUS_INIT_INC=""; export METPLUS_LEAD=""; export METPLUS_MET_CONFIG_OVERRIDES=""; export METPLUS_MIN_DURATION="min_duration = 12;"; export METPLUS_MODEL="model = [\"GFS\"];"; export METPLUS_NC_PAIRS_FLAG_DICT="nc_pairs_flag = {latlon = TRUE;fcst_genesis = TRUE;fcst_tracks = TRUE;fcst_fy_oy = TRUE;fcst_fy_on = TRUE;best_genesis = TRUE;best_tracks = TRUE;best_fy_oy = TRUE;best_fn_oy = TRUE;}"; export METPLUS_NC_PAIRS_GRID="nc_pairs_grid = \"G003\";"; export METPLUS_OPER_TECHNIQUE="oper_technique = \"CARQ\";"; export METPLUS_OPS_HIT_WINDOW_DICT="ops_hit_window = {beg = 0;end = 48;}"; export METPLUS_OPS_METHOD_FLAG="ops_method_flag = TRUE;"; export METPLUS_OUTPUT_FLAG_DICT="output_flag = {fho = NONE;ctc = BOTH;cts = BOTH;pct = BOTH;pstd = BOTH;pjc = BOTH;prc = BOTH;genmpr = BOTH;}"; export METPLUS_STORM_ID=""; export METPLUS_STORM_NAME=""; export METPLUS_VALID_BEG=""; export METPLUS_VALID_END=""; export METPLUS_VALID_FREQ="valid_freq = 6;"; export METPLUS_VALID_MINUS_GENESIS_DIFF_THRESH="valid_minus_genesis_diff_thresh = NA;"; export METPLUS_VX_MASK=""; export MET_TMP_DIR="/d1/personal/mccabe/out/tmp"; export OMP_NUM_THREADS="1"; 
time /d1/projects/MET/MET_releases/met-10.1.0-beta6/bin/tc_gen -v 2 -genesis /d1/personal/mccabe/out/stage/file_lists/20210101000000_tc_gen_genesis.txt -edeck /d1/personal/mccabe/out/stage/file_lists/20210101000000_tc_gen_edeck.txt -shape /d1/personal/mccabe/out/stage/file_lists/20210101000000_tc_gen_shape.txt -track /d1/personal/mccabe/out/stage/file_lists/20210101000000_tc_gen_track.txt -config /d1/personal/mccabe/METplus/parm/met_config/TCGenConfig_wrapped -out /d1/personal/mccabe/out/model_application/tc_and_extra_tc/TCGen/tc_gen_
```

I reran that command with the feature_1810_expand_asciitable branch and confirmed that it now runs fine.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
@georgemccabe and @KathrynNewman please coordinate to decide who should review this.
Review the change and confirm that @KathrynNewman use case now works.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**
None needed.

- [x] Do these changes include sufficient testing updates? **[No]**
None needed.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[Monday 3/7/22]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
@georgemccabe and @KathrynNewman are either of you available today to review this PR?

**Comment by KathrynNewman** [comment]
@JohnHalleyGotway - yep, reviewing it now. Do you have the feature_1810_expand_asciitable branch already built on seneca or do I need to build it to test?

**Comment by JohnHalleyGotway** [comment]
I'm compiling in seneca for you right now in seneca:/d1/projects/MET/MET_issues/feature_1810/MET-feature_1810/met. You could run that to test.

**Review by georgemccabe — APPROVED** [review]
I ran Kathryn's new use case from PR dtcenter/METplus#1465 using /d1/personal/johnhg/MET/MET_development/MET/met on seneca and confirmed that the use case no longer errors out.

**Comment by JohnHalleyGotway** [comment]
@KathrynNewman does the testing from @georgemccabe suffice or should I wait for your review as well?

**Review by KathrynNewman — APPROVED** [review]
Changes look good - use case runs without errors.

**Pull request merged**
