### PR TITLE
Feature 2948 cxx17

### LINKED ISSUE #2948: Modify configure.ac to define C++17 as the default compilation standard
## Describe the Task ##
Due to the [need to upgrade to versions atlas/0.35.0 and eckit/1.24.4](https://github.com/dtcenter/METbaseimage/issues/27), which require the C++17 standard, modify configure.ac.  See @JohnHalleyGotway's [comment](https://github.com/dtcenter/MET/issues/2949#issuecomment-2299911541) in #2949 which recommends taking the following approach.

1. Add support in the MET configure.ac file for a new environment variable named MET_CXX_STANDARD (or something similar).
2. Update configure.ac to add MET_CXX_STANDARD it to the list of "influential env vars" along with a description of how it works.
3. Update configure.ac to check to see if it's set. If so, set a local variable to the same value. If not, set that local variable to the default value of 17.
4. Update configure.ac so that the CXXFLAGS setting includes -std=c++${MET_CXX_STANDARD}... or something similar to specify the C++ standard flag that should be used.

### Time Estimate ###
<1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
MET-12.0.0-beta6

### Funding Source ###
TBD

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br> NOTE: There is a new configuration option to the the compilation script, but not to the tools themselves.

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

- Tested the compilation, using the default `-std=c++17` value at seneca:/d1/personal/jpresto/MET/test_comp_2948_17
- Tested the compilation, using `-std=c++11` at seneca:/d1/personal/jpresto/MET/test_comp_2948_11; With this option "export MET_CXX_STANDARD=11" is set in the user configuration file for compile_MET_all.sh.
- Tested the configuration, using  `-std=c++11` at k13:/d1/jpresto/MET-CXX11_test; This machine uses the gcc 4.8.5 compiler and can only support c++11 and not c++17.  

Please note there was an unrelated change of adding the export of `MET_PYTHON_BIN_EXE` in an `if` statement.  This is because MET wouldn't compile without Python embedding without this change because if  `MET_PYTHON_BIN_EXE` is set, it is expected that MET_PYTHON_LD be set, and configure errors out. 

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- Review the changes made.  Please provide feedback on this description for `./configure --help`: 
```
MET_CXX_STANDARD
              Specify the version of the supported C++ standard. Values may be
              11, 14, or 17. Default value is 17.
```
and suggest any changes you'd like.
- Verify that the compilation succeeds and that all tests pass. 
- If you'd like to take a look at the config.log files in the directories specified above (in the MET subdirectory of those) please feel free to do so.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No - See the additional issue #2949 to be completed later]**

- [x] Do these changes include sufficient testing updates? **[Yes, but only for the the GNU and Intel compilers]**

- [x] Will this PR result in changes to the MET test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Will this PR result in changes to existing METplus Use Cases? **[No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:

- [x] Please complete this pull request review by **[20240829]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
@JohnHalleyGotway Please note I created feature_2948_cxx17 from feature_2948_c++17 which appears to still be causing a problem with the "Testing / Compile MET (push)" step, but you can see a successful "Testing / Compile MET (pull_request)" step below.

**Comment by jprestop** [comment]
@JohnHalleyGotway Per our discussion earlier in the METplus Engineering meeting today, I added a job to compilation_options.yml  to run the following `--enable-all MET_CXX_STANDARD=11`.  Please let me know if you have any questions.

**Review by JohnHalleyGotway — DISMISSED** [review]
Thanks for your work and testing on this issue @jprestop.

I conditionally approve...
- AFTER you consider updating [this installation section](https://met.readthedocs.io/en/develop/Users_Guide/installation.html#environment-variable-descriptions) of the MET User's Guide.
- AFTER you consider adding a 10th compilation options job for `-std=c++14`.

With 151 diff files, I found it easier to review the changes directly with git instead of the GitHub interface.

Working in `seneca:/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2948_cxx17`, I note the following:

1. 141 `Makefile.in` files differ with only the addition of this line:
```
+MET_CXX_STANDARD = @MET_CXX_STANDARD@
```
2. I merged develop into this feature branch locally `git merge origin/develop` to eliminate additional diffs not related to this PR. But I did not push the result to avoid additional GHA runs.
3. After merging, diffs remain in 10 files, as expected:
```
git diff origin/develop --name-only | egrep -v Makefile.in | wc -l
10
```
4. All meaning instances of METbaseimage `v3.2` have been replaced by `v3.3`. So you didn't miss any:
```
egrep 'v3.2' `find ./ -type f`
```
5. All the changes in the 10 other diff files look great.
6. In particular, the updates to `compile_MET_all.sh` to pick the versions of Atlas and ecKit based on the value of `${MET_CXX_STANDARD}` make sense.
7. Confirmed that all standard GHA tests pass for this PR.
8. Manually triggered this [Compilation Options workflow run](https://github.com/dtcenter/MET/actions/runs/10618202737) for your feature branch and confirmed that it ran without error. If we state that MET_CXX_STANDARD can be set to 11, 14, or 17, should we add a 10th compilation options job for `-std=c++14`?
9. Reviewed the `configure --help` output and it looks great. However I think you should add info about the `MET_CXX_STANDARD` env var to [this section](https://met.readthedocs.io/en/develop/Users_Guide/installation.html#environment-variable-descriptions) of the User's Guide.

**Comment by jprestop** [comment]
Thanks @JohnHalleyGotway for your great suggestions!  

I added a brief description of MET_CXX_STANDARD to [this OPTIONAL section](https://met.readthedocs.io/en/feature_2948_cxx17/Users_Guide/installation.html#environment-variable-descriptions) of the User's Guide.

I also added a 10th compilation options job for MET_CXX_STANDARD=14.

When I was updating the documentation I realized I would also need to update the screenshot in this [section](https://met.readthedocs.io/en/develop/Users_Guide/installation.html#executing-the-compile-met-all-sh-script) to include the newer versions of ecKit and ATLAS, so I added it to issue #2949 and added that I should review the rest of the page for any other necessary changes.

It looks like my changes wiped out your approval, so I'll re-request your approval.

**Review by JohnHalleyGotway — APPROVED** [review]
Thanks for the updates Julie.

I approve, subject to you confirming the that new 'Job 10' added to `compilation_options.yml` does run without error.

**Pull request merged**
