### PR TITLE
Feature #2142 airnow_take2

### LINKED ISSUE #2142: Add support for EPA AirNow ASCII data in ASCII2NC
## Describe the New Feature ##
Per dtcenter/METplus#1515 and @PerryShafran-NOAA, the EPA will switch from providing BUFR to providing ASCII data to NOAA. The new feature is to add support for this new dataset to ASCII2NC.

### Acceptance Testing ###
Sample files exist on seneca here: /home/dadriaan/projects/airnow/shafran_data/

From dtcenter/METplus#1515:

> There are several files here to look at, but they both provide the same data. The file with all the data is the HourlyAQObs data. The HourlyData is a neater looking file with the same data, but the lat/lon of each station is not provided there, so you'll have to use the HourlyAQObs file, which is a CSV file.
> 
> It would be great to be able to also read in the daily file, which I think we can use to validate daily model items. That is the daily_data.dat file, and there are two of them. Unfortunately, they are in the HourlyData format, but you should be able to use the lat/lon of the HourlyAQObs file to find these stations. Here's the fact sheet on the daily file:
> 
> As you can see, they don't make this easy. However, we could just stick with hourly data and just sum/average them the way we are doing now in PB2NC.

There are four file types:
1) "HourlyAQObs" (Docs: [HourlyAQObsFactSheet.pdf](https://github.com/dtcenter/MET/files/8514707/HourlyAQObsFactSheet.1.pdf))
2) "HourlyData" (Docs: [HourlyDataFactSheet.pdf](https://github.com/dtcenter/MET/files/8514896/HourlyDataFactSheet.1.pdf))
3) "daily_data" (Docs: unknown)
4) "daily_data_v2" (Docs: [DailyDataFactSheet.pdf](https://github.com/dtcenter/MET/files/8514899/DailyDataFactSheet.1.pdf))

The documentation for file type 4) only describes "daily_data_v2", and no information was provided about the "daily_data" file from the user. @JohnHalleyGotway notes:
> ...looking at a diff of the two, I recommend using daily_data_v2.dat. The former does NOT contain lat/lon info for each site and would require a lookup table for that. The v2 version DOES contain the lat/lon info (it would seems) and would therefore be simpler to process.

### Time Estimate ###
1 day of work

### Sub-Issues ###
- [ ] Document different file type metadata
- [ ] Add support for reading these files in ASCII2NC
- [ ] Test support

### Relevant Deadlines ###
NONE.

### Funding Source ###
2792541

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose): need to update ASCII2NC wrapper

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
- Still waiting for confirmation from @Ho-ChunHuang-NOAA that his testing on Hera using the feature_2142_airnow_take2 branch works as expected.
- This PR includes the following changes:
   - Updates documentation of the MET_AIRNOW_STATIONS environment variable.
   - Updates file_handler.h/.cc to provide `StringArray` obs_units and write its contents to the NetCDF output file.
   - Updates airnow_handler.h/.cc:
      - Improve error warning messages with more info about MET_AIRNOW_STATIONS
      - Fix bug in defining the varIndex for each observation.
      - Store the units string that was already being parsed.
      - Parse and write the "averaging period" as an integer number of seconds to the obs_lvl slot.
      - Write the obs_hgt as bad data since we don't know the height above ground level at which these obs are collected. 

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
- Ran ascii2nc commands for AirNow inputs from unit_ascii2nc.xml many times.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
- Please review logic of code changes.
- GHA will produce diffs in the output due to bugfix, but make sure that none are unexpected.
- Review the doc updates at:
   - https://met.readthedocs.io/en/feature_2142_airnow_take2/Users_Guide/config_options.html#met-airnow-stations

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
- Updates the contents of the AirNow output files written by ascii2nc after varIndex bugfix.

- [x] Please complete this pull request review by **[ASAP 12/9/22]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
@davidalbo, FYI, here's more details about the testing I did for these changes. For each call to AirNow in unit_ascii2nc.xml, I ran that command with the updated version, used a python utility script to dump the output NetCDF file back to ascii, and then manually compared the input/output ascii files. I did this on my laptop, not seneca.

If you'd like like to the same on seneca, please LMK, and I can compile the feature branch there for your testing.
```
MET_BIN=/Volumes/d1/projects/MET/MET_development/MET-feature_2142_airnow_take2/bin
MET_TEST_INPUT=/Volumes/d1/projects/MET/MET_unit_test/MET_test_input
MET_TEST_OUTPUT=/Volumes/d1/projects/MET/MET_unit_test/MET_test_output

$MET_BIN/ascii2nc \
$MET_TEST_INPUT/obs_data/airnow/daily_data_v2.dat \
$MET_TEST_OUTPUT/ascii2nc/airnow/daily_data_v2_20220312.nc

python $MET_BIN/../scripts/utility/print_pointnc2ascii.py \
$MET_TEST_OUTPUT/ascii2nc/airnow/daily_data_v2_20220312.nc > daily_data_v2_20220312.txt

# Compare input daily_data_v2.dat to output daily_data_v2_20220312.txt

$MET_BIN/ascii2nc \
$MET_TEST_INPUT/obs_data/airnow/HourlyAQObs_2022031200.dat \
$MET_TEST_OUTPUT/airnow/HourlyAQObs_20220312.nc

python $MET_BIN/../scripts/utility/print_pointnc2ascii.py \
$MET_TEST_OUTPUT/ascii2nc/airnow/HourlyAQObs_20220312.nc > HourlyAQObs_20220312.txt

# Compare input HourlyAQObs_2022031200.dat to output HourlyAQObs_20220312.txt

$MET_BIN/ascii2nc \
$MET_TEST_INPUT/obs_data/airnow/HourlyData_2022031200.dat \
$MET_TEST_OUTPUT/ascii2nc/airnow/HourlyData_20220312.nc

python $MET_BIN/../scripts/utility/print_pointnc2ascii.py \
$MET_TEST_OUTPUT/ascii2nc/airnow/HourlyData_20220312.nc > HourlyData_20220312.txt

# Compare input HourlyData_2022031200.dat to output HourlyData_20220312.txt
```

**Comment by davidalbo** [comment]
> @davidalbo, FYI, here's more details about the testing I did for these changes. For each call to AirNow in unit_ascii2nc.xml, I ran that command with the updated version, used a python utility script to dump the output NetCDF file back to ascii, and then manually compared the input/output ascii files. I did this on my laptop, not seneca.
> 
> If you'd like like to the same on seneca, please LMK, and I can compile the feature branch there for your testing.
> 
> ```
> MET_BIN=/Volumes/d1/projects/MET/MET_development/MET-feature_2142_airnow_take2/bin
> MET_TEST_INPUT=/Volumes/d1/projects/MET/MET_unit_test/MET_test_input
> MET_TEST_OUTPUT=/Volumes/d1/projects/MET/MET_unit_test/MET_test_output
> 
> $MET_BIN/ascii2nc \
> $MET_TEST_INPUT/obs_data/airnow/daily_data_v2.dat \
> $MET_TEST_OUTPUT/ascii2nc/airnow/daily_data_v2_20220312.nc
> 
> python $MET_BIN/../scripts/utility/print_pointnc2ascii.py \
> $MET_TEST_OUTPUT/ascii2nc/airnow/daily_data_v2_20220312.nc > daily_data_v2_20220312.txt
> 
> # Compare input daily_data_v2.dat to output daily_data_v2_20220312.txt
> 
> $MET_BIN/ascii2nc \
> $MET_TEST_INPUT/obs_data/airnow/HourlyAQObs_2022031200.dat \
> $MET_TEST_OUTPUT/airnow/HourlyAQObs_20220312.nc
> 
> python $MET_BIN/../scripts/utility/print_pointnc2ascii.py \
> $MET_TEST_OUTPUT/ascii2nc/airnow/HourlyAQObs_20220312.nc > HourlyAQObs_20220312.txt
> 
> # Compare input HourlyAQObs_2022031200.dat to output HourlyAQObs_20220312.txt
> 
> $MET_BIN/ascii2nc \
> $MET_TEST_INPUT/obs_data/airnow/HourlyData_2022031200.dat \
> $MET_TEST_OUTPUT/ascii2nc/airnow/HourlyData_20220312.nc
> 
> python $MET_BIN/../scripts/utility/print_pointnc2ascii.py \
> $MET_TEST_OUTPUT/ascii2nc/airnow/HourlyData_20220312.nc > HourlyData_20220312.txt
> 
> # Compare input HourlyData_2022031200.dat to output HourlyData_20220312.txt
> ```

Sure, I'll try running your tests from seneca, so please do build there.

**Review by davidalbo — APPROVED** [review]
I approve this pull request. 

I reviewed the documentation and it did add meaningful and useful content.
I reviewed the code changes and they all made sense and were clear improvements, some cosmetic, and others adding functionality such as correctly handling units.
The testing done showed that the changes made did give the expected changes in results.

**Comment by JohnHalleyGotway** [comment]
Thanks @davidalbo for the review. Ho-Chun has no objection to us proceeding with these changes. So I'll merge this PR and proceed with the release.

**Comment by Ho-ChunHuang-NOAA** [comment]
Sorry John:

Please review the comments in feature #2142.   I need advice to enable the
ascii2nc airnow daily max/ave obs to point_stat.



Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Pull request merged**
