### PR TITLE
Feature #2633 seeps default p1 threshold

### LINKED ISSUE #2633: Set the SEEPS p1_thresold to >=0.1&&<=0.85
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
From Rachel North and Marion Mittermaier <marion.mittermaier@metoffice.gov.uk>

> 
> I support Marion’s suggestion of having the default seeps_p1_thresh value set to >=0.1&&<=0.85, rather than setting it to NA. This is recommended in the original Rodwell et al (2010) paper which defines the score.
> 
> Plus, as Marion says, for a novice user this makes the set-up easier.
> 

### Time Estimate ###
2 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

The default p1 threshold was set to >=0.1&&<=0.85 (was NA). The point SEEPS climo was filtered already, but not gridded SEEPS climo.

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

/d1/personal/hsoh/git/pull_request/MET_feature_2633_SEEPS_default_p1_threshold/bin/grid_stat /d1/personal/hsoh/data/MET-1943/gpm_2021120100_2021120200_trmmgrid.nc /d1/personal/hsoh/data/MET-1943/prods_op_gl-mn_2021120100_f024_A24_trmmgrid.nc /d1/personal/hsoh/data/config/GridStatConfig_SEEPS_fixed_p1_thresh -outdir out_grid_stat -v 7 > log_grid_stat_seeps.log

grep "filtered by threshold p1"  log_grid_stat_seeps.log | wc -w
1290704

/d1/personal/hsoh/git/pull_request/MET_feature_2633_SEEPS_default_p1_threshold/bin/point_stat /d1/projects/MET/MET_test_data/unit_test/model_data/grib1/nam/nam_2012040900_F012.grib /d1/personal/hsoh/MET/test_output/feature_1942_seeps/ascii2nc/trmm_2012040912_3hr.nc /d1/personal/hsoh/data/config/PointStatConfig_APCP_hardcoded_p1_thresh -outdir point_stat -v 7 > log_point_stat_seeps.log
grep "filtered by threshold p1"  log_point_stat_seeps.log | wc -w
0

Note: The SEEPS score for the point data are not filtered because the filtered values are saved at the point Climo.
Note: The SEEPS score for the point data are filtered by other criteria (density weighted averaging, density_radius = 0.75).

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[No]**

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

The setting at unit test, grid_stat_UK_SEEPS, "SEEPS_P1_THRESH" is changed to ge0.1&amp;&amp;le0.85 (was NA).
The grid_stat output will be changed because of filtering by p1 threshold. The out "grid_stat/grid_stat_SEEPS_000000L_20211202_000000V*" will be different.

Note:

- [x] Please complete this pull request review by **[7/31/2023]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by georgemccabe** [comment]
@hsoh-u , the destination branch for this pull request should be main_v11.1, not main_v11.0

**Comment by hsoh-u** [comment]
> @hsoh-u , the destination branch for this pull request should be main_v11.1, not main_v11.0

I branched this from develop. I will redo (branch from main_v11.1).

**Comment by hsoh-u** [comment]
> > @hsoh-u , the destination branch for this pull request should be main_v11.1, not main_v11.0
> 
> I branched this from develop. I will redo (branch from main_v11.1).

Thank you John! John already did it exept one file (internal/test_unit/xml/unit_grid_stat.xml).
The output of unit test will be the same.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of this PR. I updated the destination branch to be main_v11.1, added labels, and made some minor edits to the docs. I reviewed the changes and all are desired. Note that no seeps diffs were flagged in the output because while the default config files changed, the ones used in the unit tests did not.

The tests do produce an additional output file, as seen here:
ERROR: folder /data/output/met_test_truth missing 1 files
    plot_tc/plot_tc_TCMPR_data.tcst 

This is expected based on the update to the test.

**Pull request merged**
