### PR TITLE
Feature 1904 gen_ens_prod

### LINKED ISSUE #1904: Create the new Gen-Ens-Prod tool for ensemble product generation.
## Describe the New Feature ##
Create a new tool for ensemble product generation named Gen-Ens-Prod. This tool requires a configuration file and should contain the ensemble product generation currently performed for the fields in the "ens" dictionary of Ensemble-Stat. Consider renaming the "ens" dictionary to "data" to be consistent with the conventions of the Grid-Diag tool.

This tool does not process observations, but must support climatology mean and standard deviation data to support the use of climatological distribution percentile thresholds (e.g. >CDP75).

### Acceptance Testing ###
Ensure that other MET tools can read the NetCDF output created by this tool.

### Time Estimate ###
2 weeks.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
Sub-issues will likely be required. Not sure what they are yet.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split 2793541, 2700041, 2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway
- [x] Select **scientist(s)** or **no scientist** required: @j-opatz 
Can also solicit feedback from @mpm-meto, @jwolff-ncar, and @michelleharrold.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] dtcenter/METplus#1180
- [x] No downstream impacts on METdatadb, METplotpy, METcalcpy, METviewer, or METexpress.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Pull Request Testing ##

This PR adds a new gen_ens_prod tool. It processes the "ens" dictionary that is also currently processed by the Ensemble-Stat tool. However gen_ens_prod add support for climo_mean/stdev to define climatological percentile thresholds. Note that this PR is for an initial version of the tool. Additional enhancements will be made via other issues/PR's.

- [x] Describe testing already performed for these changes:</br>
Manually tested. Added call to gen_ens_prod in "make test" and also added that call to unit_met_test_scripts.xml. Also added unit_gen_ens_prod.xml to run it with climo_mean/stdev both with and without the -ctrl command line option.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

@georgemccabe, please review the usage statement, docs, and config file options to understand the functionality of this tool. We need to create a METplus wrapper for it.

@j-opatz, please review in more depth:
- Inspect the usage statement, review the config file options, see the output of running "make test", and the output of running "unit_gen_ens_prod.xml". Confirm that the handling of the "-ctrl" member is correct. Its included in the mean and probabilities but excluded from the standard deviation. Please do additional testing to try to break it. Confirm that it can re-create the CPC tercile probability values. Please consider other functionality that should be included in this initial version. The "-out" option requires that the user choose an output file name (like gen_vx_mask does) instead of automatically picking one for them.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
Added a new chapter that can be reviewed in [Read-The-Docs](https://met.readthedocs.io/en/feature_1904_gen_ens_prod/Users_Guide/gen-ens-prod.html).

- [x] Do these changes include sufficient testing updates? **[Yes]**
See above. Adds call in make test, unit_met_test_scripts.xml, and unit_gen_ens_prod.xml.

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
Adds 3 new gen_ens_prod output files:
```
    gen_ens_prod/gen_ens_prod_NO_CTRL_20120410_120000V.nc 
    gen_ens_prod/gen_ens_prod_WITH_CTRL_20120410_120000V.nc 
    met_test_scripts/gen_ens_prod/gen_ens_prod_20100101_120000V_ens.nc 
```
- [x] Please complete this pull request review by **[Friday 10/1/21]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by georgemccabe — APPROVED** [review]
The changes look good to me. It looks like the new wrapper will be able to borrow existing components from other wrappers to implement all of the functionality. The wrapper will support the following functionality:

* Obtain a list of input files, write a file list file, and pass to -ens argument
* Set environment variables to override values in MET config file (all dictionaries and variables in the new config file are supported in other wrappers)
* Pass wrapped config file as -config argument
* Build output file path from template/dir and pass to -out argument
* Set optional -ctrl path based on template/dir (GEN_ENS_PROD_CTRL_[TEMPLATE/DIR] or GEN_ENS_PROD_CONTROL_[TEMPLATE/DIR])

While I approve these changes, the science review should be completed before merging this PR.

**Review by j-opatz — COMMENTED** [review]
Confirmed that the output from the "make test" matched expectations, and reviewed documentation for accuracy and completeness. Also was able to successfully run CPC's NMME data through the new tool, which was previously accomplished in EnsembleStat. Comparisons to the output netCDF files show an exact match for the probability fields.
However, I don't know if the -ctrl option is working as expected. During testing, I ran two instances: one where gen-ens-prod had no control members, but 0-23 ensemble members included (24 total members), and the second where 1 ensemble member was excluded from the list (so 23 total members), but included the missing member as the control member. If this method was functioning correctly, then the ensemble_flag "mean" field should be identical between the two runs, and the "stdev" field should differ.
However, both fields differed from each other. Everything else on the tool seemed to function correctly.

**Comment by JohnHalleyGotway** [comment]
@j-opatz you're right. Thanks for catching this. There was an error in the logic for tracking the counts. I just committed a [fix for it](https://github.com/dtcenter/MET/commit/2aa7b5ad0a402f626655beb184edd083120118c3).

I also updated the version on kiowa and recompiled:
/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1904/MET-feature_1904_gen_ens_prod/met/bin/gen_ens_prod

Please rerun your test. Note, I did already confirm the problem/fix in my own testing.

FYI, at 4:00pm on 10/1/21, I restarted the full regression test vs develop after merging recent enhancements from develop into this feature branch. That required some manual conflict resolution:
kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1904

**Review by j-opatz — APPROVED** [review]
Reran the test for -ctrl option and confirmed that the output was as expected. With this update, I approve the PR merge

**Pull request merged**
