### PR TITLE
Bugfix 1976 main_v10.0 cdist

### LINKED ISSUE #1976: Fix MTD to compute the CDIST_TRAVELLED value correctly.
## Describe the Problem ##
In the calculation of cdist_travelled, x_old and y_old are set in the first loop iteration as the values of  xbar_2d and ybar_2d.  However, these values don't change in successive iterations of the loop.  This results in the distance being calculated using the starting centroid lat/lon rather than the centroid lat/lon of the previous time step, giving a cdist_travelled that is too large.

### Expected Behavior ###
x_old and y_old should use the values of xbar_2d and ybar_2d from the previous loop iteration.

### Environment ###
Describe your runtime environment:
1. Machine: Linux Workstation (aerial)
2. OS: Debian GNU/Linux 9.13 (stretch)
3. Lines 1319 - 1336, https://github.com/dtcenter/MET/blob/main_v10.0/met/src/tools/other/mode_time_domain/3d_att.cc

### To Reproduce ###
1. Run mtd (mtd -single mtd_file_list_test.txt -config MTDConfig_SKM_python_ALP3i_MOHC_HadREM3_rcp85_prltTH05_rsmoo8_tsmoo1_minvol1000_oooo)
2. Object F001 has a computed cdist_travelled of 354.691
3. Compute the great circle distance between successive centroid lat/lons, using mtd_ALP-3i_MOHC_HadREM3_rcp85_prltTH05_rsmoo8_tsmoo1_minvol1000_oooo__20960314_000000V_2d.txt .  The value computed externally is approximately 252 (using a constant earth radius of 6371)

Post relevant sample data following these instructions:*
The sample data is on seneca in /d1/projects/METplus/discussions/1249

### Relevant Deadlines ###
MET 10.1.0-beta5

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required: Tina to review

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [x] Fix the bug and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[Yes]**</br>
If **yes**, please describe:</br>
Modifies the contents of the CDIST_TRAVELLED column number 36 of the [3D Single Attribute Columns](https://met.readthedocs.io/en/latest/Users_Guide/mode-td.html#id10) from MTD.

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Ran unit_mtd.xml before/after the change.
BEFORE:
```
egrep "CDIST|F004" MET_test_output/mtd/mtd_SINGLE_20100517_010000V_3d_single_simple.txt | awk '{print $23, $36}'
OBJECT_ID CDIST_TRAVELLED
F004 417.821
```
AFTER:
```
egrep "CDIST|F004" MET_test_output/mtd/mtd_SINGLE_20100517_010000V_3d_single_simple.txt | awk '{print $23, $36}'
OBJECT_ID CDIST_TRAVELLED
F004 147.694
```
Here's the lat/lon centroid locations:
```
egrep "VERSION|F004" MET_test_output/mtd/mtd_SINGLE_20100517_010000V_2d.txt | awk '{print $23, $25, $29, $30}'
OBJECT_ID TIME_INDEX CENTROID_LAT CENTROID_LON
F004 0 30.86 -97.45
F004 1 30.90 -97.47 # 5 km
F004 2 30.86 -97.32 # 15 km
F004 3 30.87 -97.30 # 2 km
F004 4 30.80 -96.97 # 32 km
F004 5 30.52 -96.61 # 46 km
F004 6 30.42 -96.30 # 32 km
F004 7 30.48 -96.16 # 15 km
```
Using [NHC's distance calculator](https://www.nhc.noaa.gov/gccalc.shtml) to double-check.
Total = 147km... which matches the new output of 147.694 rather than the old output of 417.821.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
No additional testing needed. Please review the code changes to confirm the logic.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
None needed.

- [x] Do these changes include sufficient testing updates? **[Yes]**
None needed.

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
Will change the contents of existing MTD output columns.

- [x] Please complete this pull request review by **[Monday 11/22/21]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by CPKalb** [comment]
Is there a version of this already compiled somewhere that I could test?  It looks like it's doing what it should now.

**Comment by JohnHalleyGotway** [comment]
@CPKalb I just kicked off a regression test in kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta5/bugfix_1976 to compare the bugfix_1976_develop_cdist branch to develop.

At about 9:00am, you can test the MTD executable in:
/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta5/bugfix_1976/MET-bugfix_1976_develop_cdist/met/bin/mtd

This is actually the bugfix for the develop branch, but the fix is the same for develop as it is for main_v10.0.

Thanks,
John

**Comment by CPKalb** [comment]
Great, I'm testing it now.

**Review by CPKalb — APPROVED** [review]
I ran mtd, and the new cdist_travelled works as expected!

**Review by CPKalb — APPROVED** [review]
I ran mtd, and the new cdist_travelled works as expected!

**Pull request merged**
