### PR TITLE
Feature 1673 gbeta

### LINKED ISSUE #1673: Add G and G-Beta to the DMAP line type from Grid-Stat.
## Describe the Enhancement ##
On 2/18/21, Eric Gilleland presented the G and G-Beta methods. Since they are derived from the Mean-Error-Distance, which is already included in the DMAP line type, they are easily added to that line type.

Here's a description of the methods provided in the SpatialVx package in R:
https://www.rdocumentation.org/packages/SpatialVx/versions/0.7-1/topics/Gbeta

Implementation considerations:
- Should beta be made configurable via the Grid-Stat config file?
- Work with Eric to confirm the proper way of aggregating scores from multiple runs together, and enhance the Stat-Analysis tool to do so.
- Add documentation and references about this method to the MET User's Guide. List equations in Appendix C.

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required: Eric G

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] Define a METdatadb issue to handle the new DMAP columns.
dtcenter/METdatadb#62
- [x] Define a METviewer issue to plot the new DMAP columns:
dtcenter/METviewer#324
- [x] Define a METplus issue to make the setting of the beta_value option configurable:
dtcenter/METplus#1089

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Pull Request Testing ##

@ericgilleland please do a final review of documentation updates and confirm the decisions to only report GBETA for VX_MASK = FULL and mask out bad data back/forth between the fcst/obs files.

@georgemccabe please review the code/config file changes and regression test output. Just want to bring you into the loop on these changes.

@sethlinden please take a look at the changes... just looping you into the PR review process.

- [x] Describe testing already performed for these changes:</br>

- Tested manually to compare to output from the SpatialVx R package. While the computed distance maps values differ between MET and SpatialVx, I confirmed that the G and GBETA values are being computed correctly.
- Ran unit_grid_stat.xml and unit_met_test_scripts.xml to confirm that it all runs without error.
- Since GBETA is only reported when VX_MASK = FULL, I updated the Grid-Stat config file so "make test" produces a non-NA GBETA output value.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- Review the documentation updates to appendixC.rst and grid-stat.rst.
- Review the code changes.
- Review the diffs in the regression test I ran for this PR in kiowa: /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1673

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
- Lots of them! Please review these sections:
  - https://met.readthedocs.io/en/feature_1673_gbeta/Users_Guide/grid-stat.html#distance-maps
  - https://met.readthedocs.io/en/feature_1673_gbeta/Users_Guide/grid-stat.html#beta-and-g-beta
  - https://met.readthedocs.io/en/feature_1673_gbeta/Users_Guide/appendixC.html#g-and-g-beta

- [x] Do these changes include sufficient testing updates? **[Yes]**

- Only testing change was adding poly = "FULL" to the Grid-Stat config file called by "make test". But yes, I do think that's sufficient.

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

This PR will change the output from the Nightly Build!
- It adds 3 new columns of output to the existing DMAP line type (G, GBETA, BETA_VALUE) 
- Adds output for VX_MASK = FULL for a run of Grid-Stat.
- It also changes the existing distance map output statistics. Prior to computing distance maps, we now mask out missing data back/forth between the fcst/obs fields. That makes the comparison more fair, but changes existing output.

- [x] Please complete this pull request review by **[8/10/21]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by ericgilleland** [comment]
Hi John,

Sorry, I don't think I can help with this pull request as I have no idea
what I'm looking at.

Eric

**Comment by JohnHalleyGotway** [comment]
Eric, here's what you'd do...
1. Review the updated docs at these links.
https://met.readthedocs.io/en/feature_1673_gbeta/Users_Guide/grid-stat.html#distance-maps
https://met.readthedocs.io/en/feature_1673_gbeta/Users_Guide/grid-stat.html#beta-and-g-beta
https://met.readthedocs.io/en/feature_1673_gbeta/Users_Guide/appendixC.html#g-and-g-beta
2. Think about the decision to only report GBETA for VX_MASK = FULL and mask out bad data back/forth between the fcst/obs files.

If everything looks good to you, then...
1. Go to https://github.com/dtcenter/MET/pull/1857
2. Click on the tab that says "Files Changed (45)"
3. On the right side, click the green button that says "Review Changes" or "Add Your Review" (you should see one of those).
4. Select the "Approve" radio button.
5. Write whatever you'd like in the "Leave a comment" box, like "I approve of these changes for these reasons...".
6. Click the green "Submit Review" button, and you're done.

**Review by ericgilleland — APPROVED** [review]
I approve of the changes.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe the regression test completed on kiowa. All tests ran without error but 17 output files were flagged with differences:
```
cd /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1673
egrep -i "ERROR:|file1:" test_regression.log | egrep -B 1 ERROR: | grep file1
```
Here are the modified files:
```
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_cnt.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_ctc.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_cts.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_dmap.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_eclv.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_fho.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_grad.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_nbrcnt.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_nbrctc.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_nbrcts.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_pairs.nc
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_sl1l2.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V.stat
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_vcnt.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_vl1l2.txt
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/stat_analysis/job_summary_ME.stat
file1: MET-feature_1673_gbeta/test_output/met_test_scripts/stat_analysis/stat_analysis.out
```
As expected, the differences are confined to Grid-Stat output and Stat-Analysis output from jobs which process that Grid-Stat output.

**Comment by sethlinden** [comment]
Hi John, I'm just getting back to this. What specifically should I review for this pull request?

**Comment by sethlinden** [comment]
I'm looking at the code changes now.

**Review by georgemccabe — APPROVED** [review]
The code changes look good to me. It appears to add new line types for grid_stat and stat_analysis output (G GBETA and BETA_VALUE). John organized a summary of the differences in the regression tests and the files that have changes align with the expected differences due to these changes. I approve.

**Review by sethlinden — APPROVED** [review]
I looked over the code changes. Everything looks good to me as far as I can tell.

**Pull request merged**
