### PR TITLE
Feature 1442 file_list

### LINKED ISSUE #1442: Enhance tc_gen to support file lists for the -genesis and -track command line options.
## Describe the Enhancement ##
Enhance tc_gen to support file lists for the -genesis and -track command line options.

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway with George McCabe to review.
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [X] Push local changes to GitHub.
- [X] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [X] Iterate until the reviewer(s) accept and merge your changes.
- [X] Delete your fork or branch.
- [X] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**

### CODE REVIEW

**Comment by georgemccabe** [comment]
Is there a version of this app available on one of the NCAR machines that I could use to ensure the changes work with METplus?

**Comment by JohnHalleyGotway** [comment]
Compiling now in eyewall:/d1/johnhg/MET/MET_development/MET-feature_1442_file_list/met/bin/tc_gen
Please give it 10 minutes or so.

**Comment by georgemccabe** [comment]
I tested the METplus wrapper with the changes from this PR and it ran successfully. However, there was an odd error when I tried to run the old method of building the command (a -genesis/-track item for each input found). John is investigating the issue. Once that is resolved, this can be approved.

**Comment by JohnHalleyGotway** [comment]
I tested this potential issue locally but was not able to replicate the problem George describes. I passed the tool 77 instances of the "-genesis" command line option, one for each input file, and tc_gen processed those command line args the same as using "-genesis" once with 77 arguments.
My next step in debugging is running George's exact command on eyewall.

**Comment by JohnHalleyGotway** [comment]
Running unit_tc_gen.xml on eyewall yields the exact same runtime error that George was getting:
```
terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  basic_filebuf::underflow error reading the file: iostream error
Aborted
```
So the underlying problem is the eyewall build environment and not the code changes themselves. Since I tested those on my local machine and confirmed they worked, I'll proceed with merging this into the develop branch. At the same time, I'll continue debugging the eyewall environment.

**Pull request merged**
