### PR TITLE
Feature 2022 anom corr to vcnt

### LINKED ISSUE #2022: Add Anomaly Correlation Coefficient to VCNT Line Type
## Describe the Enhancement ##
In the CNT line type, Anomaly Correlation Coefficient is part of the output from the line type. It would be good to add this to the VCNT line type, so that Anomaly Correlation Coefficient can be calculated for Vector Wind. See the bottom of slide 11 for the equation at https://www.emc.ncep.noaa.gov/users/verification/global/gfs/doc/RMSE_decomposition.pdf. Additionally, it can be computed from the VAL1L2 line type by the equation 

A=sum[(uf-uc)*(uo-uc)+(vf-vc)*(vo-vc)]
B=sum[(uf-uc)**2+(vf-vc)**2]
C=sum[(uo-uc)**2+(vo-vc)**2]
ACC=A/sqrt(B*C)

uf = u wind forecast
uo = u wind observation
uc = u wind climatology
vf = v wind forecast
vo = v wind observation
vc = v wind climatology

or in terms from the VAL1L2 line type...

ACC = (UVFOABAR)/(sqrt(UVFFABAR*UVOOABAR) 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2793541, 2702691

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by sethlinden**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes or No]**</br>

No

If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[Yes or No]**</br>

YES

If **yes**, please describe:</br>

This change modifies the output of the VAL1L2 line type by adding the following columns:

FA_SPEED_BAR
OA_SPEED_BAR

This change modifies the output of the VCNT line type by adding the following columns:
ANOM_CORR
ANOM_CORR_NCL
ANOM_CORR_NCU 
ANOM_CORR_BCL 
ANOM_CORR_BCU 
ANOM_CORR_UNCNTR 
ANOM_CORR_UNCNTR_BCL 
ANOM_CORR_UNCNTR_BCU

Note BCL and BCU values are missing (not calculated), set to NA in the output

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Ran Testing workflow. All unit tests passed. Then checked the differences by downloading the diff.zip file from the "Check the Differences" section.

I also ran some point_stat command lines by hand to check that missing ANOM_CORR values are expected (missing U/V data in the climo file).

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run: perl/unit.pl xml/unit_climatology_1.5deg.xml. A new test was added to run stat_analysis and aggregate line-type VAL1L2 to output-line-type: VCNT. You should see the new columns in:

../MET/test_output/climatology_1.5deg/stat_analysis_WMO_1.5DEG_VAL1L2_to_VCNT_out.stat

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

Yes. Documentation was updated for the new VCNT output columns

- [x] Do these changes include sufficient testing updates? **[Yes or No]**

Yes. 

A new test was added to xml/unit_climatology_1.5deg.xml to run stat_analysis and aggregate line-type VAL1L2 to output-line-type: VCNT. You should see the new columns in:

../MET/test_output/climatology_1.5deg/stat_analysis_WMO_1.5DEG_VAL1L2_to_VCNT_out.stat

- [x] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

Yes, new columns were added to the VAL1L2 line-type and to the VCNT line type. Many output files will have these new columns:

For VAL1L2, new columns are: FA_SPEED_BAR, OA_SPEED_BAR
For VCNT, new columns are: ANOM_CORR ANOM_CORR_NCL ANOM_CORR_NCU ANOM_CORR_BCL ANOM_CORR_BCU ANOM_CORR_UNCNTR ANOM_CORR_UNCNTR_BCL ANOM_CORR_UNCNTR_BCU

- [x] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
@sethlinden I've lost track on where we stand with this PR. Is it all ready to be merged? I'll merge the latest from the develop branch into this feature branch and let the GHA tests run one more time.

**Comment by sethlinden** [comment]
@JohnHalleyGotway barring any major issues the PR is ready to be merged. I put in all the testing details that we had gone over (I did some more testing as well). Let me know if we still need to make changes to the code in relation to this PR.

**Review by JohnHalleyGotway — APPROVED** [review]
OK, I approve of this PR. The only thing that was tripping me up was the compilation failure from earlier runs. I suspect we needed to sync up with develop to get past that, which I did sometime last week I think. But manually re-running the failed PR jobs, the compilation succeeded.

Go ahead and merge this. We'll need related issues for METdatadb/viewer to handle the schema changes. I can add those.

**Comment by sethlinden** [comment]
@JohnHalleyGotway I just squashed and merged this pull request. I also closed the original issue as well. Thanks for the help with this, I greatly appreciate it!

**Pull request merged**
