### PR TITLE
bugfix 1414 develop_gaussian

### PR DESCRIPTION
**Pull request by hsoh-u**
…n value. Added more log message

### CODE REVIEW

**Review by JohnHalleyGotway — COMMENTED** [review]
Howard, I think we have an issue here. Dividing by the sum of the weights was added to solve a different problem. When we apply a gaussian smoother to the data near the edge of the grid, let's say that 1/2 of the points in the interpolation area are on the grid and 1/2 are off the the grid. When we don't divide by the sum of the weights, the smoothed values along the edge of the grid falls off rapidly. Here's the commit for that change:

Author: John Halley-Gotway <johnhg@ucar.edu>
Date:   Wed Dec 18 14:41:59 2019 -0700
    Refine gaussian smoother logic to use the vld_thresh and also renormalize the weights based on the grid points actually used.
commit bc1bdad031deb580b4d25ca231154f3a97534f63

**Comment by hsoh-u** [comment]
Yes, the same issues even though they are not at the edge.
The main idea with Gaussian smoothing is more weight near the center and less weight far away to center.

Example 1: all values are the same but one missing value, for example 280, for 11 by 11 neighbors.
Case 1: one missing value where the weight is 0.3 (close to center)
Case 2: one missing value where the weight is 0.04 (far away from the center)

Example 2: all missing values except one, for example 280, for 11 by 11 neighbors.
Case 1: one valid value where the weight is 0.3 (close to center)
Case 2: one valid value where the weight is 0.04 (far away from the center)

The current implementation produces the same Gaussian value for all cases:
- Example 1:  (280 * 0.7 / 0.7 VS. 280 * 0.96 / 0.96)
- Example 2:  (280 * 0.3 / 0.3 VS. 280 * 0.04 / 0.04)

This extreme case (Example 2) ended up expanding the same value to Gaussian matrix (which is 11 by 11 matrix, but excludes the cells which distance is more than 5 from the center, where MAX_R=5)

If this is accetable, no need to merge.

**Comment by JohnHalleyGotway** [comment]
Howard,

Yes, I do think this is correct. We generally want to ignore missing data
values rather than having them contribute the final result. When not
dividing by the sum of the weights, we had edge effects that caused our
gaussian implementation to not match Burkley's results.

But does this logic mess up the functionality of the point2grid tool in any
way?

John

**Comment by hsoh-u** [comment]
No it doses not mess up the Gaussian filtering for point2grid.
We can explain a weird shape with sparse point observation after Gaussian smoothing, for example:
- missing values because they are filtered by vld_thresh
- expanding the same value depending on the adjusted vld_thresh.

**Review by JohnHalleyGotway — COMMENTED** [review]
As discussed in the MET development meeting on 7/21/20, we do not want this change. Dividing by the sum of the weights was added to get MET's practically perfect results to correctly match Burkely's results.

**Pull request closed without merging**
