### PR TITLE
Feature 1319 no pickle

### LINKED ISSUE #1319: For python embedding, replace temporary pickle files with temporary NetCDF or ASCII files.
## Describe the Enhancement ##
When testing python embedding for tri-polar grids, Lindsay Blank ran into a python version problem when running on eyewall:  
```
AttributeError: cannot set attribute '_accessors' on a 'DataArray' object. Use __setitem__ styleassignment (e.g., `ds['name'] = ...`) instead of assigning variables.
```

Some Googling reveals this is caused by writing a pickle file with one version of Xarray and reading it with another (https://github.com/pydata/xarray/issues/3696).  This version-itis undermines the whole pickle file approach in the first place.

To replicate, run the following on eyewall:
```
conda activate /home/met_test/.conda/envs/metplus_envcd /d1/lblank/noaa_tripolar_testing/tripolar
setenv MET_PYTHON_EXE /home/met_test/.conda/envs/metplus_env/bin/python3
/usr/local/met-9.0/bin/plot_data_plane PYTHON_XARRAY rtofs_ice_area_test.ps 'name="read_tripolar_grid.py /d1/lblank/noaa_tripolar_testing/data/20200127/rtofs_glo_2ds_n048_daily_diag.nc north 20200127 ice_coverage ";'
```

In this example, 
(1) /home/met_test/.conda/envs/metplus_env/bin/python3 writes the pickle file using Xarray version 0.13.0
  > /home/met_test/.conda/envs/metplus_env/bin/python3
  > import xarray as xr
  > xr.show_versions()

(2) /usr/local/met-python3/bin/python3 reads the pickle file using Xarray version 0.15.0.
  > /usr/local/met-python3/bin/python3
  > import xarray as xr
  > xr.show_versions()

This task is to rework the logic employed when the MET_PYTHON_EXE environment variable is set.
(1) Replace met/data/wrappers/write_pickle_dataplane.py with met/data/wrappers/write_netcdf_dataplane.py.  Rather than writing the python data to a pickle file, write it to a gridded NetCDF data file that MET can read.
(2) Replace met/data/wrappers/read_pickle_dataplane.py entirely.  Update the python embedding logic... instead of executing the read_pickle_dataplane.py script, read the temporary NetCDF data file directly.
(3) Replace met/data/wrappers/write_pickle_point.py with met/data/wrappers/write_ascii_point.py.  Rather than writing the python data to a pickle file, write it to the 11-column MET ASCII format and update the ascii2nc tool to read data from that temporary file.
(4) Replace met/data/wrappers/write_pickle_mpr.py with met/data/wrappers/write_ascii_mpr.py.  Rather than writing the python data to a pickle file, write it to the ASCII MPR data format and update the stat_analysis tool to read data from that temporary file.

The trick is to make everything work well both with MET_PYTHON_EXE set and with it unset.

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
2799991

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts to other METplus repos.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by dwfncar**
## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
Check sys.path.insert to update system path with user's script dir.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation and testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [ ] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by JohnHalleyGotway — COMMENTED** [review]
This PR consists of a change to a single line of code in write_tmp_dataplane.py.
I don't see how this can address the features described in MET #1319.
If this needs to be merged now for some reason, please update the PR template with an explanation.

**Comment by dwfncar** [comment]
Attached file of feature_1319_no_pickle diffs relative to develop branch.
[no_pickle_diffs.txt](https://github.com/dtcenter/MET/files/6229830/no_pickle_diffs.txt)

**Comment by JohnHalleyGotway** [comment]
@davidfillmore I assume I should just run the unit_python.xml tests to ensure that they run well and produce the same output before/after these changes.

Here is the first PR for this work: https://github.com/dtcenter/MET/pull/1699
But that broke the build and those changes were reverted by: https://github.com/dtcenter/MET/pull/1717

So I'll also need to double-check that the problem introduced by #1699 has been fixed by this PR #1720.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
@davidfillmore I am very confused. I see the diff files you attached to this PR, but I don't actually see these changes reflected in the branch. For example, look at this Makefile.am from your feature branch:https://github.com/dtcenter/MET/blob/feature_1319_no_pickle/met/data/wrappers/Makefile.am

It's supposed to HAVE read_tmp_dataplane.py and write_tmp_dataplane.py and NOT HAVE read_pickle_dataplane.py and write_pickle_dataplane.py. But the opposite it true.

I do not think that approving this PR will actually merge the changes you intend. If you have a local copy of the code that fixes this issue, can you please just send me a tarball of that? And then I'll figure out how to merge it into GitHub.

**Review by JohnHalleyGotway — APPROVED** [review]
I did some work on the feature_1319_no_pickle branch and now approve of this PR.
I incorporated the changes that David sent to me. There was some confusion in git caused by reverting the original PR. But now all the expected changes are present in this branch and active for this PR.

Running unit_python.xml revealed one additional problem to fix in write_tmp_dataplane.py script. After fixing that, all test in unit_python.xml run and produce the same output as the develop branch.

I did the testing for this work on kiowa in /d1/projects/MET/MET_pull_requests/met-10.0.0_beta5/feature_1319

**Pull request merged**
