### PR TITLE
Feature 1184 dryline

### LINKED ISSUE #1184: Add support for Multi-Variate MODE
A new MODE tool is to be created to perform arbitrary set operations
(union, intersection, difference, etc.) on objects generated by MODE.
The objects in general will be associated with different variables.
Object attributes (centroid, axis, etc.) will be computed for the resultant objects.
Matching and merging may be a later option.
This tool is to be tested on fields relevant for dryline identification
(gradient of temperature, gradient of specific humidity, etc.).
The output format of the new tool will be identical to that of MODE.

Account Key: 2700042 WPC

Related METplus issue: dtcenter/METplus#1516

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**</br>
If **yes**, please describe:</br>
This PR provides a new way for the MODE tool to be configured and run. While existing MODE config files should still work as-is, the METplus team should develop some new use cases to demonstrate this multi-variate MODE functionality.

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
This feature branch is very old. On 3/7/22, I merged the latest from the develop branch into this feature branch and had to manually resolve 2 files in conflict. I tested to make sure the merged branch compiles and that the newly added unit_mode_multivar.xml file runs. I am relying on the GHA automated testing for this PR to see if these changes break and existing tests.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
This PR adds/modifies a whopping 52 files. Recommend doing a very careful code review of these changes before approving.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

Documentation is missing and should be added to this this feature branch before approving this PR.

- [x] Do these changes include sufficient testing updates? **[No]**

The unit_mode_multivar.xml file runs a fake data case to demonstrate the boolean object logic. Ideally, a test using real data would be added either to the MET unit tests or as a METplus use case to demonstrate a more reasonable use of multi-variate MODE.

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

It adds new output files in the $MET_TEST_OUTPUT/mode_multivar directory, and that new output will be flagged as a difference. In any other MODE output files are modified, those differences must be fixed before this PR can be merged.

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
The compilation of this feature branch fails via GHA with this message:
```
token.h:23:8: error: 'constexpr' does not name a type
 static constexpr const char * const intersection_char   = "&&";
        ^
token.h:23:8: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
```

This code uses features from the C++ 11 standard which apparently require the use of a compilation option to enable. I'm very leery of changing how MET is compiled in the RC1 development cycle, as I'm sure @jprestop is too. I'll check to see if I can remove the use of 'constexpr' so as not to require the use of a new compilation option.

**Comment by CPKalb** [comment]
What's the best way to test this?

**Comment by JohnHalleyGotway** [comment]
I need to get the unit tests running via GHA first. It looks like unit_mode_multivar.xml fails via GHA. Runs fine locally, so I need to figure out why it's failing there.

@CPKalb I think it'd be worthwhile to...
1. Put together a more realistic example using real data using existing test data input. And I can add them into unit_mode_multivar.xml.
2. Update documentation along the way.

**Review by TaraJensen — APPROVED** [review]
Was able to replicate the test, as well as confirm that we get different super objects when only using:

multivar_logic = "#1 && #2 ";
multivar_logic = "#1 && #3";

**Pull request merged**
