### PR TITLE
Bugfix 1395 develop comp script

### LINKED ISSUE #1395: Enhance the MET compilation script and its documentation
Enhance the compilation script and its documentation.

## Describe the Enhancement ##
* DONE - Remove --enable-modis from configure when COMPILE_HDF = 0 and COMPILE_HDFEOS=0 (need to account for when using an existing build of HDF and HDFEOS and not compiling)
* DONE - Create defaults for default BUFRLIB_NAME and GRIB2CLIB_NAME
* DONE - Changes George suggested in Slack
** cp include/*.h ${LIB_DIR}/include/. : line 443 you could remove the . at the end. The copy fails if you already instealled HDFEOS and you try to rerun the script. The 2nd time the files weren't overwritten in $LIB_DIR/include.
** Line 667: You could change to: if [ "${SET_D64BIT}" == "TRUE" ]; then; There were no quotes around ${SET_D64BIT} so if that is unset accidentally, it would evaluate to "" and fail the if test. Without it, you get a unary operator error; That could be applied to other checks for environment variables that may not be set by the user
**CLARIFIED IN DOCUMENTATION UPDATES - in the example install_met_env.kiowa file, I suggest commenting out the 2nd section of variables and change the comment to say uncomment if you have already compiled these. I was being hasty and didn't read the comment, so it skipped all of those and failed.
* DONE - Add syntax to check if path exists (eliminating extra colons) when adding to, for example, LDFLAGS
**export PATH=/usr/local/anaconda3/bin${PATH:+:$PATH}
**export PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}${HOME}/git/ConfigMaster
* DONE - Add LIBPNG_LIB to LDFLAGS (and potentially other libs) (this fixed Logan's MRMS problem on WCOSS)
* DONE - Add option for --bindir call to MET
* DONE - Improve documentation for script based on changes above which will simplify a recalling of the script
* CLARIFIED IN DOCUMENTATION - Add comments for each var to the install_env_<machine>.conf files or just to the generic file
* DONE - "python --version" should really be "${MET_PYTHON}/bin/python --version"
* DONE - Add check for GNU version 10. If 10 or greater, have ‘-fallow-argument-mismatch' in BUFRLIB compilation.   If less than 10, have ‘-Wno-argument-mismatch'' in BUFRLIB compilation.  

### Time Estimate ###
*Estimate the amount of work required here.*
1 - 3 days of work.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split 2771021 AF and 2700042 WPC

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Julie Prestopnik)
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

I tested the script on seneca:/d1/personal/jpresto/MET/test_comp using GCC version 8.3.0

I tested the script in several ways:

- full installation with all external libraries (needed to upgrade version of Freetype in tar_files to 2.7.0)
- with all libraries already installed (pointing to locations in environment config file)
- with and without compilation of HDF, HDFEOS, FREETYPE, and CAIRO.

I tested the script on cheyenne:/glade/p/ral/jntp/MET/MET_cross_platform_testing/met-10.1.0-beta2/gcc/
using GCC version 10.1.0

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Feel free to run any additional tests you’d like (or not run any tests - I tried to be thorough and test everything).  Please review the changes to the script, the documentation within the script, and updates to the documentation on the webpage (MET Downloads) which is currently marked as "Needs Review":
https://dtcenter.org/node/817/latest

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **10/5/21 (before beta3 release if possible)**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
@JohnHalleyGotway I should mention that while this is a bugfix to fix the issue where it breaks when GNU versions lower than 10 are used I do not plan to do a branch off of main_v10.0 because folks will be grabbing the compile script from the website and not from the repo directly. Plus, the version of the compile script in main_v10.0 is the script I used to install version 10.0 on various machines, so I'd like to keep that as-is.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
@jprestop I browsed the changes to script and noticed some odd wrapping of lines. When I opened it in an editor on my Mac, I found lots of trailing whitespace on many lines. I ran the following commands to strip them out and then committed the result:
```
cat scripts/installation/compile_MET_all.sh | sed -r 's/ +$//g' > t
mv t scripts/installation/compile_MET_all.sh 
```
I see no need for change to the actual content of the script. But adding all those extra details to the top seems very helpful to users! However the formatting has more issues. Scrolling through the body, I see a mixture of tabs and spaces that result in inconsistent indentation... sometimes 2 spaces, sometimes 4, and sometimes with tabs. The MET code typically indents 3 spaces and in scripts like this I usually use 2 spaces. But just keeping it consistent throughout the file makes it easier to read.

I don't think it's worthwhile for me to actually out the script since you've already run it so many times in so many places. If you think that'd be helpful, I can, but I'll wait for you to tell me to do so.

Regarding the website (https://dtcenter.org/node/817/latest), two comments:
- Instead of listing many machines '(includes NCAR RAL machines and NCAR machine cheyenne, and NOAA machines theia, jet, and WCOSS)' could we be more generic, like '(includes widely used HPC's at NCAR and NOAA)'? For example, perhaps jet will be retired and 5 years later, we'll still have a reference to it on this page.
- I wish there were some way to remove version-specific instructions so we wouldn't need to update this page for each release. While "https://github.com/dtcenter/MET/releases/latest" does resolve to "v10.0.0" I don't think there's a way to get the "latest" tarfile. We could point them to the "latest" release page and tell them to click the button to download the tarfile. But having commands to copy/paste is pretty convenient. But whenever we made edits to websites, I'm always trying to minimize future maintenance because we usually don't do it very well!

I'm going to select the "request changes" option since I think getting the indentation consistent is worth doing.

**Comment by jprestop** [comment]
@JohnHalleyGotway Thanks for the review, for getting rid of the trailing whitespace, and letting me know the command that you used to do it.   There was definitely a mix of tabs and varying spaces!  I've been playing with my emacs options trying to fix that problem.  Hopefully, I'll get that resolved.  In any case, I fixed up this file appropriately, sticking with two spaces for consistency.  To ensure that I didn't mess up the actual indentation of if statements and whatnot, I did a manual check with the old version to ensure the indentation had remained the same and I also tested again with the installation of all libraries to ensure they all compiled well still.

I don't think there is any need for you to test the script.  I tried to be thorough in testing. 

Regarding:

> Instead of listing many machines '(includes NCAR RAL machines and NCAR machine cheyenne, and NOAA machines theia, jet, and WCOSS)' could we be more generic, like '(includes widely used HPC's at NCAR and NOAA)'? For example, perhaps jet will be retired and 5 years later, we'll still have a reference to it on this page.

Ha!  I found an old reference to "theia" on the page, so I changed that to "hera" and decided to go generic with "includes widely used HPC's at NCAR and NOAA" in the place you suggested.  So those changes have been made.

Regarding:

> I wish there were some way to remove version-specific instructions so we wouldn't need to update this page for each release. While "https://github.com/dtcenter/MET/releases/latest" does resolve to "v10.0.0" I don't think there's a way to get the "latest" tarfile. We could point them to the "latest" release page and tell them to click the button to download the tarfile. But having commands to copy/paste is pretty convenient. But whenever we made edits to websites, I'm always trying to minimize future maintenance because we usually don't do it very well!

I agree and wasn't sure about that one.  I went ahead and changed it from:

>Download the latest MET release (e.g. met-10.0.0.20210510.tar.gz) from the Download page into the tar_files directory:
>wget https://github.com/dtcenter/MET/releases/download/v10.0.0/met-10.0.0.20210510.tar.gz

To:

>  Download the latest MET release (e.g. met-10.0.0.tar.gz) from the Recommended download section above using a wget (or other) command and place it in the tar_files directory.

I know met-10.0.0.tar.gz is still listed, but it is only as an example.  Please let me know what you think of that change.  If it's good, I'll go ahead and publish it once this is merged.

**Comment by jprestop** [comment]
@JohnHalleyGotway 

I see I didn't modify my comment above before submitting.

I changed the reference that included hera from:
>includes NCAR RAL machines and NCAR machine cheyenne, and NOAA machines theia, jet, and WCOSS

to:
>includes NCAR RAL machines and widely used HPC's at NCAR and NOAA

to get rid of references to all specific machines.

**Review by JohnHalleyGotway — APPROVED** [review]
Thanks for fixing up the indentation. Looks good to me now. I approve.

**Pull request merged**
