### PR TITLE
Feature 2092 v10.1.0-rc1

### LINKED ISSUE #2092: Create the MET-10.1.0-rc1 release
## Describe the Task ##
This task is to create the MET 10.1.0-rc1 release.

During this process, remember to review and refine the instructions for MET in the METplus Release Guide:
https://metplus.readthedocs.io/en/develop/Release_Guide/met_development.html

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issue required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: No scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Will need related issues for beta3 releases for each component.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
No testing, just documentation updates.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please review the [MET-10.1.0 release notes](https://met.readthedocs.io/en/feature_2092_v10.1.0-rc1/Users_Guide/overview.html#met-version-10-1-0-release-notes-20220314). Note that these have already been collated for the official release, rather than listing rc1 separately.

I also rotated/updated the author list based on Tara's feedback.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
That's all it is ;)

- [x] Do these changes include sufficient testing updates? **[Yes]**
None needed.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[Thurs 3/10/22]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by TaraJensen — CHANGES_REQUESTED** [review]
I found one enhancement that needs to be included in the MODE listing:
Update the MODE AREA_RATIO output column to list the forecast area divided by the observation area ([#1643](http://github.com/dtcenter/MET/issues/1643)).

This is a nitpicky request and if it's too much effort, please feel free to not do it, but could the application code list be alphabetized by tool name?

**Comment by JohnHalleyGotway** [comment]
Tara, dtcenter/MET#1643 was already released in MET version 10.0.0 and it's already listed in those release notes:
Screen Shot 2022-03-10 at 2 02 25 PM
Not sure how it ended up in your list of 10.1.0 issues.

I can alphabetize the tools if that's what you prefer. The order I chose corresponds to the order of the tools in the [flowchart](https://met.readthedocs.io/en/feature_2092_v10.1.0-rc1/_images/overview-figure.png). Pre-processing, statistics, analysis.

If you prefer them alphabetical, I'll update them for MET version 10.1.0 and 10.0.0. I'll wait for you to confirm.

I do realize that I also need to updated the overview section for MET version 10.1.0 (new flowchart + gen_ens_prod description). I'll do that now.

**Comment by TaraJensen** [comment]
As for MODE issue - ok.  Not sure how it wound up in my list also.
As for order - Thanks for explaining your methodology but then Grid-Diag should be after Series Analysis and Stat-Analysis seems out of place and maybe after the TC tools because it's in a different "column".  I'm okay with just fixing the order a bit because it's less work.

**Comment by JohnHalleyGotway** [comment]
@TaraJensen OK, I'm re-requesting your review now.
- Please see the newly alphabetized-by-tool-name [release notes](https://met.readthedocs.io/en/feature_2092_v10.1.0-rc1/Users_Guide/overview.html#met-release-notes).
- Please review the newly updated [MET components](https://met.readthedocs.io/en/feature_2092_v10.1.0-rc1/Users_Guide/overview.html#met-components) overview section.
   - Mainly review the 2nd paragraph starting with ```The reformatting stage of MET consists```.

**Review by TaraJensen — APPROVED** [review]
Looks good.  Thanks for the changes.

**Pull request merged**
