### PR TITLE
Bugfix 2666 point2grid usage

### LINKED ISSUE #2666: Bugfix: Correct the usage statement for Point2Grid
*Replace italics below with details for this issue.*

## Describe the Problem ##
The input of point2grid is a MET point NetCDF, GOES data, and Point observation as NcCF, not a gridded data. The descrioption of "input_filename" should be updated.
```
bin/point2grid
DEBUG 1: Start point2grid by hsoh(9895) at 2023-08-23 15:48:52Z  cmd: bin/point2grid

*** Model Evaluation Tools (METV11.1.0) ***

Usage: point2grid
        input_filename
        to_grid
        output_filename
        ...
        where   "input_filename" is the gridded data file to be read (required).
```
User guide is correct.

The input_filename argument indicates the name of the input file to be processed. The input can be a MET NetCDF point observation file generated by other MET tools or a NetCDF AOD dataset from GOES16/17. Python embedding for point observations is also supported, as described in [:numref:`pyembed-point-obs-data`](https://github.com/dtcenter/MET/blob/main_v11.1/docs/Users_Guide/reformat_point.rst#id59).

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2792543 - NOAA Base

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as the next bugfix version
- [ ] Select **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Select **MET-X.Y.Z Development** project for development toward the next official release

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next bugfix version
Select: **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

The usage message of point2grid
```
where   "input_filename" is the gridded data file to be read (required).
==>
where   "input_filename" is the input NetCDF point observation file to be read (required).
```

Two additional changes for ReadTheDocs (happedn at this branch)

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Run point2grid and  check the description of input_filename
```
/d1/personal/hsoh/git/pull_request/MET_bugfix_2666_point2grid_usage/bin/point2grid
```

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[No]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[Oct. 06. 2023]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — APPROVED** [review]
I ran /d1/personal/hsoh/git/pull_request/MET_bugfix_2666_point2grid_usage/bin/point2grid and checked the usage statement and ensured all tests passed.  Please note that the one failure is unrelated to this PR.  Also included in this PR are some edits I made to fix the ReadTheDocs errors.  I approve this request.

**Comment by jprestop** [comment]
Hi @hsoh-u.  Unfortunately, I'm a little late in noticing that this is a bugfix.  Looking at the issue, I see that this bugfix was only applied to the develop branch.  However, I see that the issue #2666 only has the 12.0.0-beta2 Project assigned.  Should there be a corresponding bugfix for MET-11.1.0?  Or was it intended for this only to go into develop?  Thanks!

**Comment by hsoh-u** [comment]
I did not make a bugfix branch for MET-11.1.0 because this is a minor issue. I will make it for MET-11.1.0.

**Comment by jprestop** [comment]
Thanks @hsoh-u.  I went ahead and added "Coordinated METplus-5.1 Support" to the issue for clarity and as a reminder it would be done for MET-11.1.0.

**Pull request merged**
