### PR TITLE
Feature 2302 python embedding converting

### LINKED ISSUE #2302: Add a Python helper script/function to transform point_data objects to met_point_data objects for Python Embedding
## Describe the Enhancement ##
Write a new Python helper script to take a `point_data` object and transform it to a `met_point_data` object, to avoid the user having to use ASCII2NC with Python Embedding prior to calling another MET tool.

The workflow would look like this:
1) User Python script is executed that constructs a `point_data` object
2) User can import functions from this Python helper script to convert `point_data` to `met_point_data`
3) The user is returned a `met_point_data` object which can then be handed off directly to MET tools such as `point_stat`

This work is a stop-gap to provide users functionality faster than the work described in #2285  

### Time Estimate ###
TBD

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799992 NRL Aerosol Prof

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

The MET/scripts/python/read_ascii_point.py can be used instead of MET/scripts/python/read_met_point_obs.py for 11 column text input.

- modified the existing python scripts
- two data files: no changes for the content. Only file permission is updated (removed the executable permission)
- unit test:
  - "python_plot_point_obs_CONFIG_XXX" is the same as "plot_point_obs_CONFIG" at unit_plot_point_obs.xml except output directory. 
  - Renamed "python_plot_point_obs_CONFIG_XXX" to "python_plot_point_obs_with_point_data" and updated arguments

How to use: add following two lines
```
from met_point_obs import convert_point_data   # newly added

point_data = pd.read_csv(...).values.tolist()             # existing code by customer
met_point_data = convert_point_data(point_data)   # newly added
```

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

+ Added to unit test
+ Converted ascii2nc and pb2nc output at the nightly build output by using pntascci2nc.R and used them as input to plot_point_obs

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

+ Converted ascii2nc and pb2nc output at the nightly build output by using pntascci2nc.R and used them as input to plot_point_obs

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [ ] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

One new plot (precip24_2010010112.ps) is added.

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
@DanielAdriaansen this one is the same situation. We're both assigned, but I'd really like to get your input on these changes to keep you in the loop on python embedding functionality in MET.

In particular I don't see any changes to the User's Guide on this PR... and it sure seems like we'd need some to document the changes to the functionality.

**Comment by hsoh-u** [comment]
The associated issue corrected to this PR

**Comment by DanielAdriaansen** [comment]
This work adds a converter to transform a `point_data` object to `met_point_data`, if the user has `point_data` but wants to use a MET tool that requires `met_point_data`.

`read_ascii_point.py` has been modified such that both `point_data` and `met_point_data` exist when it is called, thus having both objects available for whatever tool is being used downstream of the Python embedding, if `read_ascii_point.py` is being used.

If a user has existing Python embedding with `point_data` but wants to use a tool that requires `met_point_data`, they will have to add the following lines to their Python embedding script:
```
from met_point_obs import convert_point_data
met_point_data = convert_point_data(point_data)
```

After #2285 is complete, the user won't have to do this. They can create `point_data` (which is far easier to create), and something within MET will sense that they have `point_data` and call `convert_point_data` for the user if the tool downstream of the Python embedding they are using requires `met_point_data`.

I will add some documentation updates soon, and then add my review.

**Comment by DanielAdriaansen** [comment]
For testing, I did the following:
1) ascii2nc with the proposed `read_ascii_point.py` using `/d1/projects/MET/MET_releases/MET/data/sample_obs/ascii/sample_ascii_obs.txt` on seneca, to create a "point NetCDF file":
```
/d1/projects/MET/MET_regression/develop/NB20221118/MET-develop/bin/ascii2nc -format python "scripts/python/read_ascii_point.py /d1/projects/MET/MET_releases/MET/data/sample_obs/ascii/sample_ascii_obs.txt" ascii2nc_python.nc
```

2) plot_point_obs with output from (1):
```
/d1/projects/MET/MET_regression/develop/NB20221118/MET-develop/bin/plot_point_obs ascii2nc_python.nc ascii2nc_python.ps
```

3) plot_point_obs with proposed `read_ascii_point.py` using Python embedding and `/d1/projects/MET/MET_releases/MET/data/sample_obs/ascii/sample_ascii_obs.txt` on seneca:
```
/d1/projects/MET/MET_regression/develop/NB20221118/MET-develop/bin/plot_point_obs "PYTHON_NUMPY=scripts/python/read_ascii_point.py /d1/projects/MET/MET_releases/MET/data/sample_obs/ascii/sample_ascii_obs.txt" new.ps
```

Since Test 3 uses plot_point_obs which requires the "MET NetCDF point observation format" as input -or- the `met_point_data` object via Python embedding, it should succeed now with Howard's changes here, when previously it would fail.

With Howard's changes, Test 3 succeeds now.

I am adding some documentation updates and then I will add my review.

**Comment by DanielAdriaansen** [comment]
NOTE:

I removed a section from the "Reformatting of Point Observations" that described Python Embedding with `ascii2nc`. I felt that it was more appropriate to have this in Appendix F:
https://github.com/dtcenter/MET/pull/2340/commits/af71f3bd4897e45ac4bb4102f2bacbef01aa40eb

**Review by DanielAdriaansen — APPROVED** [review]
I approve.

**Pull request merged**
