### PR TITLE
Feature 1903 sonarqube

### LINKED ISSUE #1909: Resolve PB2NC string truncation warning messages.
## Describe the Task ##
Pull requests for Issue #1855 introduced several hundred warning messages when running PB2NC. These are evident when running:
```
make test >& make_test.log
```
Here's the resulting [make.log](https://github.com/dtcenter/MET/files/7107358/make.log) file.
It contains 986 new warning messages:
```
grep WARNING make_test.log | grep get_variable_info | wc -l
     986
```
And here's what one looks like:
```
WARNING:   get_variable_info() truncated a string var_name from "SAID     | 001007 | SATELLITE IDENTIFIER (SATELLITE REPORTS ONLY)            |
WARNING: " to "SAID    "
```
This task is investigate this situation and get rid of that warning. I suspect that the vertical bar '|' should be interpreted as a field separator. Could you use strtok or string split instead so that this doesn't trigger a warning message?

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Please fix in the next development cycle, met-10.1.0-beta3.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Howard
- [x] Select **scientist(s)** or **no scientist** required: none required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Pull Request Testing ##

New files:
- str_wrappers.h & str_wrappers.cc (at vx_log) are separated from string_fxns.h/cc (vx_util) to reduce the dependency
- enum_to_string.h: extern statements at enum_to_string.cc were moved to the header file

Overall:
- m_strlen, m_strcpy and m_strncpy are re-implemented
- strlen, strcpy and strncpy is changed to m_strlen, m_strcpy and m_strncpy
- Some null pointer 0 is changed to NULL (it should be nullptr, but some old compiler does not support nullptr yet)

The assignment at the second or at the third conidtion for || or && logical could cause a side effect. SO separated the condition with assignments to avoid a potential side effects:
- my_config_scanner.cc
- concat_string.cc
- grib_classes.cc
- tc_stat_job.cc

File specific updates:
- code.cc: include statements are moved to top. Removed extern statements and included enum_to_string.h:
- is_dst.cc: added socnt to dst_info[] variable
- concat_string.cc : check if the pointer is valid before deleting it.
- color.cc: initialized r,g, and b variables
- table_lookup.cc: avoid unreachable code return above if statement returns something nor exit
- nccf_file.cc: cast unixtime (long long) to int
- python3_script.cc: renamed a local variable name module (a keyword) to py_module
- cgraph_main.cc, cgraph_main.h, & plot_mode_field.cc: renamed a function name import (a keyword) to import_image
- pair_data_ensemble.cc: initialize fcst
- track_info.cc: avoid a potential negative offset
- aeronet_handler.cc : removed unused variable offset (setting only but no use after setting a value
- madis2nc.cc: initialize the variable data
- pb2nc.cc: allows the truncation for some m_strncpy (the to_str must be different from the from_str)

- [x] Describe testing already performed for these changes:</br>

Just do the unit test and the same outputs are expected

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

unittest and compare the outputs

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[No]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
@hsoh-u have you quantified the number of security hotspots identified by SonarQube before/after these changes? If not, please do so. I think that'd be very useful to keep track of.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
@hsoh-u I tested by running a full regression test on kiowa and the unit tests for your feature branch failed. From kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/test_unit_feature_1903_sonarqube.log
```
TEST: gen_vx_mask_DATA_APCP_24        - FAIL -   0.191 sec
WARNING: 
WARNING: regex_apply()  truncated a string mat[i] from "A24" to "(nul)"
WARNING: 
WARNING: 
WARNING: regex_apply()  truncated a string mat[i] from "24" to "(nul)"
WARNING: 
ERROR  : 
ERROR  : timestring_to_sec(const char *) -> empty time string!
ERROR  : 

ERROR: /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/test/perl/unit.pl unit_gen_vx_mask.xml failed.

*** UNIT TESTS FAILED ***
```
Please fix.

**Comment by hsoh-u** [comment]
It's fixed (some m_strcpy are replaced with m_strncpy). Please do regression test.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
I re-ran the regression test vs develop on 9/13/2021 and it continues to fail as it did last time. See kiowa: d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/test_unit_feature_1903_sonarqube.log
```
TEST: gen_vx_mask_DATA_APCP_24        - FAIL -   0.119 sec
/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/met/share/met/../../bin/gen_vx_mask \
      /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/met/data/sample_fcst/2005080700/wrfprs_ruc13_24.tm00_G212 \
      /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/met/data/sample_fcst/2005080700/wrfprs_ruc13_24.tm00_G212 \
      /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/test_output/gen_vx_mask/DATA_APCP_24_mask.nc \
      -type data -mask_field 'name="APCP"; level="A24";' -thresh 'ge2.54' -v 2
DEBUG 1: Input Grid:		/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/met/data/sample_fcst/2005080700/wrfprs_ruc13_24.tm00_G212
DEBUG 1: Mask File:		/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/met/data/sample_fcst/2005080700/wrfprs_ruc13_24.tm00_G212
DEBUG 2: Parsed Input Grid:	Lambert Conformal (185 x 129)
WARNING: 
WARNING: regex_apply()  truncated a string mat[i] from "A24" to "(nul)"
WARNING: 
WARNING: 
WARNING: regex_apply()  truncated a string mat[i] from "24" to "(nul)"
WARNING: 
ERROR  : 
ERROR  : timestring_to_sec(const char *) -> empty time string!
ERROR  : 

ERROR: /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/test/perl/unit.pl unit_gen_vx_mask.xml failed.

*** UNIT TESTS FAILED ***

ERROR: Command returned with non-zero status (1): test/bin/unit_test.sh
```
Please make sure all the unit tests run without error before re-submitting.

**Comment by hsoh-u** [comment]
I modified m_strcpy to m_strncpy in order to use sizeof(to_str) instead of strlen(from_str). But I changed back to use strlen because the unit test for pull request was failed again. I doubt the pull request got the latest code from the feature branch. The instances of m_strcpy & m_strncpy don't match with mine. Here are the counts of m_strcpy & m_strncpy:
```
directory: /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903:

- m_strcpy: 48
- m_strncpy: 54

grep m_strcpy `find /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/met/src/ -type f -name "*cc"` | wc -l
48
grep m_strncpy `find /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903/MET-feature_1903_sonarqube/met/src/ -type f -name "*cc"` | wc -l
54

directory: /d1/personal/hsoh/git/pull_request/MET_feature_1903_sonarqube:
- m_strcpy: 36
- m_strncpy: 66

grep m_strcpy `find /d1/personal/hsoh/git/pull_request/MET_feature_1903_sonarqube/met/src/ -type f -name "*cc"` | wc -l
36
grep m_strncpy `find /d1/personal/hsoh/git/pull_request/MET_feature_1903_sonarqube/met/src/ -type f -name "*cc"` | wc -l
66
``` 
Please make sure the number of m_strcpy and m_strncpy after checking out feature_1903_sonarqube branch.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes. I ran a full regression test in kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta3/feature_1903 for feature_1903_sonarqube versus develop and no differences were flagged. I also ran "make test" and inspected the log messages carefully and found that no warning messages about truncated strings remain.

**Pull request merged**
