### PR TITLE
Feature 1453 create pdf user guide

### LINKED ISSUE #1453: Create and publish a PDF of the MET User's Guide via Read-The-Docs
## Describe the Task ##
As of met-9.1, the User's Guide is created via Sphinx and the resulting html output is published to:
https://ncar.github.io/MET/index.html

This task is to render the User's and Contributor's Guides as 2 separate PDF files which would useful for offline viewing. Some users, particularly in secure areas, do not have ready access to the internet for viewing docs on github.io.

George McCabe did some initial investigation but ran into issues rendering equations.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by ksearight**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>4

Builds on RTD with no warning file generated.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Here's a summary of the changes made:
1. replaced UTF-8 characters with ASCII
2. enabled PDF creation
3. added conditional directives to address differences in handling underscore chars in HTML vs. Latex/PDF
4. replace some problematic math syntax with alternatives or text
5. don't display Indices and tables section in PDF
6. replaced gif images with png (gif not supported in latex)

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[end of beta2]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** 
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
Note, I found the PDF of the User's Guide for this branch served up by ReadTheDocs here:
https://met.readthedocs.io/_/downloads/en/feature_1453_create_pdf_user_guide/pdf/

It is accessible via the "Downloads" tab from RTD for this branch:
https://met.readthedocs.io/en/feature_1453_create_pdf_user_guide/

**Comment by JohnHalleyGotway** [comment]
@ksearight these changes look great. I'm excited to a get a PDF in place! I do have one question... prior to submitting this PR, did you merge the latest changes FROM develop INTO your feature branch?

I want to make sure that recent changes to the develop branch do not cause the PDF creation to fail.

If not, please do so.

**Comment by ksearight** [comment]
Not yet, but will merge develop in to the feature branch next.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes.
Thanks for your work on this Keith! While I did not read all 400+ pages, I did scroll through the PDF and saw no glaring problems. In reviewing the 38 modified files, I noted:
- enabling and configuring the pdf output format
- many formatting changes for single quotes, double-quotes, and dashes
- many formatting changes for equations in the appendices

Since Keith is busy today. I'll go ahead and merge these changes and close the original issue. Please feel free to reopen if additional work is needed.

**Pull request merged**
