### PR TITLE
Feature main_v10.0 bugfix_checklist

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Pull Request Testing ##

No code changes here. Just updates to the bugfix and pull request templates. I'm using this PR to propose these changes and request review/feedback from Julie and Minna. Once we settle on changes, I'll push them to the other METplus repos... doing so in both the develop and the current default branch (e.g. main_v10.0 for MET) in each.

- [x] Describe testing already performed for these changes:</br>
Just updated wording.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Review template changes.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[NA]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[5/20/21]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [ ] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — APPROVED** [review]
I took my time going through the wording and looked at an example to follow along.  It took some time to process what you wrote and to make sure it all made sense, but I think it sounds great!  Thanks so much for your work on this. I think it will be really helpful in understanding what choices to make.  I approve this request.

**Review by bikegeek — APPROVED** [review]
These changes look good-provide more clarification than the original version.  I approve.

**Comment by JohnHalleyGotway** [comment]
@jprestop and @bikegeek thanks for reviewing these changes. I realized I should make similar tweaks to the other issue templates to keep the level info consistent. So I just pushed minor changes to the others.

**Comment by jprestop** [comment]
@JohnHalleyGotway Should we consider updating the other METplus component's templates as well?  If so, should we discuss at a meeting or via email with group leads?

**Comment by JohnHalleyGotway** [comment]
@jprestop my plan was to get review/approval from you guys, and then push these changes to all the repos... both the current default branch and the develop branch in each. I don't imagine people will have objections to these template tweaks. But I did want to get buy in and approval from a couple of folks first. Agreed that we should review the tweaks at a METplus All Hands meeting soon.

**Comment by jprestop** [comment]
@JohnHalleyGotway That sounds like a good plan.  Thanks! Unfortunately, I will be out of town for the first METplus all hands meeting.  :(

**Review by georgemccabe — APPROVED** [review]
The changes add more detailed instructions for setting the Project and Milestone information for each type of issue and pull request. These changes look good to me.

**Pull request merged**
