### PR TITLE
Bugfix 2638 nccf coordinate dimension main v11.1

### LINKED ISSUE #2638: Bugfix: Refine support for coordinate dimensions in CF-compliant NetCDF files
## Describe the Enhancement ##
This issue arose via GitHub discussion dtcenter/METplus#2273 from @robdarvell and is demonstrated by running the plot_data_plane tool. Use this file to demonstrate the issue:
[percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc.gz](https://github.com/dtcenter/MET/files/12253982/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc.gz)

The goal is to retrieve 2D fields from this variable:
`float visibility_in_air(percentile, projection_y_coordinate, projection_x_coordinate) ;`

Plotting the 0-th percentile index works as expected:
`plot_data_plane percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc plot.ps 'name="visibility_in_air"; level="(0,*,*)";'`
Screen Shot 2023-08-03 at 12 39 42 PM
Plotting the VALUE of the first percentile also works fine:
`plot_data_plane percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc plot.ps 'name="visibility_in_air"; level="(@5,*,*)";'`

However, plotting ANY OTHER index or percentile value produces a runtime error:
- `name="visibility_in_air"; level="(1,*,*)";'`
- `name="visibility_in_air"; level="(@10,*,*)";'`
- `name="visibility_in_air"; level="(6,*,*)";'`
- `name="visibility_in_air"; level="(@50,*,*)";'`

Here's the error:
```
ERROR  : 
ERROR  : MetNcCFDataFile::data_plane(VarInfo &, DataPlane &) -> the requested vertical value 50 for "visibility_in_air" variable does not exist (data size = 1).
ERROR  : 
```
I assumed that the changes for dtcenter/MET#1815 included in MET version 11.0.0 would enable this logic to work. In general, for an N-dimensional NetCDF variable, exactly 2 of those dimensions should define the X/Y dimensions. The remaining dimensions should be settable by specifying their index as an integer. Additionally, for coordinate variables (i.e. dimension and 1-d variable of the same name), MET should support the `@` syntax to specify the value for that dimension.

This issue is to refine the logic to support the processing of this data.

Please fix this in the main_v11.1 branch to be included in an 11.1.1 bugfix release. Please also fix this in the develop branch to be included in the 12.0.0 official release.

Recommend adding a unit test using the input file.

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

The variable with the standard name "height" and "air_pressure" is selected as the vertical level variable for NCCF. The sample NetCDF from the user has the "height" variable but it's not used as the vertical level. The vertical level will be from the variable's vertical dimension.
```
        float projection_y_coordinate(projection_y_coordinate) ;
                projection_y_coordinate:axis = "Y" ;
                projection_y_coordinate:standard_name = "projection_y_coordinate" ;
        float projection_x_coordinate(projection_x_coordinate) ;
                projection_x_coordinate:axis = "X" ;
                projection_x_coordinate:standard_name = "projection_x_coordinate" ;
        float percentile(percentile) ;
                percentile:units = "%" ;
                percentile:long_name = "percentile" ;
        float height (height);
                height:units = "m" ;
                height:standard_name = "height" ;
                height:positive = "up" ;
        float visibility_in_air(percentile, projection_y_coordinate, projection_x_coordinate) ;
                visibility_in_air:least_significant_digit = 0LL ;
                visibility_in_air:standard_name = "visibility_in_air" ;
                visibility_in_air:units = "m" ;
                visibility_in_air:grid_mapping = "lambert_azimuthal_equal_area" ;
                visibility_in_air:coordinates = "blend_time forecast_period forecast_reference_time height time" ;
```
MET recognizes projection_x_coordinate, projection_y_coordinate, and height by the standard_name and the attribute "axis". The "height" is excluded as a coordinate variables because it is not 1 dimension variable. And the variable "visibility_in_air" has the "percentile" dimension as Z. MET checks the vertical level from "percentile", not "height".

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
```
/d1/personal/hsoh/git/pull_request/MET_bugfix_2638_nccf_coordinate_dimension_main_v11.1/bin/plot_data_plane /d1/personal/hsoh/data/MET-2638/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc plot.ps 'name="visibility_in_air"; level="(1,*,*)";' -v 5
```
And tested following three:
```
'name="visibility_in_air"; level="(@10,*,*)";'
'name="visibility_in_air"; level="(6,*,*)";'
'name="visibility_in_air"; level="(@50,*,*)";'
```

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[No]**

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

An unittest is added. One more output at plot_data_plane//visibility_in_air_by_percentile.ps

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — CHANGES_REQUESTED** [review]
Hi @hsoh-u. Thank you for making this changes for main v11.1 to resolve the problems as described in #2638.  I have reviewed the changes and am waiting to approve to ensure the tests pass. Could you also please add a unit test using the input file?

**Comment by hsoh-u** [comment]
The input file is added to mohawk for unittest at /d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc. unit_test-all.tgz is updated, too

**Comment by jprestop** [comment]
Thank you for your reply @hsoh-u.  Based on @JohnHalleyGotway's comment in the issue description:

> Recommend adding a unit test using the input file.

I interpreted that as adding a unit test (https://github.com/dtcenter/MET/tree/main_v11.1/internal/test_unit/xml) using the input file.  Could you please add a unit test for this in an appropriate xml file?

**Comment by hsoh-u** [comment]
An unit test is added

**Comment by jprestop** [comment]
@hsoh-u I see that one of the tests failed due to:

> ERROR  : 
ERROR  : grd_file_type() -> file does not exist "/data/input/MET_test_data/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc"
ERROR  : 

Is that expected?  I know you said that you added it to /d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc and unit_test-all.tgz, so I was surprised to see this fail, but I really don't know the details of the connections.  Please let me know if you expected it to fail and I can approve.

**Comment by hsoh-u** [comment]
> @hsoh-u I see that one of the tests failed due to:
> 
> > ERROR  :
> > ERROR  : grd_file_type() -> file does not exist "/data/input/MET_test_data/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc"
> > ERROR  :
> 
> Is that expected? I know you said that you added it to /d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc and unit_test-all.tgz, so I was surprised to see this fail, but I really don't know the details of the connections. Please let me know if you expected it to fail and I can approve.

Not expected. It looks like the new input data file for unittest is not available at Docker for version 11.1.
There will be procedures to update the unittest input to Docker. I don't know details (for example, if the procedures are automated). I did the first step, updating tar file at mohawk
- /d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test/v11.1/unit_test-all.tgz
- /d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test/develop/unit_test-all.tgz
- /d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc

**Comment by hsoh-u** [comment]
unit_test-all.tgz at develop and v11.1 were updated yesterday. GHA failed because of newly added input file. What is the next step to add new input file for Docker?

GHA error messages:
```
DEBUG 1: Opening data file: /data/input/MET_test_data/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc
ERROR  : 
ERROR  : grd_file_type() -> file does not exist "/data/input/MET_test_data/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc"
```

Status of mohawk for unit test data:
```
WARNING: YOU ARE met_test@mohawk:/d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test$ pwd
/d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test
WARNING: YOU ARE met_test@mohawk:/d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test$ find -type f -name "unit_test-all.tgz" -ls
861995721 7040304 -rw-r--r--   1 met_test met-dev  7209255177 Aug 17 20:21 ./v11.1/unit_test-all.tgz
862100595 4496852 -rw-r--r--   1 met_test met-dev  4604765515 Feb  5  2023 ./v11.0/unit_test-all.tgz
862037476 7026040 -rw-r--r--   1 met_test met-dev  7194651312 Aug 17 18:02 ./develop/unit_test-all.tgz
WARNING: YOU ARE met_test@mohawk:/d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test$ find -type f -name "percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc"
./unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc
./v11.1/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc
./develop/unit_test/model_data/nccf/percentile_extract_20230729T1200Z-B20230725T0030Z-visibility_at_screen_level.nc
```

**Comment by jprestop** [comment]
@hsoh-u 

> What is the next step to add new input file for Docker?

I am not sure.  I tried poking around in the GitHub Actions files in .github, but I could not find this information.  @JohnHalleyGotway are you able to help us out with this information?

**Comment by JohnHalleyGotway** [comment]
FYI, I added the project and milestone to this PR. Please remember to check the Projects, Milestone, and Development metadata when submitting and reviewing to make sure this PR and linked issue get added to the release notes for the target release.

Copy/pasting info over from Slack:
I see the reason for the GHA failure for this PR, and it'll require a small fix to the GHA logic. It's basically version-itis.

The [Update input data volumes](https://github.com/dtcenter/MET/actions/runs/5894701585/job/16013305021?pr=2653) step is updating the **met-data-dev:develop** Docker image tag.
```
data repo: met-data-dev
data version: develop
```

While the actual [unit tests](https://github.com/dtcenter/MET/actions/runs/5894701585/job/16013908292?pr=2653) are pulling the **met-data-dev:11.1-all** Docker image tag.
```
Status: Downloaded newer image for dtcenter/met-data-dev:11.1-all
```
But that was never regenerated because the previous step didn't update it!

I will work on the necessary GHA updates on this feature branch now.

**Review by jprestop — APPROVED** [review]
It looks like the only difference is the new file:
```
dir1: /data/output/met_test_truth contains 1104 files
dir2: /data/output/met_test_output contains 1105 files

ERROR: folder /data/output/met_test_truth missing 1 files
    plot_data_plane/visibility_in_air_by_percentile.ps 
```

I approve.

**Pull request merged**
