### PR TITLE
Bugfix 2428 python from env main v11.0

### LINKED ISSUE #2386: Convert the python list to the numpy array for the python embedding at the base class.
The python list and the numpy array are accepted for the python embedding. The current implementation gives a INFO message if the python list contains numpy data type members.
- no info message with 1) python list  & python general numeric data type members and 2) numpy array & numpy data type members
- info message with the python list & the numpy data type members
```
==INFO_PYTHON== Recommend using numpy instead of python list for obs_hgt (<class 'numpy.float32'>)
==INFO_PYTHON== Recommend using numpy instead of python list for obs_val (<class 'numpy.float32'>)
```

## Describe the Enhancement ##
MET codes handle better with the numpy array than the python list for the python embedding. It's better to convert the python list to numpy array instead of giving a INFO message at the base python class (met_point_obs.py).

### Time Estimate ###
*Estimate the amount of work required here.*
4 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2702691

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### LINKED ISSUE #2428: Bugfix: Fix the MET vx_pointdata_python library to handle MET_PYTHON_EXE for python embedding of point observations
## Describe the Problem ##
When a user runs a point data tool `plot_point_obs`, `point_stat`, etc. with the environment variable `MET_PYTHON_EXE` set, MET does not override the default Python with the value from `MET_PYTHON_EXE`.

### Expected Behavior ###
When a user sets `MET_PYTHON_EXE`, the MET tools should override the default Python executable and use the users Python executable. The example below under "To Reproduce" reports this:
```
DEBUG 3: Initializing python: /usr/local/met-python3/bin/python3.8
```

but I would expect it to say this:
```
DEBUG 3: Initializing python: /home/met_test/.conda/envs/metplus_base.v5/bin/python3
```

### Environment ###
Testing on seneca on Linux using the MET develop nightly build which reports the Python executable being used.

### To Reproduce ###
On seneca:
```
export MET_PYTHON_EXE=/home/met_test/.conda/envs/metplus_base.v5/bin/python3

/d1/projects/MET/MET_regression/develop/NB20230130/MET-develop/bin/plot_point_obs "PYTHON_NUMPY=/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point.py /d1/projects/MET/MET_releases/MET-11.0.0/data/sample_obs/ascii/sample_ascii_obs.txt" test.ps -v 3
```

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792542

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

If MET_PYTHON_EXE is defined, the met_point_data should be saved as temporary NetCDF file and MET reads the NetCDF file. The log message shows if the temporary file was created. MET deletes the temporary file.
Without the environment variable MET_PYTHON_EXE 
```
DEBUG 3: Running user's python script (../../../../scripts/python/read_met_point_obs).
DEBUG 2: Processing 78376 observations at 8465 locations.
```
With the environment variable MET_PYTHON_EXE 
```
DEBUG 3: Calling /usr/local/met-python3/bin/python3.8 to run user's python script (../../../../scripts/python/read_met_point_obs).
DEBUG 4: Writing temporary Python point data file:
DEBUG 4:        /usr/local/met-python3/bin/python3.8 /d1/personal/hsoh/git/bugfixes/bugfix_2428_python_from_env_main_v11.0/MET/share/met/wrappers/write_tmp_point_nc.py /dev/shm/hsoh/tmp/tmp_met_nc_18941_0 ../../../../scripts/python/read_met_point_obs /d1/personal/hsoh/MET/test_output/NB/pb2nc/ndas.20120409.t12z.prepbufr.tm00.nc
  python: Python Script:        '/d1/personal/hsoh/git/bugfixes/bugfix_2428_python_from_env_main_v11.0/MET/share/met/wrappers/write_tmp_point_nc.py'
  python: User Command: '../../../../scripts/python/read_met_point_obs /d1/personal/hsoh/MET/test_output/NB/pb2nc/ndas.20120409.t12z.prepbufr.tm00.nc'
  python: Temporary File:       '/dev/shm/hsoh/tmp/tmp_met_nc_18941_0'
  python: Done python script ../../../../scripts/python/read_met_point_obs took 0:00:00.045950
DEBUG 4: Reading temporary Python point data file: /dev/shm/hsoh/tmp/tmp_met_nc_18941_0
DEBUG 2: Processing 78376 observations at 8465 locations.
```

Note: The following log message was not added for 11.0 branch because MET_PYTHON_BIN_EXE was not introduced at 11.0 branch.
```
DEBUG 3: Initializing python: /usr/local/met-python3/bin/python3.8
```

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

at seneca:

```
export MET_BASE=/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met
export MET_PYTHON_EXE=/usr/local/met-python3/bin/python3.8

/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/bin/plot_point_obs \
   'PYTHON_NUMPY=/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/scripts/python/read_met_point_obs.py /d1/personal/hsoh/MET/test_output/NB/pb2nc/ndas.20120409.t12z.prepbufr.tm00.nc' \
  pointdata_numpy.ps -dotsize 2.0 -v 4 | grep -v "Plotting location"

unset MET_PYTHON_EXE

/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/bin/plot_point_obs \
   'PYTHON_NUMPY=/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/scripts/python/read_met_point_obs.py /d1/personal/hsoh/MET/test_output/NB/pb2nc/ndas.20120409.t12z.prepbufr.tm00.nc' \
  pointdata_numpy.ps -dotsize 2.0 -v 4 | grep -v "Plotting location"

```
Test from [#2428](https://github.com/dtcenter/MET/issues/2428) 

```
export MET_BASE=/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met
export MET_PYTHON_EXE=/usr/local/met-python3/bin/python3.8

/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/bin/plot_point_obs \
  "PYTHON_NUMPY=/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/scripts/python/read_ascii_point.py /d1/projects/MET/MET_releases/MET-11.0.0/data/sample_obs/ascii/sample_ascii_obs.txt" \
  test.ps -v 4 | grep -v "Plotting location"
```

Added unit test
```
/d1/personal/hsoh/git/bugfixes/bugfix_2428_python_from_env_main_v11.0/MET/internal/test_unit/perl/unit.pl /d1/personal/hsoh/git/bugfixes/bugfix_2428_python_from_env_main_v11.0/MET/internal/test_unit/xml/unit_python.xml -log unit_python.log

TEST: python_point2grid_pb2nc_TMP                       - pass -   2.072 sec
TEST: python_point2grid_pb2nc_TMP_user_python           - pass -   3.281 sec
```

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

Unittest "python_point2grid_pb2nc_TMP_user_python" was added. It should produce the same output with python_point2grid_pb2nc_TMP (pb2nc_TMP.nc  and pb2nc_TMP_user_python.nc).

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

No except a new output python/pb2nc_TMP_user_python.nc

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by georgemccabe — CHANGES_REQUESTED** [review]
The changes to the logs that list the version of Python used as described in [this comment](https://github.com/dtcenter/MET/issues/2428#issuecomment-1410859417) weren't implemented here.

I think it would be best for @DanielAdriaansen to test running with these changes to ensure the output matches what he expects.

**Comment by hsoh-u** [comment]
> The changes to the logs that list the version of Python used as described in [this comment](https://github.com/dtcenter/MET/issues/2428#issuecomment-1410859417) weren't implemented here.
> 
> I think it would be best for @DanielAdriaansen to test running with these changes to ensure the output matches what he expects.

How to get the compile time python exe?
Is MET_PYTHON_BIN_EXE available at main_v11.0 branch?

**Comment by georgemccabe** [comment]
> > The changes to the logs that list the version of Python used as described in [this comment](https://github.com/dtcenter/MET/issues/2428#issuecomment-1410859417) weren't implemented here.
> > I think it would be best for @DanielAdriaansen to test running with these changes to ensure the output matches what he expects.
> 
> How to get the compile time python exe? Is MET_PYTHON_BIN_EXE available at main_v11.0 branch?

I'm sorry, I didn't realize this was for main_v11.0. I don't think any log changes are needed.

> sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),

Modified  read_tmp_point_nc.py & write_tmp_point_nc.py (github and /d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0).
Dan, would you test it without MET_BASE settting?
```
unset MET_BASE
```

**Comment by DanielAdriaansen** [comment]
@hsoh-u should `met_point_obs` be able to be automatically found in 11.0.0? Or is that only going to be available in future releases?

I am running this command on seneca:
```
export MET_PYTHON_EXE=/home/met_test/.conda/envs/metplus_base.v5/bin/python3
/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/bin/plot_point_obs "PYTHON_NUMPY=/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point.py /d1/projects/MET/MET_releases/MET-11.0.0/data/sample_obs/ascii/sample_ascii_obs.txt" test.ps -v 3
```

But get this error:
```
DEBUG 3: Calling /home/met_test/.conda/envs/metplus_base.v5/bin/python3 to run user's python script (/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point).
Traceback (most recent call last):
  File "/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met/wrappers/write_tmp_point_nc.py", line 19, in <module>
    from met_point_obs import met_point_obs
ModuleNotFoundError: No module named 'met_point_obs'
```

**Comment by hsoh-u** [comment]
> @hsoh-u should `met_point_obs` be able to be automatically found in 11.0.0? Or is that only going to be available in future releases?
> 
> I am running this command on seneca:
> 
> ```
> export MET_PYTHON_EXE=/home/met_test/.conda/envs/metplus_base.v5/bin/python3
> /d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/bin/plot_point_obs "PYTHON_NUMPY=/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point.py /d1/projects/MET/MET_releases/MET-11.0.0/data/sample_obs/ascii/sample_ascii_obs.txt" test.ps -v 3
> ```
> 
> But get this error:
> 
> ```
> DEBUG 3: Calling /home/met_test/.conda/envs/metplus_base.v5/bin/python3 to run user's python script (/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point).
> Traceback (most recent call last):
>   File "/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met/wrappers/write_tmp_point_nc.py", line 19, in <module>
>     from met_point_obs import met_point_obs
> ModuleNotFoundError: No module named 'met_point_obs'
> ```

It depends on MET_BASE setting. MET adds MET_BASE/python and MET_BASE/wrappers into the system path for python. If MET_BASE is not set, it fails to find "met_point_obs.py" which is in MET_BASE/python directory ("/python" and "/wrappers" are added to the system path).

Please check if this helps:
```
export MET_BASE=/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met
```

**Comment by DanielAdriaansen** [comment]
OK, that helps thank you Howard. Now I am getting this error:
```
DEBUG 3: Calling /home/met_test/.conda/envs/metplus_base.v5/bin/python3 to run user's python script (/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point).
Traceback (most recent call last):
  File "/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met/wrappers/write_tmp_point_nc.py", line 19, in <module>
    from met_point_obs import met_point_obs
  File "/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met/python/met_point_obs.py", line 27, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

I think this is related to #2386 is that right? 

It looks like NumPy is listed already as a dependency for MET Python Embedding, so I think this is OK, and I will change to a Python environment that has NumPy because apparently `/home/met_test/.conda/envs/metplus_base.v5/bin/python3` on Seneca does not.

I am adding a note on #2414 to suggest unifying the Python requirements for METplus wrappers and the requirements for a Python to use when building MET for Python Embedding support.

**Comment by DanielAdriaansen** [comment]
@georgemccabe regarding Howard's comment:

> It depends on MET_BASE setting. MET adds MET_BASE/python and MET_BASE/wrappers into the system path for python. If MET_BASE is not set, it fails to find "met_point_obs.py" which is in MET_BASE/python directory ("/python" and "/wrappers" are added to the system path).

Does METplus wrappers set `MET_BASE` somehow? I know that `MET_INSTALL_DIR` is required for the METplus wrappers, so I am wondering if `MET_BASE` is set automatically or not set by METplus wrappers.

**Comment by hsoh-u** [comment]
> OK, that helps thank you Howard. Now I am getting this error:
> 
> ```
> DEBUG 3: Calling /home/met_test/.conda/envs/metplus_base.v5/bin/python3 to run user's python script (/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point).
> Traceback (most recent call last):
>   File "/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met/wrappers/write_tmp_point_nc.py", line 19, in <module>
>     from met_point_obs import met_point_obs
>   File "/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/share/met/python/met_point_obs.py", line 27, in <module>
>     import numpy as np
> ModuleNotFoundError: No module named 'numpy'
> ```
> 
> I think this is related to #2386 is that right?
> 
> It looks like NumPy is listed already as a dependency for MET Python Embedding, so I think this is OK, and I will change to a Python environment that has NumPy because apparently `/home/met_test/.conda/envs/metplus_base.v5/bin/python3` on Seneca does not.
> 
> I am adding a note on #2414 to suggest unifying the Python requirements for METplus wrappers and the requirements for a Python to use when building MET for Python Embedding support.

No, it's not.
The python3 you are using does not have the numpy package as is. You may need to activate the conda.
```
(base) hsoh@seneca:MET$ /home/met_test/.conda/envs/metplus_base.v5/bin/python3 -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

**Comment by DanielAdriaansen** [comment]
Is there an open issue to log `MET_PYTHON_BIN_EXE` in future versions? If not, I can create one.

**Comment by hsoh-u** [comment]
> @georgemccabe regarding Howard's comment:
> 
> > It depends on MET_BASE setting. MET adds MET_BASE/python and MET_BASE/wrappers into the system path for python. If MET_BASE is not set, it fails to find "met_point_obs.py" which is in MET_BASE/python directory ("/python" and "/wrappers" are added to the system path).
> 
> Does METplus wrappers set `MET_BASE` somehow? I know that `MET_INSTALL_DIR` is required for the METplus wrappers, so I am wondering if `MET_BASE` is set automatically or not set by METplus wrappers.

Not sure without METplus configuration. I set MET_BASE manually as needed at seneca.
MET_BASE is not defined at internal/scripts/environment/development.seneca

**Comment by georgemccabe** [comment]
I believe MET_BASE is set to a default value of where MET is installed. The wrappers do not override this value.

You shouldn't have to set MET_BASE to include the python directory in the path. It is added in other files by using the relative path from the script. See: https://github.com/dtcenter/MET/blob/eb987a401413723950d7c66ed05f42b8f9d03ef1/data/wrappers/write_tmp_dataplane.py#L25-L26

> @georgemccabe regarding Howard's comment:
> 
> > It depends on MET_BASE setting. MET adds MET_BASE/python and MET_BASE/wrappers into the system path for python. If MET_BASE is not set, it fails to find "met_point_obs.py" which is in MET_BASE/python directory ("/python" and "/wrappers" are added to the system path).
> 
> Does METplus wrappers set `MET_BASE` somehow? I know that `MET_INSTALL_DIR` is required for the METplus wrappers, so I am wondering if `MET_BASE` is set automatically or not set by METplus wrappers.

**Comment by DanielAdriaansen** [comment]
@hsoh-u can you please add the code @georgemccabe sent from `write_tmp_dataplane.py` to `write_tmp_point_nc.py`?

**Comment by hsoh-u** [comment]
> Is there an open issue to log `MET_PYTHON_BIN_EXE` in future versions? If not, I can create one.

I don't think this is an issues. The log already exists for python embedding of gridded data (MET v11.1 development version) or the existing log message should be changed as @georgemccabe mentioned [this comment](https://github.com/dtcenter/MET/issues/2428#issuecomment-1410859417). The same log should be added for the python embedding of the point observation data. But it can not be added to the 11.0 branch for both (python embedding of gridded and point data).

**Comment by DanielAdriaansen** [comment]
> > Is there an open issue to log `MET_PYTHON_BIN_EXE` in future versions? If not, I can create one.
> 
> I don't think this is an issues. The log already exists for python embedding of gridded data (MET v11.1 development version). The same log should be added for the python embedding of the point observation data. But it can not be added to the 11.0 branch for both (python embedding of gridded and point data).

OK, that makes sense. Then will this PR also be merged into MET v11.1 development version?

**Comment by hsoh-u** [comment]
> @hsoh-u can you please add the code @georgemccabe sent from `write_tmp_dataplane.py` to `write_tmp_point_nc.py`?

Updated at github repository

Sorry my script does not allow new build for Pull Request to the different location.
- /d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0 was renamed to /d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0_rev1
  + Two python scripts are updated here (read_tmp_point_nc.py and write_tmp_point_nc.py)
- New checkout is done at /d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0 and the build was started

**Comment by DanielAdriaansen** [comment]
I performed the following testing on seneca with the new changes.

**TEST 1**
```
/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/bin/plot_point_obs "PYTHON_NUMPY=/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point.py /d1/projects/MET/MET_releases/MET-11.0.0/data/sample_obs/ascii/sample_ascii_obs.txt" test.ps -v 3
```
This worked as expected, and worked previously.

**TEST 2**
```
export MET_PYTHON_EXE=/home/dadriaan/.conda/envs/icing/bin/python3
/d1/personal/hsoh/git/pull_request/MET_bugfix_2428_python_from_env_main_v11.0/bin/plot_point_obs "PYTHON_NUMPY=/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point.py /d1/projects/MET/MET_releases/MET-11.0.0/data/sample_obs/ascii/sample_ascii_obs.txt" test.ps -v 3
```
This would also have worked previously, but would have silently used the same Python as **TEST 1**, instead of `MET_PYTHON_EXE` Python.

The output from **TEST 2** now correctly informs me MET is using `MET_PYTHON_EXE` Python to run the Python embedding:
```
DEBUG 3: Calling /home/dadriaan/.conda/envs/icing/bin/python3 to run user's python script (/d1/projects/MET/MET_releases/MET-11.0.0/scripts/python/read_ascii_point).
```

Howard also added additional changes so that a user does not need to set `MET_BASE` when using `MET_PYTHON_EXE` in order for `met_point_obs` to be able to be imported, consistent with `write_tmp_dataplane.py`.

In future versions, the addition of `MET_PYTHON_BIN_EXE` will make it clear to the user in **TEST 1** that the Python MET was built with is being used, but this feature is not available in main_v11.0.0 so that is not currently the case.

In addition, @georgemccabe shared with me this change:
https://github.com/dtcenter/MET/pull/2407/commits/5ad920b3fab2ddf1c5fe5aa3a73e014addab9a74
which will allow Python embedding in the future if `MET_PYTHON_EXE` is unset to still find `met_point_obs` without the user needing to set `MET_BASE`.

**Review by DanielAdriaansen — APPROVED** [review]
I approve.

**Comment by JohnHalleyGotway** [comment]
Merging this PR into main_v11.0 based on @DanielAdriaansen's approving review.

**Pull request merged**
