### PR TITLE
Bugfix 2596 main v11.0 rpath compilation

### LINKED ISSUE #2596: Bugfix: Unknown ld Flag on Macos causes MET compilation to fail
## Describe the Problem ##
When using GCC@12 from the homebrew package manager MET fails to build due to an unknown ld flag _--disable-new-dtags_. Gives an error thatC compiler cannot create executables.

All the libraries appear to have built successfully. 

### Expected Behavior ###
MET tools should be able to determine what ld flags are needed based on OS.

### Environment ###
Describe your runtime environment:
*1. Machine: Virtual Mac Laptop*
*2. OS: Mac OS 13.1.4
*3. Software version number(s) MET 11.0.2

### To Reproduce ###
Describe the steps to reproduce the behavior:
`  echo "MET INSTALLING"
  brew install wget
  brew install git
  brew install gcc@12
  brew install libtool
  brew install automake
  brew install autoconf
  brew install make
  brew install m4
  brew install java
  brew install ksh
  brew install grads
  brew install ksh
  brew install tcsh
  brew install snap
  brew install python@3.11
  brew install cmake
  brew install xorgproto
  brew install xorgrgb
  brew install xauth
  brew install curl
  brew install flex
  brew install byacc
  brew install bison
  brew install gnu-sed

   pip3.11 install python-dateutil

    #Directory Listings
    mkdir $HOME/DTC
    export WRF_FOLDER=$HOME/DTC

    if [ "$WRFCHEM_PICK" = "1" ]; then
      mkdir $HOME/WRFCHEM
      export WRF_FOLDER=$HOME/WRFCHEM
    fi

    if [ "$WRFHYDRO_COUPLED_PICK" = "1" ]; then
      mkdir $HOME/WRFHYDRO_COUPLED
      export WRF_FOLDER=$HOME/WRFHYDRO_COUPLED
    fi

    if [ "$WRFHYDRO_STANDALONE_PICK" = "1" ]; then
      mkdir $HOME/WRFHYDRO_STANDALONE
      export WRF_FOLDER=$HOME/WRFHYDRO_STANDALONE
    fi

    if [ "$WRF_PICK" = "1" ]; then
      mkdir $HOME/WRF
      export WRF_FOLDER=$HOME/WRF
    fi

    if [ "$HWRF_PICK" = "1" ]; then
      mkdir $HOME/HWRF
      export WRF_FOLDER=$HOME/HWRF
    fi

    mkdir $WRF_FOLDER/MET-11.0.2
    mkdir $WRF_FOLDER/MET-11.0.2/Downloads
    mkdir $WRF_FOLDER/METplus-5.0.1
    mkdir $WRF_FOLDER/METplus-5.0.1/Downloads

      #Symlink to avoid clang conflicts with compilers
      #default gcc path /usr/bin/gcc
      #default homebrew path /usr/local/bin

      echo "Please enter password for linking GNU libraries"

      echo $PASSWD | sudo -S ln -sf /usr/local/bin/gcc-12 /usr/local/bin/gcc
      echo $PASSWD | sudo -S ln -sf /usr/local/bin/g++-12 /usr/local/bin/g++
      echo $PASSWD | sudo -S ln -sf /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
      echo $PASSWD | sudo -S ln -sf /usr/local/bin/python3.11 /usr/local/bin/python3

    cd $WRF_FOLDER/MET-11.0.2/Downloads

   wget -c -4 https://raw.githubusercontent.com/dtcenter/MET/main_v11.0/internal/scripts/installation/compile_MET_all.sh

    wget -c -4 https://dtcenter.ucar.edu/dfiles/code/METplus/MET/installation/tar_files.tgz

    wget -c -4 https://github.com/dtcenter/MET/archive/refs/tags/v11.0.2.tar.gz

    cp compile_MET_all.sh $WRF_FOLDER/MET-11.0.2
    tar -xvzf tar_files.tgz -C $WRF_FOLDER/MET-11.0.2
    cp v11.0.2.tar.gz $WRF_FOLDER/MET-11.0.2/tar_files
    cd $WRF_FOLDER/MET-11.0.2

    cd $WRF_FOLDER/MET-11.0.2

    export PYTHON_VERSION=$(python3 -V 2>1|awk '{print $2}')
    export PYTHON_VERSION_MAJOR_VERSION=$(echo $PYTHON_VERSION | awk -F. '{print $1}')
    export PYTHON_VERSION_MINOR_VERSION=$(echo $PYTHON_VERSION | awk -F. '{print $2}')
    export PYTHON_VERSION_COMBINED=$PYTHON_VERSION_MAJOR_VERSION.$PYTHON_VERSION_MINOR_VERSION

    export CC=/usr/local/bin/gcc
    export CXX=/usr/local/bin/g++
    export CFLAGS="-fPIC -fPIE -O3 -Wno-implicit-function-declaration"
    export FC=/usr/local/bin/gfortran
    export F77=/usr/local/bin/gfortran
    export F90=/usr/local/bin/gfortran
    export gcc_version=$(gcc -dumpfullversion)
    export TEST_BASE=$WRF_FOLDER/MET-11.0.2
    export COMPILER=gnu_$gcc_version
    export MET_SUBDIR=${TEST_BASE}
    export MET_TARBALL=v11.0.2.tar.gz
    export USE_MODULES=FALSE
    export MET_PYTHON=/usr/local/

    export MET_PYTHON_CC="-I$MET_PYTHON/opt/python@$PYTHON_VERSION_COMBINED/Frameworks/Python.framework/Versions/$PYTHON_VERSION_COMBINED/include/python$PYTHON_VERSION_COMBINED"
    export MET_PYTHON_LD="-L$MET_PYTHON/opt/python@$PYTHON_VERSION_COMBINED/Frameworks/Python.framework/Versions/$PYTHON_VERSION_COMBINED/lib/python$PYTHON_VERSION_COMBINED/config-$PYTHON_VERSION_COMBINED-darwin -lpython$PYTHON_VERSION_COMBINED -ldl -framework CoreFoundation"

    export SET_D64BIT=FALSE

    chmod 775 compile_MET_all.sh

    sed -i'' -e "831s/export/#export/g" compile_MET_all.sh
    time ./compile_MET_all.sh 2>&1 | tee compile_MET_all.log

[config.log](https://github.com/dtcenter/MET/files/11916752/config.log)
[configure.log](https://github.com/dtcenter/MET/files/11916753/configure.log)
[compile_MET_all.log](https://github.com/dtcenter/MET/files/11916754/compile_MET_all.log)

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
2792543

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Tested compilation on narya using the gcc version 12.3.0 compiler.  After reproducing the problem described in the issue, I was able to resolve the problem with these changes to the script and got a successful compilation and a successful run of "make test".  I also tested the changes in the script with the gcc version 12.1.0 compiler on cheyenne and got a successful compilation and a successful run of "make test".

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
No testing needed.  Review the files that changed and ensure that all tests pass.  Could compile on a machines using gcc version 12.3.0 if desired.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[20230710]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by hsoh-u — APPROVED** [review]
I approve this changes.

There is an instance without major version :
- internal/scripts/installation/config/install_met_env.generic:export COMPILER=gnu

This causes the same value "gnu" for all three: COMPILER_FAMILY, COMPILER_MAJOR_VERSION, and COMPILER_MINOR_VERSION. It does not cause a problem at seneca (it seems to convert the string "gnu" to integer for the major and minor versions with "if xxx -ge 12"). It would be nice to set to 0 if "COMPILER_FAMILY is the same asCOMPILER_MAJOR_VERSION.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u and @jprestop just following up on this PR. Looks like its been approved for a week. Julie, can you please merge it assuming its ready?

**Comment by jprestop** [comment]
@JohnHalleyGotway It's not quite ready yet.  Please see this comment on this issue:
https://github.com/dtcenter/MET/issues/2596#issuecomment-1622870505

**Comment by jprestop** [comment]
@JohnHalleyGotway Do you want me to close the PR instead of letting it sit?  I haven't been able to get back to this work yet.

**Pull request merged**
