### PR TITLE
Feature 2231 unstructured grid

### LINKED ISSUE #2231: Add support for NetCDF files following the UGRID convention
## Describe the New Feature ##
This new feature request was originally combined with #1954 but has been split off into this separate issue.

MET needs to be enhanced to supported gridded NetCDF files following the UGRID convention (```Conventions = "UGRID"```):
[ugrid-conventions.github.io/ugrid-conventions](https://ugrid-conventions.github.io/ugrid-conventions/)

Recommend doing development using both LFRic and MPAS NetCDF files side-by-side. This will require a new vx_data2d_ugrid library to extract data from these NetCDF files. In addition, it'll require a new unstructured grid class in the vx_grid library.

The UGRID grid class will need to link to the source NetCDF file since it must be queried while working with it. One key piece of functionality will be instantiating a kdtree for that UGRID. Recommend leveraging an external C++ library rather than coding that up ourselves.

Some pieces of functionality we'll need to add are:
- Enhance Point-Stat to verify points natively on the UGRID.
- Consider parallelizing the loop for interpolating model data to point locations to make it as fast as possible.
- Support nearest neighbor as well as the min/max/uw_mean/dw_mean of the nearest N points.
- Enhance Grid-Stat and Series-Analysis to compare UGRID to UGRID on the same grid.

Future considerations include:
- Using lookup tables to make the interpolation to point locations more efficient rather than calling kdtrees.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
Weeks

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2799991	Met Office METplus Support & 7705991 MPAS participation

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: @willmayfield 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- May want separate issues for plotting UGRID data but I don't think these changes have any direct impacts on other repos.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

The capability of unstructured grid is implemented, but not completed.
- `--enable-ugrid` is added to the `configure`, default is without ugrid capability.
  - At seneca, atlas and eckit libraries are installed at /d1/projects/MET/MET_releases/external_libs/gnu_8.3.0
  - The configuration for seneca is updated at `internal/scripts/environment/development.seneca` 
- Updated configurations, see below
  - added 
- Find variables by looking at the `level` setting  (L and P options only) if the given name does not exist:
  - search the variable "\<name\>\_\<DDD\>\<uuu\>", "temperature\_\<DDD\>\<uuu\>
    -  DDD: vertical level from `level` setting, pressure or height
    -  uuu: unit, optional, ignore the unit  if exists, for example, hPa
  - for example,`name = "temperature";  level = "P1000-500";` is given
  - result: temperature_500hPa, temperature_700hPa, temperature_850hPa, and temperature_925hPa are selected
- Four unit tests are added
  - point_stat
    - MPAS diagnostic file VS prefburf
    - MPAS output file VS prefburf
  - grid_stat:
    -  MPAS diagnostic VS. GFS (grib2)
    -  MPAS diagnostic VS. MPAS output
  - four configuration files were added
    - internal/test_unit/config/GridStatConfig_ugrid_mpas
    - internal/test_unit/config/GridStatConfig_ugrid_mpas_diag
    - internal/test_unit/config/PointStatConfig_ugrid_mpas_diag
    - internal/test_unit/config/PointStatConfig_ugrid_mpas_out
  - $MET_TEST_INPUT/ugrid_data is added

Error messages if "file_type = NETCDF_UGRID" is configured at the configuration file but MET was built without "--enable-ugrid" option:
```
ERROR  :
ERROR  : Met2dDataFileFactory::new_met_2d_data_file() -> data file type "FileType_UGrid" is not activated. Recompile with the --enable-ugrid option"
ERROR  :
```

Not completed items:
- GHA is not ready because of missing Atlas and eckit libraries for the Docker
- The grid_stat output as the unstructured grid is not supported
  - The regrid option has to be configured for the grid_stat between unstructured grid inputs
- Documentation: not done
- Unit test
   - the unit test of the unstructured grid is not conditional
   - did not set \<grid_nc\> output with grid_stat because of parsing error

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**</br>
If **yes**, please describe:</br>

- File type NETCDF_UGRID is added
- Three configurations are added to GridStatConfig and PointStatConfig
  - ugrid_max_distance_km = 30;
  - ugrid_user_map_config: to override metadata settings (dimension and variable names)
  - ugrid_coordinates_file: to specify the static metadata file (for MPAS)

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Added in the unit test (commands and configurations)

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Test with other MPAS input.
Test with LFRic data (I did not test LFRic data)
The build is ready at /d1/personal/hsoh/git/pull_request/MET_feature_2231_unstructured_grid/bin

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

Working on this

- [x] Do these changes include sufficient testing updates? **[Yes]**

Four unit tests are added (see above)

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

more outputs from the four unit tests

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by hsoh-u** [comment]
The error message of grid_stat when both the forecast and observation are the unstructured grid data (because the output capability is not implemented). The regrid option at the configuration must be specified to avoid this error message.

DEBUG 1: Forecast File: /d1/projects/MET/MET_test_data/unit_test/ugrid_data/mpas/diag.2012-04-09_12.00.00_reduced.nc
DEBUG 1: Observation File: /d1/projects/MET/MET_test_data/unit_test/ugrid_data/mpas/mpasout.2012-04-09_12.00.00_reduced.nc
ERROR  :
ERROR  : grid_output(const GridInfo &, NcFile *) -> can't determine projection!
ERROR  :

**Review by DanielAdriaansen — APPROVED** [review]
Documentation is still needed, but functionality with point_stat and grid_stat has been tested with MPAS output for two meshes. Great work @hsoh-u !

I approve, and look forward to expanding on this for the next beta.

**Review by willmayfield — APPROVED** [review]
Ran a few tests with point_stat (diag files vs bufr) and grid_stat (diag files vs diag files, results on climo file grid), using MPAS diag files with pressure levels in separate netcdf variables. Used separate lines in the config for these variables. Results were as expected and run times reasonable for a high resolution mesh. Approving!

**Comment by JohnHalleyGotway** [comment]
Thanks @hsoh-u for all this excellent work, and thanks to @DanielAdriaansen and @willmayfield for advising on and reviewing it. I'm proceeding with the merge into develop for inclusion in the MET-12.0.0-beta2 release.

**Comment by willmayfield** [comment]
Great work @hsoh-u !!! And thank you @DanielAdriaansen and @JohnHalleyGotway !

**Pull request merged**
