### PR TITLE
Feature 2937 update unit

### LINKED ISSUE #2937: Enhance the `unit.py` MET testing script to allow for expected failures
## Describe the New Feature ##
This issue is derived from dtcenter/METplus-Internal#23.

This task is to enhance the logic of the `unit.py` MET testing script to allow for expected failures.

That script reads one or more input XML files specified as command line arguments. Each XML file consists of one or more tests, each defined using the `<test>` XML tag. For each test, the `<exec>` tag specifies the command that should be executed, which is typically a call to a MET executable. If the command run for that test returns non-zero status, then the test fails, prints a failure message, and writes the test output to the screen. For example:
```
TEST: pcp_combine_sum_GRIB1
	- FAIL - 	1.072 sec
/Volumes/d1/projects/MET/MET_development/MET-feature_2924_fcst_climo/internal/test_unit/../../share/met/../../bin/pcp_combine \
      20120409_00 3 20120409_18 18 \
      /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/pcp_combine/nam_2012040900_F018_APCP18.nc \
      -pcpdir /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/BADPATH/grib1/namDEBUG 1: Start pcp_combine by johnhg(6088) at 2024-07-18 21:54:49Z  cmd: /Volumes/d1/projects/MET/MET_development/MET-feature_2924_fcst_climo/internal/test_unit/../../share/met/../../bin/pcp_combine 20120409_00 3 20120409_18 18 /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/pcp_combine/nam_2012040900_F018_APCP18.nc -pcpdir /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/BADPATH/grib1/nam 
DEBUG 2: Performing sum command: Init/In_Accum/Valid/Out_Accum Times = 20120409_000000/030000/20120409_180000/180000
DEBUG 2: Searching for 6 files with accumulation times of 030000 to sum to a total accumulation time of 180000.
ERROR  : 
ERROR  : search_pcp_dir() -> can't open search directory: /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/BADPATH/grib1/nam
ERROR  : 
```
This issue is to enhance the control logic to allow for expected failures. So that even though the command may return non-zero status, the test can still pass - if that's what was expected.

Recommend adding a new tag to the MET test XML named `<retval>`. Use it to specify the expected return value from the `<exec>` command. Note that `<retval>` should be optional. If not present, the logic should use a default value of 0, which indicates a successful run.

Update the Python control logic to capture the return value from the `<exec>` command and compare it against the expected return value (either explicitly specified with `<retval>` or using the default value of 0 otherwise). If they match, the test succeeds. If they do not match, the test fails, and the stdout should be printed, which is the current behavior.

### Acceptance Testing ###
Please add at least one unit test that uses `<retval>` to specify an expected non-zero return value to demonstrate this new functionality.

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by natalieb-noaa**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**</br>
If **yes**, please describe:</br>
A new configuration option for unit testing: If test is expected to fail (execution returns a non-zero value), can include a <retval> in unit test xml

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
I created a testing test xml ("TEST... .xml" in MET/internal/test_unit/xml) that runs the ascii2nc_GAGE_24hr test with 6 scenarios: with no \<retval\> included in the test, with \<retval\> set to 0, and with \<retval\> set to 1, and for each of those a test that should have a return value of 0 (the standard ascii2nc_GAGE_24hr test) and a test that should have a return value of 1 (modified to pass a non-existent input file)

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
can run the same tests I did, make sure to use  -noexit flag

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]** </br>
If documentation exists for creating the unit test xml files, it would be good to update with the <retval> option

- [x] Do these changes include sufficient testing updates? **[N/A]**

- [x] Will this PR result in changes to the MET test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Will this PR result in changes to existing METplus Use Cases? **[No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by natalieb-noaa** [comment]
@JohnHalleyGotway Note on this feature: This retval check works against the return value of the exec command. However, if any of the output file checks return a non-zero value, the test will still fail. I think that's what we want here, but just want to call that out in case we also want to handle non-zero returns from the output checks.

**Comment by jprestop** [comment]
HI @natalieb-noaa.  Thanks for all of your work on this task.  I am running through these unit tests after not having run the unit tests in a while.  After setting the following:
```
export MET_PROJ_DIR=/d1/projects/MET
export MET_TEST_INPUT=${MET_PROJ_DIR}/MET_test_data/unit_test
export MET_TEST_OUTPUT=/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2937_update_unit/output
export MET_TEST_RSCRIPT=/nrit/ral/bin/Rscript
export MET_BASE=/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2937_update_unit/internal/test_unit/../../share/met
export MET_BUILD_BASE=/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2937_update_unit/internal/test_unit/../..
export MET_TEST_BASE=/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2937_update_unit/internal/test_unit
```
and executing the tests from seneca:/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2937_update_unit/internal/test_unit as the `met_test` user:
```
(base) WARNING: YOU ARE met_test@seneca:/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2937_update_unit/internal/test_unit$ python python/unit.py xml/TEST_unit_ascii2nc.xml -noexit
```
The code is not finding the `gauge/2012041012.badfile.ascii` file in my `DATA_DIR_OBS` directory.  
```
ERROR  : 
ERROR  : determine_ascii_format() -> can't open input ASCII file "/d1/projects/MET/MET_test_data/unit_test/obs_data/gauge/2012041012.badfile.ascii" for reading
ERROR  : 
```
Can you please tell me where I can find the file?

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
@jprestop, I see that you asked @natalieb-noaa for the path to `unit_test/obs_data/gauge/2012041012.badfile.ascii`. But I think the point is that that file DOES NOT and SHOULD NOT exist for this test. With this PR, we're adding the ability for the unit tests to return a FAILURE status... and stating that we expect the return code from that call to ascii2nc to be non-zero.

@natalieb-noaa I see that you added added a new file named `[TEST_unit_ascii2nc.xml](https://github.com/dtcenter/MET/pull/2944/files#diff-b98f6211f746ec354718b6297150c72f53a8302a6396135c9b18ea44d1d729de)` that has many calls to ascii2nc... along with many calls that are commented out.

My assumption is that you were using this to thoroughly test out your development, which is great. But this seems like overkill to add all these to our unit tests.

I'd recommend:
1. Remove `TEST_unit_ascii2nc.xml` from the `feature_2937_update_unit` branch to remove it from this PR.
2. Add one new test to the existing `unit_ascii2nc.xml` file where you provide a bad path to an ascii2nc input file (i.e. doesn't exist) and specify an expected non-zero return value.

**Comment by natalieb-noaa** [comment]
@jprestop , thanks for taking a look at this and @JohnHalleyGotway for chiming in while I've been out.

John is right that I created those tests with an intentionally nonexistent file, and the tests include multiple cases, some of which should pass and some of which should fail. I tried to explain that above but realize that it wasn't very clear (partially because everywhere I had typed "\<retval\>", it was hidden until I escaped the <> characters just now). And I named each test with "pass" or "fail" in it to know what the outcome should be. For example here is the output from the first 2 tests (an expected pass and an expected fail):
```
TEST: ascii2nc_GAGE_24hr_pass_no_retval
	- pass - 	0.734 sec
TEST: ascii2nc_GAGE_24hr_fail_no_retval
	- FAIL - 	0.513 sec
/d1/projects/MET/MET_regression/develop/NB20240819/MET-develop/share/met/../../bin/ascii2nc \
      /d1/projects/MET/MET_test_data/unit_test/obs_data/gauge/2012041012.badfile.ascii \
      /d1/personal/nbabij/met_testing/test_output/ascii2nc/gauge_2012041012_24hr.nc \
      -v 1DEBUG 1: Start ascii2nc by nbabij(43018) at 2024-08-20 21:17:40Z  cmd: /d1/projects/MET/MET_regression/develop/NB20240819/MET-develop/share/met/../../bin/ascii2nc /d1/projects/MET/MET_test_data/unit_test/obs_data/gauge/2012041012.badfile.ascii /d1/personal/nbabij/met_testing/test_output/ascii2nc/gauge_2012041012_24hr.nc -v 1
DEBUG 1: Config File: /d1/projects/MET/MET_regression/develop/NB20240819/MET-develop/share/met/config/Ascii2NcConfig_default
ERROR  :
ERROR  : determine_ascii_format() -> can't open input ASCII file "/d1/projects/MET/MET_test_data/unit_test/obs_data/gauge/2012041012.badfile.ascii" for reading
ERROR  :
```


I'm fine with removing the "TEST" test before merging this branch. I just wanted to make it available to a reviewer to show how this update affects the output in different scenarios without the reviewer having to come up with their own tests. (It was never intended to be included in the list of unit tests that are run automatically/regularly.)

@JohnHalleyGotway , regarding your 2nd recommendation, do you think it's necessary to add that as a test that is regularly run?

Let me know if this all makes sense now or if there are any other questions or anything you'd like to discuss further! Also, let me know if you'd like me to remove that test file immediately or if it's still useful for reviewing this PR.

**Comment by JohnHalleyGotway** [comment]
@natalieb-noaa sorry for the delay in responding. I need to figure out a better way of staying on top of my GitHub notifications!

I see why you'd want to provide the `TEST_unit_ascii2nc.xml` file to make it easier for the reviewer to test. One idea is just adding that file as an _attachment_ to the PR rather than including it in the actual set of proposed changes in your feature branch.

And yes, please to update one of the existing `unit_...` files to add a test that is expected to fail. And yes, it's fine to do it in `unit_ascii2nc.xml`. Since you're adding this feature to allow for expected failures, I'd like to have at least one test that we run all the time to demonstrate it.

Once you've pushed final changes that are ready to be re-reviewed, please click the little blue circle icon next to my name on the PR to indicate that it's all ready. Here's what that looks like:
Screen Shot 2024-08-23 at 9 04 53 AM

Thanks for working through this!

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes. Thanks @natalieb-noaa.

I tested that copy/paste of environment variables with nested double-quotes now works as expected. And I see that you've added that calls to ascii2nc to demonstrate an expected failure.

I'll go ahead and merge this PR myself since I'm in the midst of merging several in a particular order.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes. Thanks @natalieb-noaa.

I tested that copy/paste of environment variables with nested double-quotes now works as expected. And I see that you've added that calls to ascii2nc to demonstrate an expected failure.

I'll go ahead and merge this PR myself since I'm in the midst of merging several in a particular order.

**Pull request merged**
