### PR TITLE
Feature 1844 python embedding

### LINKED ISSUE #1844: Enhance Ensemble-Stat, Point-Stat, Plot-Point-Obs, and Point2Grid to support python embedding of point observations.
## Describe the New Feature ##

This issue was originally titled "Allow read into memory for Point2Grid". However this feature request should be done as part of a larger task to more broadly support python embedding of point observations across multiple tools. Currently, this type of python embedding is only supported in ascii2nc. This task is to expand that support to include point_stat, ensemble_stat, point2grid, and plot_point_obs. I believe those are all the tools which read the NetCDF point observation files written by the *2NC point pre-processing tools. If needed, consider breaking this issue out into separate ones for each of those tools. Make sure that the conventions for requesting python embedding of point observations are as consistent as possible across these tools.

Currently, The MET user's guide states the Point2Grid tool "...takes point observations from a NetCDF output file from one of the four previously mentioned MET tools (ascii2nc, madis2nc, pb2nc, lidar2nc) and creates a gridded NetCDF file." The original workflow did not take advantage of the Python embedding, which is now prevalent in MET.

A recent use case highlighted the cumbersome task of converting an ASCII file to a grid for analysis, via (ASCII2NC w/ Python Embedding) --> (Point2Grid) --> (GridStat). The ASCII2NC tool creates netCDF files each time it runs, but since these files are immediately passed into Point2Grid, they only take up disk space and are unwanted by the user.

The desire is for the Point2Grid tool to no longer require a file input when it is a tool called in a series of tools (as described above). Instead, Point2Grid should be able to utilize a file *or* point data from a memory-read list which the user provides via Python embedding.

### Acceptance Testing ###
An ASCII file of any amount of point data will suffice for testing. @j-opatz can provide an example file and companion Python script if required.
The successful resolution of this issue will be Point2Grid being able to read in point data from memory.

### Time Estimate ###
*Need input from engineer*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
2788881 (do not charge as of 16Dec21)
Instead split 2792541, 2702691, 2799991, 2700042, 

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

  - Added met/src/libcode/vx_pointdata_python
  - Added two python scripts to met/scripts/python (met_point_obs.py & read_met_point_obs.py: reaing MET point observation NetCDF by python)
  - Redesign and implement the class structure at met/src/libcode/vx_nc_obs
    - Rename NcHeaderData to MetPointHeader
    - Moved many APIs from NcPointObsData to MetPointObsData (base class, obs data only))
    - Moved many APIs from MetNcPointObs to MetPointData (header & obs)
  - Added pyobject_as_bool to met/src/libcode/vx_python3_utils
  - Support python embedding for 4 tools
  - Added 4 unittests (NetCDF input is changed to python embedding, so the same output should be generated)
  - Added documentations

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

  - Run unittest and make sure the outputs are not changed
  - Run unittest and compare new outputs (NetCDF input & python embedding)
    - <unit_test_output>/python/pb2nc_TMP.nc VS. <unit_test_output>/point2grid/pb2nc_TMP.nc
    - <unit_test_output>/python/nam_and_ndas.20120409.t12z.prepbufr_CONFIG.ps VS. <unit_test_output>/plot_point_obs/nam_and_ndas.20120409.t12z.prepbufr_CONFIG.ps
    - <unit_test_output>/python/point_stat_GRIB1_NAM_GDAS_WINDS_120000L_20120409_120000V.stat VS. <unit_test_output>/python/point_stat_GRIB1_NAM_GDAS_WINDS_120000L_20120409_120000V.stat
    - <unit_test_output>/python/ensemble_stat VS. <unit_test_output>/ensemble_stat/

The outputs are available at /d1/personal/hsoh/git/pull_request/MET_feature_1844_python_embedding/unit_test_output/

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

  - run a full unit test
  - Just change <netcdf_input> to ''PYTHON_NUMPY=MET_BASE/python/read_met_point_obs.py <netcdf_input>' for 4 tools

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

  - More  outputs by new unit tests

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
Running a full regression test in kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta5/feature_1844 reveals unexpected differences. Specifically in the files listed below:

```
egrep -i "ERROR:|file1:" test_regression.log | egrep -B 2 ERROR: | grep ensemble | grep file1
file1: MET-feature_1844_python_embedding/test_output/climatology/ensemble_stat_NCEP_1.0DEG_20120410_120000V_ecnt.txt
file1: MET-feature_1844_python_embedding/test_output/climatology/ensemble_stat_NCEP_1.0DEG_20120410_120000V_orank.nc
file1: MET-feature_1844_python_embedding/test_output/climatology/ensemble_stat_NCEP_1.0DEG_20120410_120000V_orank.txt
file1: MET-feature_1844_python_embedding/test_output/climatology/ensemble_stat_NCEP_1.0DEG_20120410_120000V.stat
file1: MET-feature_1844_python_embedding/test_output/climatology/ensemble_stat_ONE_CDF_BIN_20120410_120000V_ecnt.txt
file1: MET-feature_1844_python_embedding/test_output/climatology/ensemble_stat_ONE_CDF_BIN_20120410_120000V_ens.nc
file1: MET-feature_1844_python_embedding/test_output/climatology/ensemble_stat_ONE_CDF_BIN_20120410_120000V.stat
```

These differences require further investigation. No explanation for why they should differ is listed in the pull request.

Since we're otherwise ready to do the beta5 release, I recommend we do the following:
- Proceed with the beta5 release on 1/14/22.
- Move issue MET#1884 and this PR MET#2010 over to the beta6 project.
- After completing the beta5 release, merge the latest from develop into this feature branch. Also, update the develop-ref version to get past of lots of existing diffs in the output.
- Rerun the full regression test to compare the update version of this feature branch to the newly updated develop-ref.
- That should allow us to see the real diffs to investigate rather than wasting time sifting through lots of other diffs.

**Comment by JohnHalleyGotway** [comment]
After the met-10.1.0-beta5 release, I updated develop-ref to get past diffs from many recent changes. On 1/18/22, I merged the latest from develop into this feature branch, feature_1844_python_embedding, and initiated a regression test on kiowa in:
   /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta6/feature_1844

Once the regression test completes, I'll post the list of diffs here.

**Comment by hsoh-u** [comment]
I merged the latest develop branch into the feature branch and have the same difference.s I will take a look

OBS_THRESH COV_THRESH ALPHA LINE_TYPE **TOTAL** N_ENS CRPS    CRPSS     IGN      ME        RMSE    SPREAD  ME_OERR RMSE_OERR SPREAD_OER
OBS_THRESH COV_THRESH ALPHA LINE_TYPE **TOTAL** N_ENS CRPS    CRPSS     IGN      ME        RMSE    SPREAD  ME_OERR RMSE_OERR SPREAD_OE
       NA         NA         NA    ECNT        **361**     5 2.15778  0.23127  42.96489  0.024977 3.16292 1.03873      NA        NA
       NA         NA         NA    ECNT        **253**     5 2.22308  0.2312   39.93187  0.11707  3.22139 1.03314      NA        NA

**Comment by hsoh-u** [comment]
The differences at ensemble_stat was fixed and I got the same result.

**Comment by JohnHalleyGotway** [comment]
Sorry for the delay on this @hsoh-u. I'm going to merge develop into this feature branch and rerun a regression test to confirm. Thanks!

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes.

I ran a full regression test vs develop in kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta6/feature_1844 and confirmed that only diffs are the addition of new output files. I skimmed through the code changes and didn't see any obvious problems. Thanks for adding more tests to unit_python.xml to demonstrate this functionality!

**Pull request merged**
