### PR TITLE
Feature #2924 parse_config

### LINKED ISSUE #2924: Enhance MET to support separate climatology datasets for both the forecast and observation inputs
## Describe the Enhancement ##
The `climo_mean` and `climo_stdev` configuration file options define climatology input files for the MET tools. As of MET version 11.1.0, they are parsed from the top-level configuration file context, meaning that they can only be defined once. So when computing anomaly statistics, the same climo value is subtracted from both the forecast and observation data.

This issue is to enhance MET to support separate climatology inputs for the forecast and observation datasets, as discussed during the NOAA METplus User Telecon on [June 24, 2024](https://docs.google.com/document/d/1psRccehlxC7KBgl3q95BMU1xYrwRA_L5c4bEkv5pWyc/edit) and requested previously in this GitHub [issue comment](https://github.com/dtcenter/MET/issues/2308#issuecomment-1494736496) for MET#2308.

This work requires the following changes:
1. @j-opatz, create at least one METplus use case that demonstrates the use of separate forecast and observation climatologies. The input data for this use case will help drive development.
2. Update the MET tools to parse the existing `climo_mean` and `climo_stdev` config options separately within the forecast and observation dictionaries. Note that we'll need a METplus issue to update the wrappers accordingly to make this configurable via METplus. This impacts 5 MET tools: Point-Stat, Grid-Stat, Ensemble-Stat, Series-Analysis. Note that they are also present in Gen-Ens-Prod, but that tool does NOT process observation data.
3. Update the internal MET library to keep track of forecast and observation climatology data separately. What should happen if one is specified but not the other? What constitutes a warning? What constitutes an error?
4. Update the MPR and ORANK output line types. They currently contain columns for `CLIMO_MEAN`, `CLIMO_STDEV`, and `CLIMO_CDF` (only in MPR). How should these change? Assume that we need extra columns to report the forecast climo values?
5. Update Stat-Analysis to parse the updated MPR and ORANK line types and use that climo data in its computations.

Additional questions:
- As described [here](https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#climo-stdev), the `climo_stdev` data is used to define climatology-based thresholds (e.g. >CDP75) and to apply binned climatology logic.  Do we need the flexibility to use the forecast climatology data in a similar way? Or do we really only need to define the forecast climatology mean so that it can be subtracted from forecast value when computing anomaly statistics?

Stages of development:
- [x] Update the MPR and ORANK output line types to just write duplicate existing climo values, update the header tables and MPR/ORANK documentation tables.
- [x] Update Stat-Analysis to parse the updated line types and just set the existing climo values to the same thing twice.
- [x] Update PairDataPoint class to process separate fcst and obs climo data.
- [x] Restructure VxPairDataPoint and VxPairDataEnsemble to inherit from a common VxPairBase class (just like PairDataPoint and PairDataEnsemble inherit from PairBase).

### Time Estimate ###
7 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2700044

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] @j-opatz, please add a new METplus use case to demonstrate this functionality.
- [x] dtcenter/METplus#2622 to update the METplus wrappers to handle the config file changes.
- [x] dtcenter/METdataio#320 to update the schema to handle the MPR and ORANK line type changes.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Expected Differences ##

This pull request changes the logic for how the `climo_mean` and `climo_stdev` dictionaries are parsed. These dictionaries consist of several entries (file_name, field, regrid, time_interp_method, day_interval, hour_interval). Currently all of these entries must be defined within the same dictionary *at the same config file context level*.

This pull request modifies the logic so that each entry is parsed separately. So while the `field` information may be parsed from config file context `fcst.climo_mean.field`, if `fcst.climo_mean.day_interval` is not defined, the default value in `climo_mean.day_interval` will be used instead.

This change simplifies the logic for the METplus wrappers. Instead of needing to override *ALL climo settings*, it now only needs to override the ones explicitly set in the METplus configuration file. And if left unspecified, the default values defined in the default MET configuration file for each tool will be used instead.

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Please note that I added a `DEBUG(5)` log message to report the criteria used when searching for climatology data. I reran the `xml/unit_climatology_mixed.xml` test several times manually, increasing the verbosity level to 5, writing to a log file, and manually modifying the `climo_mean` and `climo_stdev` settings in `GridStatConfig_climo_FCST_NCEP_1.0DEG_OBS_WMO_1.5DEG` and confirming the expected changes appear in that log message.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please find this code compiled by the `met_test` user in `seneca:/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2924_parse_config`. Recommend testing in a similar way as described above:
```
runas met_test
cd /d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2924_parse_config/internal/test_unit
testenv # to set env vars
./run_unit_climatology_mixed.sh
grep "Searching" run_unit.log
# Manually modify config/GridStatConfig_climo_FCST_NCEP_1.0DEG_OBS_WMO_1.5DEG
# Re-run the script above, grep for "Searching" and confirm the log messages match your config changes
```
- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**
None needed.

- [x] Do these changes include sufficient testing updates? **[No]**
None needed.

- [x] Will this PR result in changes to the MET test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Will this PR result in changes to existing METplus Use Cases? **[No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.

- [ ] Do these changes introduce new SonarQube findings? **[TBD]**</br>
If **yes**, please describe:

- [x] Please complete this pull request review by **[Monday, 9/9/24]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
Converting this PR to a draft to investigate unexpected differences flagged by the GHA testing workflow.

**Review by j-opatz — DISMISSED** [review]
I've reviewed the changed files, as well as performed the tests indicated in the PR. I confirmed that the various settings of climo_mean and climo_stdev libraries are now pulled independently, ignoring the levels at which the other settings appear. This logic should now allow users to take advantage of the new read-in abilities for climatology while removing the requirement to adjust all configuration files to a certain style (i.e. the climo dictionaries are moved to the fcst and obs dictionaries).

**Review by georgemccabe — CHANGES_REQUESTED** [review]
I'm getting some errors that I didn't expect when running your tests after modifying the config file. The changes below are in seneca:/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2924_parse_config/internal/test_unit/config/GridStatConfig_climo_FCST_NCEP_1.0DEG_OBS_WMO_1.5DEG

I would expect to be able to set fcst.climo_mean.regrid.method without any of the other fcst.climo_mean.regrid values. If I set:
```
regrid = {
	method = UPPER_LEFT;
      }
```
I get:

> ERROR  : Dictionary::lookup_int() -> lookup failed for name "width"

If I add, width:
```
      regrid = {
	method = UPPER_LEFT;
        width      = 3;
      }
```
I get:

> ERROR  : met_regrid() -> bad interpolation method ... UPPER_LEFT

but I see UPPER_LEFT as a valid [regrid.method in the documentation](https://met.readthedocs.io/en/develop/Users_Guide/config_options.html#regrid).

**Comment by JohnHalleyGotway** [comment]
Thanks for the feedback @georgemccabe.

I did update the logic in `vx_regrid.cc` to add support for the 4 corner point regridding methods. Thanks for catching that. The fix is easy.

I do understand why you're getting the other error based on the current set of changes. While I had updated the logic for parsing the `climo_mean` and `climo_stdev` dictionaries, I had not done so for the *child* dictionaries, like `regrid`. However, I worked on a way to support the behavior you expected, and we'll see how it all works in [the tests for this PR](https://github.com/dtcenter/MET/actions/runs/10835361722).

**Comment by JohnHalleyGotway** [comment]
@georgemccabe thanks for your review. I've finished addressing the issues you've raised and re-requested your review on this PR. I'd like to point you to:
1. This [GHA Testing Workflow](https://github.com/dtcenter/MET/actions/runs/10852552727) ran without error and produced no differences in the results.
2. I recompiled the code with these updates in `seneca:/d1/projects/MET/MET_pull_requests/met-12.0.0/beta6/MET-feature_2924_parse_config` for your further testing.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe OK I pushed more changes to this `feature_2924_parse_config` branch and recompiled on seneca. Please take a look and see if the behavior matches what you expect. Note that I did modify a lot of log messages so that whenever regridding occurs, it now tells you what method is being used, like this:
```
DEBUG 2: Regridding 19590410_000000 forecast climatology standard deviation field TMP/P500 to the verification grid using UPPER_RIGHT(1).
```

**Review by georgemccabe — APPROVED** [review]
I reviewed the test log after more changes were made and everything looks good. Thanks for iterating on this!

**Comment by JohnHalleyGotway** [comment]
Thanks @georgemccabe and @j-opatz for the feedback on this PR. I'll proceed with merging and will monitor the downstream METplus Use Case runs to see if any output unexpectedly changes.

**Pull request merged**
