### PR TITLE
Feature 2673 sonarqube beta6 vector dictionary

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

Reduced code smells on python code
Used vector instead of new statements.
One bug was identified as a new bug at `src/tools/core/mode/mode_exec.cc`.  I will take a look

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Unittest with the same outputs

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

N/A

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[No]**

- [x] Will this PR result in changes to the MET test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Will this PR result in changes to existing METplus Use Cases? **[No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:

One bug was identified as a new bug at `src/tools/core/mode/mode_exec.cc`.

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
I see that this [testing workflow](https://github.com/dtcenter/MET/actions/runs/11335661415) run failed. Please fix those failures and re-request my review.

**Comment by hsoh-u** [comment]
I rolled back the changes (pointer to vector) at src/tools/core/mode/mode_exec.cc to avoid introducing a new bug. Looks like unittest is not done.

**Review by JohnHalleyGotway — DISMISSED** [review]
I approve of these changes. I see that the GHA testing workflow flagged no differences and that the total number of SonarQube findings are reduced from 18,476 to 18,331.

I do note that the bug in `src/libcode/vx_python3_utils/wchar_argv.cc` remains, and we'll need to fix that prior to the MET-12.0.0 release in December, 2024. But these changes do reduce the overall number of code smells as intended.

**Comment by hsoh-u** [comment]
Please review again.
- There were code conflicts at src/libcode/vx_python3_utils/wchar_argv.cc. It's resolved. 
- 6 files are missing at point_weight.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes.

I see that the SonarQube code smells are further reduced to 18,323.

**Pull request merged**
