### PR TITLE
Feature #2279 point_weight_flag

### LINKED ISSUE #2279: Add support for new point_weight_flag to the Point-Stat and Ensemble-Stat tools
## Describe the New Feature ##
The MET Grid-Stat tool supports a configuration option named [grid_weight_flag](https://met.readthedocs.io/en/develop/Users_Guide/config_options.html?highlight=grid_weight_flag#grid-weight-flag) to define weights for computing statistics aggregated over multiple grid points. The grid weighting is based on the area each grid point represents, giving larger weight to grid boxes with larger areas.

This task is to develop a method for weighting the aggregation of point observations. And the same basic motivation applies, wanting to avoid overemphasizing areas with dense observations, and underemphasizing areas with sparse observations.

Consider also whether `point_weight_flag` should be added to Stat-Analysis jobs when aggregating MPR lines to compute partial sums, contingency tables, and statistics.

This request originally arose when aggregating SEEPS for individual stations into a spatial summary. The UK Met Office defines weights for that aggregation based on the spatial density of those stations. However, those weights are pre-defined and static since the stations they use are consistent run-to-run.

Recommend that when implementing this in MET, the weights *NOT* be static, in general. Instead, dynamically compute them for each verification task based on the location of the observations being processed.. The number and location of point observations can change dramatically run-to-run based on the masking region, variable, and data source. That being said, re-defining them in each run would likely be slower. Recommend that when specifying a `mask.sid` list of station id's we provide an option to define a fixed station weight.

The tasks for this issue include:
- Collaborating with @RachelNorth and @mpm-meto to clarify the algorithm for defining these weights.
- Add `point_weight_flag` configuration option for each verification task in Point-Stat and Ensemble-Stat with a default value of `NONE`, meaning apply a weight of 1 to all points.
- Support setting `point_weight_flag` equal to `DENSITY` to define the weights on the fly based on station location.
- When `mask.sid` is set to a file and station names are read from that file, add an option for a raw weight to be specified for that station (perhaps `SID(weight)` with a numeric weight?). When aggregating across multiple stations, note that the *true weight* should be computed as the *raw station weight* divided by the sum of the weights of all points. 
- Set the existing weights in the PairDataPoint and PairDataEnsemble classes and ensure that those weights are used correctly in the computation of statistics.
- In particular, ensure that the these weights are used in the aggregation of SEEPS_MPR data to compute the aggregated SEEPS data.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
1 week.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split between MetOffice and NOAA R2O keys.

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Need a METplus issue to handle configuring the new `point_weight_flag` option.
- [ ] If changes to any output line types are made, would need a METdataio issue to handle those changes.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**</br>
If **yes**, please describe:</br>
Adds `point_weight_flag` config option for Point-Stat and Ensemble-Stat.

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Manually tested point_stat and ensemble_stat while developing the new unit tests in `unit_point_weight.xml`.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
- @j-opatz:
  - Please review code changes.
  - Please review documentation updates:
    - Updates to the [mask.sid](https://metplus--2993.org.readthedocs.build/projects/met/en/2993/Users_Guide/config_options.html#mask) details.
    - [point_weight_flag](https://metplus--2993.org.readthedocs.build/projects/met/en/2993/Users_Guide/config_options.html#point-weight-flag) details.
    - [Point-Stat configuration](https://metplus--2993.org.readthedocs.build/projects/met/en/2993/Users_Guide/point-stat.html#point-stat-configuration-file)
    - [Ensemble-Stat configuration](https://metplus--2993.org.readthedocs.build/projects/met/en/2993/Users_Guide/ensemble-stat.html#ensemble-stat-configuration-file) 
  - Please review the configuration and output of new unit tests in `unit_point_weight.xml`. Recommend diff-ing the output from the "NO_WEIGHT" tests with the weighted outputs to see the impact. Note that for these tests, I chose to weight the station ID's using the elevation of the station. I realize this is not very scientifically useful but was easy to do and to understand.
- @georgemccabe I've also requested your review to coordinate on the needed METplus updates. Please review any aspects of the PR you see fit.   

The ultimate goal is to support dynamically computed options for point density and/or Voroni tesselations, described in #2661.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the MET test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
Adds new output in a new `point_weight` output directory which is analogous to the existing `grid_weight` directory.
No diffs, other than those new files, are expected.

- [x] Will this PR result in changes to existing METplus Use Cases? **[No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:
Overall code smells are reduced from 18,489 to 18,476, and @hsoh-u is already working on that one bug that remains. My changes to that file reduce a handful of code smells there.

- [x] Please complete this pull request review by **[Oct 16, 2024]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by georgemccabe** [comment]
I created issue dtcenter/METplus#2727 to add support for setting point_weight_flag in PointStat and EnsembleStat wrappers.

**Review by j-opatz — DISMISSED** [review]
Reviewed the documentation and found good discussion of the new features for the point weighting option. 

All of the code changes seem to be in order and configuration files that were impacted by the new feature have been updated accordingly. 

New tests created for the point weighting feature produced expected differences, and they were compared to the non-weighting options for correctness. New tests also contain examples of the point weighting options by file name; we should keep an eye out for an opportunity to introduce a use case that demonstrates this capability.

**Comment by JohnHalleyGotway** [comment]
Pushed new changes moving the `MaskSID` class out of the `vx_config` library and into `mask_sid.h` and `mask_sid.cc` in the `vx_util` library. This is also where `mask_poly.h` and `mask_sid.cc` live. Note that this was needed because the members were not being properly initialized. This change should fix that.

Note that if `point_weight_flag = TRUE` but `mask.sid` provides a list of station id's without any weights defined, we want a warning message printed, like this:
```
DEBUG 3: Processing station ID mask: /d1/personal/johnhg/MET/MET_development/MET-feature_2279_point_weight_flag/internal/test_unit/config/SID_CONUS_ADPUPA.txt
DEBUG 4: parse_sid_mask() -> parsing station ID masking file "/d1/personal/johnhg/MET/MET_development/MET-feature_2279_point_weight_flag/internal/test_unit/config/SID_CONUS_ADPUPA.txt"
DEBUG 4: parse_sid_mask() -> parsed 97 station ID's for the "SID_CONUS_ADPUPA" mask from file "/d1/personal/johnhg/MET/MET_development/MET-feature_2279_point_weight_flag/internal/test_unit/config/SID_CONUS_ADPUPA.txt"
DEBUG 2: Processing geography data.
...
DEBUG 4: Applying point weights for the "SID_CONUS_ADPUPA" station ID masking region.
WARNING: 
WARNING: PairBase::set_point_weight() -> station ID point weighting requested but no weights were defined in the "SID_CONUS_ADPUPA" station ID mask. Using default weights of 1.
WARNING: 
```

**Comment by JohnHalleyGotway** [comment]
I reviewed the results of the GHA tests after making the changes described above and see that the tests all run, produce the same set of new output files, and the overall number of SonarQube code smells remain unchanged.

Proceeding with merging this PR now to potentially enable us to create the beta6 release tomorrow.

**Pull request merged**
