### PR TITLE
Add user execute permissions to compile script - develop

### PR DESCRIPTION
**Pull request by georgemccabe**
This allows the compile script to run without having to change the file permissions first.

If desired I can create a PR for main_v11.1 and update the instructions on the [MET Download page](https://dtcenter.org/community-code/model-evaluation-tools-met/download) to remove the chmod command that is no longer necessary.

## Expected Differences ##

- [X] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>

- [X] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Ran compile script from cloned repo and confirmed it can be executed without changing permissions.

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Both reviewers: Consider any issues this change could create.

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[N/A]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>

- [X] Please complete this pull request review by **11/20/2023**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Review the source issue metadata (required labels, projects, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected. (No issue created)
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by JohnHalleyGotway — APPROVED** [review]
I approve. Changing permissions on this script is fine with me.

As for whether or not you modify `main_v11.1` and update the website instructions, I defer to you. If it's easier to do that now while you're thinking of it, go ahead. If you'd prefer to update those instructions after the MET-12.0.0 release (or perhaps never remember to) that's fine too.

**Comment by jprestop** [comment]
@georgemccabe I just ran the following:

> wget https://raw.githubusercontent.com/dtcenter/MET/develop/internal/scripts/installation/compile_MET_all.sh

but the permissions are not executable when I look at what I downloaded:

> -rw-rw-r--   1 jpresto  staff      29157 Nov 16 11:31 compile_MET_all.sh

**Comment by georgemccabe** [comment]
@jprestop , thanks for testing that. That is interesting that is doesn't have the same permissions when you download the file as when you obtain it from the cloned repository. I'll revert the changes on the download page. I don't think it's necessary to revert these commits, as it will save us a step if we obtain the script from GitHub. What do you think?

**Comment by jprestop** [comment]
@georgemccabe, I agree.

**Pull request merged**
