### PR TITLE
Added pcp_combine -subtract example

### LINKED ISSUE #2151: Add pcp_combine example to MET Users' Guide
## Describe the Task ##
I would like to add an example to the users' guide for the `pcp_combine -subtract` option with a list of files. I just used it for the first time and I could not get the syntax right until I found it way down in https://github.com/dtcenter/METplus/discussions/1138. All of the current examples in the users’ guide are either for `-sum` or else only have one file involved instead of a list. Something like:
`pcp_combine -subtract 2022043018_48.grib2 'name="APCP"; level="A48";' 2022043018_36.grib2 'name="APCP"; level="A36";' sample_fcst.nc`

### Time Estimate ###
15 minutes

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by mollybsmith-noaa**
## Expected Differences ##

- [ ] Do these changes introduce new tools, command line arguments, or configuration file options? No</br>
If **yes**, please describe:</br>

- [ ] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? No</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
Documentation compiles locally

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? Yes

- [ ] Do these changes include sufficient testing updates? Yes

- [ ] Will this PR result in changes to the test suite? No</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by next release.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — APPROVED** [review]
I reviewed the documentation:
https://met--2153.org.readthedocs.build/en/2153/Users_Guide/reformat_grid.html#pcp-combine-tool
This changes are great and will enhance the documentation with a "-subtract" example.  I approve this PR. Thank you for your work, @mollybsmith-noaa.  Please let me know if you would like me to squash and merge (not sure if you have permission or not) and if you would like me to delete the branch.

**Comment by jprestop** [comment]
I updated the PR with a Project and Milestone and linked the issue to the PR.

**Comment by mollybsmith-noaa** [comment]
I don't have permissions to do the merge, so go ahead and feel free to delete my branch. Thanks!

**Comment by jprestop** [comment]
Thanks, @mollybsmith-noaa.  Will do!

**Comment by jprestop** [comment]
@mollybsmith-noaa, I didn't have the option to delete your branch.  Perhaps that is because it was a fork?  I will leave it to you to delete your branch.

**Comment by mollybsmith-noaa** [comment]
Sounds good, the branch has now been deleted.

**Pull request merged**
