### PR TITLE
Feature #2068 ioda2nc v2.0

### LINKED ISSUE #2042: Enhance MET to handle NC strings when processing CF-Compliant NetCDF files.
## Describe the Enhancement ##
This enhancement request arose via GitHub discussions:
https://github.com/dtcenter/METplus/discussions/1416

MET versions 10.0.0 and 10.1.0 are not able to read CF-compliant NetCDF files from:
https://www.nohrsc.noaa.gov/snowfall_v2/

Attempting to plot this data with plot_data_plane results in this error:
```
plot_data_plane sfav2_CONUS_24h_2022020718.nc plot.ps 'name="Data"; level="(*,*)"; file_type=NETCDF_NCCF;'
...
ERROR  : 
ERROR  : NcCfFile::get_grid_from_grid_mapping() -> Cannot extract grid mapping variable ((nul)) from netCDF file.
ERROR  : 
```

The underlying problem is that the variable attributes are specified as NetCDF strings instead of character arrays. This task to enhance MET's vx_data2d_nccf library (or vx_nc_util) to handle the use of these strings.

For example, the "string" in front of units and stardard_name prevents MET from parsing these attributes:
```
	double lat(lat) ;
		string lat:long_name = "latitude" ;
		string lat:units = "degrees_north" ;
		string lat:standard_name = "latitude" ;
		lat:resolution = 0.04 ;
		lat:origin_offset = 0.02 ;
		string lat:bounds = "lat_bounds" ;
```

To test, I used ncdump/ncgen to strip out the "string" settings and re-ran plot_data_plane:
[sfav2_CONUS_6h_2022020718.nc.gz](https://github.com/dtcenter/MET/files/8026777/sfav2_CONUS_6h_2022020718.nc.gz)
```
ncdump sfav2_CONUS_6h_2022020718.nc | sed 's/string //g' > sfav2_CONUS_6h_2022020718.ncdump
ncgen -o sfav2_CONUS_6h_2022020718-char.nc sfav2_CONUS_6h_2022020718.ncdump
plot_data_plane sfav2_CONUS_6h_2022020718-char.nc plot.ps 'name="Data"; level="(*,*)";'
```

Creates this plot:
Screen Shot 2022-02-08 at 12 20 04 PM

While I see that the "Data" variable does include some timing information, it is not encoded in a CF-compliant way. If you have any control over the creation of this data, I'd recommend following the conventions for the "[Time Coordinate](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#time-coordinate)".

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2771021

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### LINKED ISSUE #2068: Enhance IODA2NC to support IODA v2.0 format
## Describe the Enhancement ##
Rob from the Met Office received a sample IODA file from their DA group and the headers is very different from the currently supported format.  Will M. took a look at it and confirmed the header is consistent with his understanding of the IODA v2.0 format.  He is going to reach out to JEDI developers to determine if the format is set.  If it is, then it would be good to add support for this format to IODA2NC.  Here is the sample header that Rob sent.  We will still need to get a sample file, but the file Rob had was very large and not conducive for testing.

Below is the header info which I got from running ncdump -h on the file I was given to look at:  (Satwind data)
```
netcdf jopa_satwind_20210701T1200Z_out_0000 {
dimensions:
               nlocs = UNLIMITED ; // (2815062 currently)
variables:
               int nlocs(nlocs) ;
                              nlocs:suggested_chunk_dim = 10000LL ;
// global attributes:
                              string :_ioda_layout = "ObsGroup" ;
                              :_ioda_layout_version = 0 ;
group: DerivedObsError {
  variables:
               float eastward_wind(nlocs) ;
                              eastward_wind:_FillValue = -3.368795e+38f ;
               float northward_wind(nlocs) ;
                              northward_wind:_FillValue = -3.368795e+38f ;
  } // group DerivedObsError

group: DerivedObsValue {
  variables:
               float eastward_wind(nlocs) ;
                              eastward_wind:_FillValue = -3.368795e+38f ;
               float northward_wind(nlocs) ;
                              northward_wind:_FillValue = -3.368795e+38f ;
  } // group DerivedObsValue

group: Diag {
  variables:
               string satwind_id(nlocs) ;
                              string satwind_id:_FillValue = "*** MISSING ***" ;
  } // group Diag

group: EffectiveError {
  variables:
               float eastward_wind(nlocs) ;
                              eastward_wind:_FillValue = -3.368795e+38f ;
               float northward_wind(nlocs) ;
                              northward_wind:_FillValue = -3.368795e+38f ;
  } // group EffectiveError

group: EffectiveQC {
  variables:
               int eastward_wind(nlocs) ;
                              eastward_wind:_FillValue = -2147483643 ;
               int northward_wind(nlocs) ;
                              northward_wind:_FillValue = -2147483643 ;
  } // group EffectiveQC
 
group: GrossErrorProbability {
  variables:
               float eastward_wind(nlocs) ;
                              eastward_wind:_FillValue = -3.368795e+38f ;
               float northward_wind(nlocs) ;
                              northward_wind:_FillValue = -3.368795e+38f ;
  } // group GrossErrorProbability
 
group: MetaData {
  variables:
               float PGE_u_over_v(nlocs) ;
                              PGE_u_over_v:_FillValue = -3.368795e+38f ;
               float QI_common(nlocs) ;
                              QI_common:_FillValue = -3.368795e+38f ;
               float QI_estimated_error(nlocs) ;
                              QI_estimated_error:_FillValue = -3.368795e+38f ;
               float QI_recursive_filter_function(nlocs) ;
                              QI_recursive_filter_function:_FillValue = -3.368795e+38f ;
               float QI_weighted_mixture_exc_forecast_comparison(nlocs) ;
                              QI_weighted_mixture_exc_forecast_comparison:_FillValue = -3.368795e+38f ;
               float QI_with_forecast(nlocs) ;
                              QI_with_forecast:_FillValue = -3.368795e+38f ;
               float QI_without_forecast(nlocs) ;
                              QI_without_forecast:_FillValue = -3.368795e+38f ;
               float air_pressure(nlocs) ;
                              air_pressure:_FillValue = -3.368795e+38f ;
               float air_pressure_original(nlocs) ;
                              air_pressure_original:_FillValue = -3.368795e+38f ;
               int64 dateTime(nlocs) ;
                              dateTime:_FillValue = -9223372036854775801LL ;
                              string dateTime:units = "seconds since 1970-01-01T00:00:00Z" ;
               float latitude(nlocs) ;
                              latitude:_FillValue = -3.368795e+38f ;
               float longitude(nlocs) ;
                              longitude:_FillValue = -3.368795e+38f ;
               int originating_centre(nlocs) ;
                              originating_centre:_FillValue = -2147483643 ;
               int originating_subcentre(nlocs) ;
                              originating_subcentre:_FillValue = -2147483643 ;
               float percent_confidence_1(nlocs) ;
                              percent_confidence_1:_FillValue = -3.368795e+38f ;
               float percent_confidence_2(nlocs) ;
                              percent_confidence_2:_FillValue = -3.368795e+38f ;
               float percent_confidence_3(nlocs) ;
                              percent_confidence_3:_FillValue = -3.368795e+38f ;
               float percent_confidence_4(nlocs) ;
                              percent_confidence_4:_FillValue = -3.368795e+38f ;
               int priority(nlocs) ;
                              priority:_FillValue = -2147483643 ;
               float priority_numerator(nlocs) ;
                              priority_numerator:_FillValue = -3.368795e+38f ;
               int64 receiptdateTime(nlocs) ;
                              receiptdateTime:_FillValue = -9223372036854775801LL ;
                              string receiptdateTime:units = "seconds since 1970-01-01T00:00:00Z" ;
               int satellite_identifier(nlocs) ;
                              satellite_identifier:_FillValue = -2147483643 ;
               string satwind_id(nlocs) ;
                              string satwind_id:_FillValue = "*** MISSING ***" ;
               float sensor_central_frequency(nlocs) ;
                              sensor_central_frequency:_FillValue = -3.368795e+38f ;
               float sensor_zenith_angle(nlocs) ;
                              sensor_zenith_angle:_FillValue = -3.368795e+38f ;
               float total_observation_error(nlocs) ;
                              total_observation_error:_FillValue = -3.368795e+38f ;
               int wind_computation_method(nlocs) ;
                              wind_computation_method:_FillValue = -2147483643 ;
               int wind_generating_application_1(nlocs) ;
                              wind_generating_application_1:_FillValue = -2147483643 ;
               int wind_generating_application_2(nlocs) ;
                              wind_generating_application_2:_FillValue = -2147483643 ;
               int wind_generating_application_3(nlocs) ;
                              wind_generating_application_3:_FillValue = -2147483643 ;
               int wind_generating_application_4(nlocs) ;
                              wind_generating_application_4:_FillValue = -2147483643 ;
  } // group MetaData

group: MetaDataError {
  variables:
               float air_pressure(nlocs) ;
                              air_pressure:_FillValue = -3.368795e+38f ;
  } // group MetaDataError

group: ObsBias {
  variables:
               float eastward_wind(nlocs) ;
                              eastward_wind:_FillValue = -3.368795e+38f ;
               float northward_wind(nlocs) ;
                              northward_wind:_FillValue = -3.368795e+38f ;
  } // group ObsBias

group: ObsValue {
  variables:
               float wind_from_direction(nlocs) ;
                              wind_from_direction:_FillValue = -3.368795e+38f ;
               float wind_speed(nlocs) ;
                              wind_speed:_FillValue = -3.368795e+38f ;
  } // group ObsValue

group: QCFlags {
  variables:
               int eastward_wind(nlocs) ;
                              eastward_wind:_FillValue = -2147483643 ;
               int northward_wind(nlocs) ;
                              northward_wind:_FillValue = -2147483643 ;
  } // group QCFlags

group: hofx {
  variables:
               float eastward_wind(nlocs) ;
                              eastward_wind:_FillValue = -3.368795e+38f ;
               float northward_wind(nlocs) ;
                              northward_wind:_FillValue = -3.368795e+38f ;
  } // group hofx
}
```

This issue is related to [METplus issue #1453](https://github.com/dtcenter/METplus/issues/1453)

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

Format v2 is support
- Group is introduced and variables are grouped
- Different variable name structure (separated the group name)
- Different core dimensions by using string data type
  - Only one global dimension (nlocs)
- Two different group names for QC: PreQC and QCFlags
- string data type is used for attributes and the variable data
- different data types for datatime variable: int64, character array, and string type
- different data types for message type and station id : character array and string type
- different name for datetime: datetime or dateTime: make this configurable
- Different QC variable names because of derived obs data (wind data VS u/v component) - configurable

Two input test file are added to mohawk for unit test (path at seneca):
- /d1/projects/MET/MET_test_data/unit_test/obs_data/ioda/jopa_satwind_20210701T1200Z_out_0000_reduced.nc4:
- /d1/projects/MET/MET_test_data/unit_test/obs_data/ioda/2021081612_sonde_small.nc

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Two unit test are added (input IODA files)
-  /d1/projects/MET/MET_test_data/unit_test/obs_data/ioda/jopa_satwind_20210701T1200Z_out_0000_reduced.nc4:
  - the variable name for time is changed to dateTime  (was datetime)
  - data type is int64
  - the attribute is the string type
- /d1/projects/MET/MET_test_data/unit_test/obs_data/ioda/2021081612_sonde_small.nc
 - has station_elevation variable: support elevation metadata
 - station_id: string type data instead of character type

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

Added obs_to_qc_map

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

Two unit tests are addded, so two more outputs

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by hsoh-u** [comment]
Two errors on reading attributes were fixed:
- reading float data type attribute into double data type variable or vise versa
- Reading time unit - there was a garbage character on reading time units
  - Time:units = "seconds since 1970-1-1" --> "seconds since 1970-1-1e"

**Comment by JohnHalleyGotway** [comment]
FYI, I recreated the input unit test data tarfile to include the newly added input files:
   https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/develop/unit_test-all.tgz

And I'll manually re-trigger the GHA tests now.

**Comment by JohnHalleyGotway** [comment]
Manually triggered a fresh GHA run for this feature branch here:
https://github.com/dtcenter/MET/actions/runs/3346860054

Hopefully that'll get us past the issue of missing ioda2nc input file.

**Comment by JohnHalleyGotway** [comment]
Aha! I finally understand what's failing with this PR. The NetCDF library version included in Docker image used by GHA cannot handle this file. Running `ncdump` on it errors out.
```
> ls ioda
2021081612_sonde_small.nc
> docker run -it --rm -v `pwd`/ioda:/ioda dtcenter/met-base:v1.0 ncdump -h /ioda/2021081612_sonde_small.nc
ncdump: /ioda/2021081612_sonde_small.nc: NetCDF: HDF error
```
So this is an issue with the NetCDF library version.
- Docker (FAIL): With `netcdf library version 4.4.1.1 of Aug 30 2022 20:18:07`
- Seneca (PASS): On Seneca with all available NetCDF versions 4.6.3, 4.7.0, and 4.8.0.
- Mohawk (FAIL): With NetCDF version 4.3.3.1, 4.5, 
- Mohawk (PASS): With NetCDF version 4.4.1.1, 4.6.1, 4.7.0

The change here is that this NetCDF file uses the "enhanced data model" whereas all previous ones did not.

So we need likely need to recreate the met-base image WITH SUPPORT for the enhanced data model.

**Comment by JohnHalleyGotway** [comment]
I approve of these changes.

FYI, I updated METbaseimage from version 1.0 to 1.1, and for version 1.1 I added support for NetCDF groups. This [GHA testing workflow run](https://github.com/dtcenter/MET/actions/runs/3353419711/jobs/5556362224) for this feature branch now runs successfully.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve.

**Pull request merged**
