### PR TITLE
Feature 1444 AVN

### LINKED ISSUE #1444: Alert users to the renaming of AVN to GFS in MET tropical cyclone tools.
## Describe the Task ##
This minor issue arose via met-help:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96109

In the MET tropical cyclone library code, all instances of "AVN" in ATCF ID's are automatically renamed to "GFS" (e.g. AVNO is renamed to GFSO). This issue is to add log messages to alert the user to this behavior.
 
This occurs in the code here:
https://github.com/NCAR/MET/blob/0cee9fbd0b3c691fd3cf4dd1d665f5d2b0db9a37/met/src/libcode/vx_tc_util/atcf_line_base.cc#L236

Make the following changes:
(1) If the user requests in their config file, a model name that includes "AVN", print a WARNING message about the behavior.
(2) If any AVN does actually occur in the input ATCF files, print a DEBUG(1) message about this behavior. But make sure to only print that message once.
(3) Make sure this behavior is clearly documented in the user's guide.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank should do the PR review.

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
Compiled code for testing can be found on kiowa:
/d1/projects/MET/MET_pull_requests/met-9.1_beta4/feature_1444/MET-feature_1444_AVN_into_develop/met/bin

**Review by KathrynNewman — COMMENTED** [review]
Suggest explicitly stating that GFS* needs to be in the -model entry, such as:

WARNING: parse_conf_tc_model() -> Requesting tropical cyclone model name "AVNI" will yield no results since "AVN" is automatically replaced with "GFS" when reading ATCF inputs. Please use "GFS" in -model field to read/process "AVN" entries.

**Comment by JohnHalleyGotway** [comment]
Thanks Kathryn. I just updated that warning message to read as follows:
```
WARNING: parse_conf_tc_model() -> Requesting tropical cyclone model name "AVNI" will yield no results since "AVN" is automatically replaced with "GFS" when reading ATCF inputs. Please use "GFS" in the "model" entry of the configuration file to read/process "AVN" entries.
```

The "model" is set in the configuration file, not on the command line with "-model". The kiowa build is recompiling now with that change:
/d1/projects/MET/MET_pull_requests/met-9.1_beta4/feature_1444/MET-feature_1444_AVN_into_develop/met

**Review by KathrynNewman — APPROVED** [review]
Looks good.

**Pull request merged**
