### PR TITLE
Feature 1492 nc_unsigned_data_type

### LINKED ISSUE #1492: Supporting unsigned data type for the input NetCDF files
MET does not support the unsigned data types for NetCDF file. MET only supported the unsigned values by applying "_Unsigned" attribute at the signed data type. Ho-Chun reported the data type changes at GOES16 AOD daata (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96687). It's changed to the "unsigned short" and the "unsigned byte" type without "_Unsigned" attribute. The point2grid does not work with new AOD data file.

## Describe the New Feature ##
MET library should support unsigned data types (unsigned byte/short/int/int64) and point2grid should check if the the data type is signed or unsigned before reading the NetCDF variables.

### Acceptance Testing ###
point2grid should process the new GOES data file (dakota:/d3/personal/hsoh/data/RT-96687/OR_ABI-L2-AODC-M6_G16_s20202581441152_e20202581443525_c20202581445493.nc)

### Time Estimate ###
2 or 3 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [x] Select **scientist(s)** or **no scientist** required (None)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>

- [x] Will this PR result in changes to the regression test output? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

The new AOD outputs have the unsigned byte and unsigned short instead of signed byte/short with "_Unsigned" attribute. The segmentation fault happened at the NetCDF library because that the values at the data value range attributes is out of scope. This was fixed at the vx_nc_util library. In addition, the duplicated codes were reduced by using template. Some APIs which pass the argument as call by value were changed to call by reference for better performance (avoid copying argument value).

get_pinterp_grid.cc : renamed API "get_global_att_double" to "get_global_att".
met/src/libcode/vx_nc_util/nc_utils.h: changes for call by reference

The input data file is added to dakota:
     /d3/projects/MET/MET_test_data/unit_test/model_data/goes_16/OR_ABI-L2-AODC-M6_G16_s20202581441152_e20202581443525_c20202581445493.nc

New output from the Unittest:
     &OUTPUT_DIR;/point2grid/point2grid_GOES_16_AOD_TO_G212_unsigned.nc

How to test:

- run unittest with "unit_point2grid.xml"
- Or run the following command
```
./bin/point2grid \
      /d3/projects/MET/MET_test_data/unit_test/model_data/goes_16/OR_ABI-L2-AODC-M6_G16_s20202581441152_e20202581443525_c20202581445493.nc \
      G212 \
      ./point2grid_GOES_16_AOD_TO_G212_unsigned.nc \
      -field 'name="AOD";  level="(*,*)";' \
      -qc 1,2,3 -method MAX \
      -v 1
```

### CODE REVIEW

**Review by JohnHalleyGotway — COMMENTED** [review]
Howard, in the MET today, I thought you mentioned that you'd used templates for supporting all these different variable types. But I don't see any templates here. Or were you saying perhaps it would be a good idea to use templates?

I'm testing on kiowa now, compiling the code for the PR and checking to make sure the new tests run and don't break any of the existing tests.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
Howard, I ran the full set of unit tests for these changes and found that pcp_combine failed on:
```
TEST: pcp_combine_sub_P_INTERP                 - FAIL -   0.181 sec
/d1/projects/MET/MET_pull_requests/met-10.0_beta1/feature_1492/MET-feature_1492_nc_unsigned_data_type_into_develop/met/share/met/../../bin/pcp_combine \
      -subtract \
      /d1/projects/MET/MET_test_data/unit_test/model_data/p_interp/wrfout_d01_2008-08-08_12:00:00_PLEV 'name="RAINNC";level="(0,*,*)";' \
      /d1/projects/MET/MET_test_data/unit_test/model_data/p_interp/wrfout_d01_2008-08-08_06:00:00_PLEV 'name="RAINNC";level="(0,*,*)";' \
      /d1/projects/MET/MET_pull_requests/met-10.0_beta1/feature_1492/MET-feature_1492_nc_unsigned_data_type_into_develop/test_output/pcp_combine/wrfout_d01_2008-08-08_12:00:00_PLEV_APCP06.nc
DEBUG 2: Since the "-field" command line option was not used, parsing the command line arguments a list of files, each followed by a configuration string.
DEBUG 1: Reading input file: /d1/projects/MET/MET_test_data/unit_test/model_data/p_interp/wrfout_d01_2008-08-08_12:00:00_PLEV
DEBUG 1: Reading data (name="RAINNC";level="(0,*,*)";) from input file: /d1/projects/MET/MET_test_data/unit_test/model_data/p_interp/wrfout_d01_2008-08-08_12:00:00_PLEV
ERROR  : 
ERROR  : get_global_att(double) -> The data type "float" for "TRUELAT1" is not supported...
ERROR  : 

ERROR: /d1/projects/MET/MET_pull_requests/met-10.0_beta1/feature_1492/MET-feature_1492_nc_unsigned_data_type_into_develop/test/perl/unit.pl unit_pcp_combine.xml failed.

*** UNIT TESTS FAILED ***
```
Please take another look and make sure none of the existing unit tests fail with these changes.

**Comment by hsoh-u** [comment]
Added 16 template functions which begins with "_"

nc_utils.cc:66:template <typename T>
nc_utils.cc-67-bool _get_att_num_value(const NcAtt *att, T &att_val, int matching_type) {

nc_utils.cc:489:template <typename T>
nc_utils.cc-490-bool _get_nc_att_value(const NcVar *var, const ConcatString &att_name,
nc_utils.cc-491-                       T &att_val, bool exit_on_error,
nc_utils.cc-492-                       T bad_data, const char *caller_name) {

nc_utils.cc:557:template <typename T>
nc_utils.cc-558-bool _get_nc_att_value(const NcVarAtt *att, T &att_val, bool exit_on_error,
nc_utils.cc-559-                       T bad_data, const char *caller_name) {

nc_utils.cc:728:template <typename T>
nc_utils.cc-729-bool _get_global_att_value(const NcFile *nc, const ConcatString& att_name,
nc_utils.cc-730-                           T &att_val, T bad_data, bool error_out, const char *caller_name) {

nc_utils.cc:931:template <typename T>
nc_utils.cc-932-bool _get_var_att_num(const NcVar *var, const ConcatString &att_name,
nc_utils.cc-933-                      T &att_val, T bad_data) {

nc_utils.cc:1177:template <typename T>
nc_utils.cc-1178-bool _get_nc_data(NcFile *nc, const char *var_name, T *data,
nc_utils.cc-1179-                 const long *dim, const long *cur) {

nc_utils.cc:1198:template <typename T>
nc_utils.cc-1199-bool _get_nc_data(NcVar *var, T *data) {

nc_utils.cc:1229:template <typename T>
nc_utils.cc-1230-bool _get_nc_data(NcVar *var, T *data, T bad_data, const long *curs) {

nc_utils.cc:1266:template <typename T>
nc_utils.cc-1267-bool _get_nc_data(NcVar *var, T *data, T bad_data, const long dim, const long cur) {

nc_utils.cc:1317:template <typename T>
nc_utils.cc-1318-bool _get_nc_data(NcVar *var, T *data, T bad_data, const long *dims, const long *curs) {

nc_utils.cc:1385:template <typename T>
nc_utils.cc-1386-void _apply_scale_factor(float *data, const T *packed_data,
nc_utils.cc-1387-                        const int cell_count, const T fill_value,
nc_utils.cc-1388-                        T &raw_min_val, T &raw_max_val, const char *data_type,

nc_utils.cc:1668:template <typename T>
nc_utils.cc-1669-int _apply_scale_factor(double *data, const T *packed_data,
nc_utils.cc-1670-                        const int cell_count, const T fill_value,
nc_utils.cc-1671-                        T &raw_min_val, T &raw_max_val, const char *data_type,

nc_utils.cc:2167:template <typename T>
nc_utils.cc-2168-bool _put_nc_data(NcVar *var, const T data, long offset0, long offset1, long offset2) {

nc_utils.cc:2253:template <typename T>
nc_utils.cc-2254-bool _put_nc_data(NcVar *var, const T *data,    const long length, const long offset) {

nc_utils.cc:2304:template <typename T>
nc_utils.cc-2305-bool _put_nc_data(NcVar *var, const T *data , const long *lengths, const long *offsets) {

nc_utils.cc:2341:template <typename T>
nc_utils.cc-2342-bool _put_nc_data_with_dims(NcVar *var, const T *data,
nc_utils.cc-2343-                           const long len0, const long len1, const long len2) {

**Comment by hsoh-u** [comment]
The error was resolved. Tested the pcp_combine unit test and some others. Started all unit test.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
Howard, the unit tests continue to fail. Please look on kiowa in:/d1/projects/MET/MET_pull_requests/met-10.0_beta1/feature_1492/MET-feature_1492_nc_unsigned_data_type_into_develop/test/test_unit.log

```
TEST: point2grid_GOES_16_AOD_TO_G212_unsigned - FAIL -   0.223 sec
export MET_TMP_DIR='${MET_TEST_OUTPUT}'
/d1/projects/MET/MET_pull_requests/met-10.0_beta1/feature_1492/MET-feature_1492_nc_unsigned_data_type_into_develop/met/share/met/../../bin/point2grid \
      /d1/projects/MET/MET_test_data/unit_test/model_data/goes_16/OR_ABI-L2-AODC-M6_G16_s20202581441152_e20202581443525_c20202581445493.nc \
      G212 \
      /d1/projects/MET/MET_pull_requests/met-10.0_beta1/feature_1492/MET-feature_1492_nc_unsigned_data_type_into_develop/test_output/point2grid/point2grid_GOES_16_AOD_TO_G212_unsigned.nc \
      -field 'name="AOD";  level="(*,*)";' \
      -qc 1,2,3 -method MAX \
      -v 1
DEBUG 1: Reading data file: /d1/projects/MET/MET_test_data/unit_test/model_data/goes_16/OR_ABI-L2-AODC-M6_G16_s20202581441152_e20202581443525_c20202581445493.nc
ERROR  : 
ERROR  : get_nc_att(NcFile) -> can't read attribute "scene_id" from because NC is invalid.
ERROR  : 
Segmentation fault

ERROR: /d1/projects/MET/MET_pull_requests/met-10.0_beta1/feature_1492/MET-feature_1492_nc_unsigned_data_type_into_develop/test/perl/unit.pl unit_point2grid.xml failed.

*** UNIT TESTS FAILED ***
```

**Comment by hsoh-u** [comment]
It's failed because the input file was missing. I will improve the log message when working on #1493 if everything goes well.

I copied OR_ABI-L2-AODC-M6_G16_s20202581441152_e20202581443525_c20202581445493.nc into /d1/projects/MET/MET_test_data/unit_test/model_data/goes_16/

**Comment by JohnHalleyGotway** [comment]
Howard,

OK, I'm retesting now... starting with unit_point2grid.xml and logging to:
kiowa:/d1/projects/MET/MET_pull_requests/met-10.0_beta1/feature_1492/MET-feature_1492_nc_unsigned_data_type_into_develop/test/unit_test.log

John

**Review by JohnHalleyGotway — APPROVED** [review]
After adding in that missing input file, all the unit tests ran without error.

I approve this PR but recommend checking for the existence of that file instead of producing a segfault.

**Pull request merged**
