### PR TITLE
Feature 2640 ioda2nc dimension

### LINKED ISSUE #2640: Update ioda2nc to support version 3 IODA files
## Describe the Enhancement ##
[A user in the Discussions forum](https://github.com/dtcenter/METplus/discussions/2290) alerted the MET team to a new aspect of version 3 IODA files that is currently unsupported by MET. Namely, the `nlocs` variable has been replaced by `Location`. This causes an error in the current ioda2nc tool run, as library code relies on `nlocs` to pull out relevant field information.

I suggest we enhance the current ioda2nc tool to support this update to IODA files, as well as any other enhancements that may have occurred between version 2 and 3.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2792543 NOAA Base METplus

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

ioda2nc processes the IODA input with Location dimension instead of nlocs dimension.

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

/d1/personal/hsoh/git/pull_request/MET_feature_2640_ioda2nc_dimension/bin/ioda2nc /d1/personal/hsoh/data/IODA_files/avhrr_radiance_location.nc  met_avhrr_radiance_location.nc /d1/personal/hsoh/git/pull_request/MET_feature_2640_ioda2nc_dimension/share/met/config/IODA2NCConfig -v 3 -obs_var brightness_temperature

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

If you have IODAS V3 data file (with nlocs dimension), make a IODA file with Location dimension.
```
ncdump IODAV3_filename > IODAV3_filename.dump
sed -i -e "s|nlocs|Location|g" IODAV3_filename.dump
ncgen -o IODAV3_filename.Location.nc IODAV3_filename.dump
```

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[No]**

- [x] Will this PR result in changes to the test suite? **[no]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
HI @hsoh-u.  Can you please confirm that these are expected differences (from the failing test)?

```
COMPARING ioda2nc/odb_sonde_16019_all.nc
file1: /data/output/met_test_truth/ioda2nc/odb_sonde_16019_all.nc
file2: /data/output/met_test_output/ioda2nc/odb_sonde_16019_all.nc
ERROR: NetCDF headers differ:
6c6
< 	nhdr = 2 ;
---
> 	nhdr = 96 ;
8,9c8,9
< 	nhdr_typ = 1 ;
< 	nhdr_sid = 1 ;
---
> 	nhdr_typ = 23 ;
> 	nhdr_sid = 20 ;

End of script
ERROR: Differences exist in the output
Error: Process completed with exit code 1.
```

**Comment by hsoh-u** [comment]
I did not expect differences. I will take a look.

**Comment by hsoh-u** [comment]
Ready for review

**Review by jprestop — APPROVED** [review]
I do not have an IODAS V3 data file and am relying on the testing by @hsoh-u.  I have reviewed the code changes and have ensured that all tests passed.  I approve this request.

**Pull request merged**
