### PR TITLE
DELETE ME

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
Same fix as PR #2432 but for the develop branch instead. Please review them together.

### CODE REVIEW

**Comment by davidalbo** [comment]
@JohnHalleyGotway does the most recent comment from GwenChen in the issue here https://github.com/dtcenter/MET/issues/2426  
change anything as regards this pull request?

**Comment by JohnHalleyGotway** [comment]
@davidalbo, I suppose it does. I'd recommend that we stick with the smaller set of changes in #2432 for the bugfix in main_v11.0. But ideally we'd update the develop branch with the more thorough set of the buoy locations.

Options are...
1. Pull back this PR and work on the more complete fix for develop now.
2. Approve/merge this PR now, but write up a separate issue to update the buoy locations file sometime later.

I don't have time now to work on the updated buoy locations file, but perhaps you do? If you do, let's add you as an assignee to this issue and do option (1). If not, let's do option (2).

What do you think?

**Comment by JohnHalleyGotway** [comment]
Here's the plan:
1. @davidalbo proceeds with the review of PR #2432 to fix this in the main_v11.0 branch.
2. @JohnHalleyGotway converts this PR #2433 to a draft.
3. @davidalbo checks out the [bugfix_2426_develop_buoy](https://github.com/dtcenter/MET/tree/bugfix_2426_develop_buoy) branch and continues development on it. The goal is to modify the contents of `ndbc_stations.xml` using the data from [ndbc.noaa.gov/to_station.shtml](https://www.ndbc.noaa.gov/to_station.shtml), as described in this [issue comment](https://github.com/dtcenter/MET/issues/2426#issuecomment-1414451083).
Please check to see if any of the lat/lon/elevation information changes from the original and this new source.
4. Once the changes are ready @davidalbo click the "Ready for review" button on this PR.

**Comment by JohnHalleyGotway** [comment]
@davidalbo wondering if I should just close this PR? Or are you planning on using it for your set of changes for develop for this issue?

**Comment by davidalbo** [comment]
@JohnHalleyGotway  I have python already implemented and uploaded to this branch:  bugfix_2426_develop_buoy.   All that is needed is testing, which would be to run the python script, then run ascii2nc on the newer ndbc locations file that gets generated.And... replace the actual table file with the newer one if the test works.

I can do this as part of issue 2426 I guess, whatever makes sense.  I'm actually confused by what seems to be 3 issues for this. 2426 2433 2432

**Review by davidalbo — APPROVED** [review]
If I'm understanding, this pull request puts a few things into develop:
1. adds changes made by JohnHG for logging formatting.
2. Adds additional stations by hand to the ndbc_stations.xml file.
3. Adds a python script that combines station information from the two sources, but that is not yet used for anything.

We can continue working on #2426 to actually use the python or make a new issue to continue work on that.  

I approve this pull request.

**Pull request closed without merging**
