### PR TITLE
DELETE ME

### PR DESCRIPTION
**Pull request by hsoh-u**
DELETE ME

### CODE REVIEW

**Comment by hsoh-u** [comment]
input: radolan_sp.nc: with standard_parallel (spherical earth)
Plot by MET:
polar_met
Plot by other tool
polar_idv

**Comment by hsoh-u** [comment]
input: NSIDC0081_SEAICE_PS_N25km_20220723_v2.0.nc with standard_parallel (ellipsoidal earth & north pole)
Plot by MET:
polar-NSIDC_Sea_Ice_MET
Plot by other tool
polar-NSIDC_Sea_Ice_IDV
NSIDC0081_SEAICE_PS_N25km_20220723_v2 0_F16

**Comment by hsoh-u** [comment]
input: NSIDC0081_SEAICE_PS_S25km_20220723_v2.0.nc with standard_parallel (ellipsoidal earth & south pole)
Plot by MET:
polar-NSIDC_Sea_Ice_S_MET
Plot by other tool
NSIDC0081_SEAICE_PS_S25km_20220723_v2 0_F16

**Comment by JohnHalleyGotway** [comment]
@hsoh-u, @TaraJensen, and @rgbullock clearly this functionality isn't ready.

The plot that Howard notes in [this comment](https://github.com/dtcenter/MET/pull/2351#issuecomment-1320346258) above *should* have map outline data on it but does not. Here's the grid information printed to the screen:
```
DEBUG 4: Grid information:
DEBUG 4:    Projection: Stereographic
DEBUG 4:    Nx: 304
DEBUG 4:    Ny: 448
DEBUG 4:    IsNorthHemisphere: true
DEBUG 4:    Lon_orient: 45.000
DEBUG 4:    Bx: 153390.426
DEBUG 4:    By: 213347.596
DEBUG 4:    Alpha: 494875.5629
```
So the grid library code does not know where this grid lives on the earth.

I further confirmed this by attempting to regrid this data to a global lat/lon grid:
```
regrid_data_plane /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/nccf/NSIDC0081_SEAICE_PS_N25km_20220723_v2.0.nc G001 regrid.nc -field 'name="F16_ICECON"; level="(0,*,*)";'
```
The result contains no valid data, whereas it should contain data at the top of the grid.

We attempted to add support for this grid but were not successful in doing so.

@TaraJensen how do you want to proceed with regards to the beta5 release and ultimately the v11.0.0 release?

**Pull request closed without merging**
