### PR TITLE
Feature 1809 gen prob

### LINKED ISSUE #1809: Enhance TC-Gen to verify genesis probabilities from ATCF e-deck files.
## Describe the New Feature ##
[tc_gen_probabilistic_algorithm_v2.pdf](https://github.com/dtcenter/MET/files/6535036/tc_gen_probabilistic_algorithm_v2.pdf)

Please see the attached slides to illustrate 2 main changes that are required for TC-Genesis verification. This issue describes the first of those 2 enhancements. Enhance tc_gen to verify genesis probabilities from ATCF e-deck files. NHC identifies disturbances and issues 3 probability forecasts for how likely it is that disturbance will develop into a tropical storm. The probabilities cover 3 time windows, with 48, 120, or 168 hours.

@halperin-erau has provided some sample data containing these e-deck probabilities. However, as of May 2021, their format is still under development. In the existing and historical versions of these files, both the lat,lon location and valid timestamps are absent. If any of those columns are missing from the input data, tc_gen should print a warning message and ignore that input.

This task is to enhance tc_gen to parse those e-deck probabilities and use them to populate Nx2 probabilistic contingency tables. Create 1 table for each of the time windows (48, 120, and 168) but make that a user-configurable option. Write the resulting probabilistic output.

Be sure to subset output by basin, time window, and perhaps forecaster initials. Support the application of both the development and operational logic, but note that the operational logic will be used by NHC. 

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
The project for 7790901 originally ended in August, 2021. After the no-cost extension, the updated date is February 28th, 2022.

### Funding Source ###
7790901

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Recommend adding a METplus use-case to demonstrate this new functionality, assuming enough data is available to do so.

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Pull Request Testing ##

@georgemccabe we'll likely need updates the tc-gen METplus wrapper to supply the new -edeck command line option and configure the new prob_genesis_thresh option. I'd recommend holding off until dtcenter/MET#1810 is done, which will also change the inputs/configuration options.

@halperin-erau please review the config file changes and  doc updates, if possible:
   https://met.readthedocs.io/en/feature_1809_gen_prob/Users_Guide/tc-gen.html
You can try out the actual code in the docker container for the MET-10.1.0-beta4 development release, once that's ready.

- [x] Describe testing already performed for these changes:</br>
Manual testing of new functionality using sample files provided by @halperin-erau. During the beta5 development cycle, @KathrynNewman will be adding a METplus use case demonstrating this new functionality with a much larger sample of data. Recommend revisiting the existing tests in unit_tc_gen.xml and consider making them more robust once that larger dataset if available.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Review the regression test output in kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta4/feature_1809

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

Still working on the doc updates. Once they're complete I'll change this from a draft PR to one that's ready for review.
See doc updates here:
https://met.readthedocs.io/en/feature_1809_gen_prob/Users_Guide/tc-gen.html

- [x] Do these changes include sufficient testing updates? **[Yes]**

Add a new call to tc_gen in unit_tc_gen.xml.

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

Expected changes are:
In kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta4/feature_1809/test_regression.log
 - new tc_gen probabilistic output files
```
ERROR: folder MET-develop/test_output missing 6 files
    tc_gen/tc_gen_prob_genmpr.txt 
    tc_gen/tc_gen_prob_pct.txt 
    tc_gen/tc_gen_prob_pjc.txt 
    tc_gen/tc_gen_prob_prc.txt 
    tc_gen/tc_gen_prob_pstd.txt 
    tc_gen/tc_gen_prob.stat 
```
 - modification to the contents of existing GENMPR line type
```
file1: MET-feature_1809_gen_prob/test_output/tc_gen/tc_gen_2016_genmpr.txt
ERROR: compareStat() failed
--
file1: MET-feature_1809_gen_prob/test_output/tc_gen/tc_gen_2016.stat
ERROR: compareStat() failed
```

- [x] Please complete this pull request review by **[Monday 11/15/21]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by KathrynNewman — COMMENTED** [review]
Quick question on consistency before I approve: I see PROB_GENESIS for the fcst_var and obs_var in the output files, which is consistent with the genesis methodology listed in the UG (GENESIS_DEV, GENESIS_OPS, or GENESIS_PROB). But in the TCGenConfig_prob the dev and ops scoring method flags appear (which I believe is what we want). How are these differentiated?

**Comment by JohnHalleyGotway** [comment]
@KathrynNewman you are correct that these flags are listed in TCGenConfig_prob:
```
dev_method_flag = TRUE;
ops_method_flag = TRUE;
```
However, these currently have no effect on the probability of genesis verification! These is only one set of vx logic defined for this data, as described in the [Scoring Logic](https://met.readthedocs.io/en/feature_1809_gen_prob/Users_Guide/tc-gen.html#scoring-logic) section.

So we do NOT have different "development" and "operational" scoring logic. That was a detail that was a bit murky for me. Should we support 2 types of scoring logic for this input? If so, is it crystal clear to you what they should be and how they should differ?

**Comment by KathrynNewman** [comment]
I'm sorry for the stupid question, John! I was recalling that you listed both DEV and OPS in the meeting notes from 11/11, but now that I look back at the issue, I see I somehow missed the entire discussion between you and Dan on only using OPS=PROBGENESIS. This all sounds good!

**Review by KathrynNewman — APPROVED** [review]

**Comment by georgemccabe** [comment]
I created 2 METplus issues that are related to this work:
Enhance TCGen wrapper to add support for new configurations: dtcenter/METplus#1273
New Use Case: TCGen Verify Genesis Probabilities from ATCF e-deck files: dtcenter/METplus#1274

**Pull request merged**
