### PR TITLE
Feature 1943 gridstat seeps

### LINKED ISSUE #1943: Enhance Grid-Stat to compute SEEPS for gridded observations and write the SEEPS STAT line type.
## Describe the New Feature ##
The Stable Equitable Error in Probability Space (SEEPS) score is described in Rodwell et al. (2010) and was devised for evaluating quantitative precipitation forecasts against SYNOP gauge data at (but not limited to) station locations. It uses a climatology to account for local variations in rainfall which enables aggregation over otherwise heterogenous locations. Recent work (North et al., 2021) has used a gridded product for calculating the score over both land and sea areas.

This issue will act as an umbrella ticket for the implementation of the gridded score capability.

- MET #1942 added SEEPS to Point-Stat.
- MET #2269 will add it to Series-Analysis after this one is completed.

While Point-Stat writes the SEEPS and SEEPS_MPR line types, Grid-Stat should only write the SEEPS line type. However, recommend also adding support for:
```
nc_pairs_flag = {
...
    seeps = TRUE;
...
}
```
There setting the `nc_pairs_flag.seeps` setting enables some output to be written to the "_pairs.nc" file created by Grid-Stat. At a minimum, it should write the seeps value for each grid point.

Please talk to @RachelNorth to determine if any other columns from the SEEPS_MPR line type should also be written to the "_pairs.nc" NetCDF file.

We do still need to define the columns that should be included in a new SEEPS line type.
MET #1942 left the S12 through PV3 columns set as NA. Work for this issue should actually define their contents.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
Unknown

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Part of Met Office contract, ending August 2022 MET v11.

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @hsoh-u 
- [x] Select **scientist(s)** or **no scientist** required: @RachelNorth

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority** medium-to-high
- [x] Select **requestor(s)** UK Met Office

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Need METplus issue to add `output_flag.seeps` and `nc_pairs_flag.seeps` as configurable options.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
- point_stat and grid_stat
  - The SEEPS QC (by p1, Probability of being dry) is added
    - Configured by using "seeps_p1_thresh" (default  is disabled, "seeps_p1_thresh  =  NA;")
    - p1 threshold for SYNOP:  "seeps_p1_thresh = \>=0.1&&\<=0.85;"
  - The weighted SEEPS score is computed (it was averaged score)
  - The columns for SEEPS are computed (S12,  S13,  S21, S23, S31, S32, PV1, PV2, PV3, PF1, PF2, PF3)
- grid_stat
  - SEEPS line type is generated
  - The three columns of SEEPS MPR (SCORE, OBS_CAT, FCST_CAT) are added to NetCDF
  - "seeps" is added to output_flag of grid_stat configuration files
  - unit test, grid_stat_UK_SEEPS, is added
    - The climo file for grid is added to MET_TEST_INPUT/climatology_data/seeps/PPT24_seepsweights_grid.nc
  - The climo file for grid is configurable by using the environment variable MET_SEEPS_GRID_CLIMO_NAME
- point_stat
   - The density vector for point_stat is computed with density_radius 0.75 degree

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

It produces the SEESP text output. It adds SEEPS MPR score, obs_category and forecast category to NetCDF.

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

SEEPS line type is added like point_stat
Some SEEPS_MPR data is saved to NetCDF output

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Added it to unit test

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

Yes two more unit test: one for grid_stat and the other for stat_ananysisfrom [another PR, Feature #2339 stat_analysis_seeps](https://github.com/dtcenter/MET/pull/2343)  by @JohnHalleyGotway 
- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
There are still problems remaining to be fixed. I inspected the diffs flagged in this [GHA run](https://github.com/dtcenter/MET/actions/runs/3474129491).

It adds 5 new output files and modifies 3 Point-Stat output files.

Please look specifically at this file that is modified:
```
point_stat_NCMET_NAM_NDAS_SEEPS_360000L_20120410_120000V_seeps.txt
```
The SEEPS column that previously reported reasonable values between 0 and 1 are now all 0. Also the S, PF, and PV columns that were previously NA are now also 0.

**Comment by hsoh-u** [comment]
> There are still problems remaining to be fixed. I inspected the diffs flagged in this [GHA run](https://github.com/dtcenter/MET/actions/runs/3474129491).
> 
> It adds 5 new output files and modifies 3 Point-Stat output files.
> 
> Please look specifically at this file that is modified:
> 
> ```
> point_stat_NCMET_NAM_NDAS_SEEPS_360000L_20120410_120000V_seeps.txt
> ```
> 
> The SEEPS column that previously reported reasonable values between 0 and 1 are now all 0. Also the S, PF, and PV columns that were previously NA are now also 0.

I informed Rachel that our test data and my sample IDL run (lat=(10,20,30,40,50), lon=(20,40,60,80,100)) produce all 0 density_vector with density_radius 0.75. That's why all columns becomes 0 and weighed SEEPS score, too. I will change back to use averaged SEEPS score, not weighted score.

**Review by JohnHalleyGotway — COMMENTED** [review]
Inspected the diffs flagged in this [GHA run](https://github.com/dtcenter/MET/actions/runs/3482198387):

1. Adds 5 new output files:
```
ERROR: folder /data/output/met_test_truth missing 5 files
    grid_stat/grid_stat_SEEPS_000000L_20211202_000000V.stat
    grid_stat/grid_stat_SEEPS_000000L_20211202_000000V_pairs.nc
    grid_stat/grid_stat_SEEPS_000000L_20211202_000000V_seeps.txt
    stat_analysis_ps/CONFIG_POINT_STAT_filter_seeps.stat
    stat_analysis_ps/POINT_STAT_SEEPS.out
```
It modifies the data in 7 existing output files.

2. Diffs in 3 files from Point-Stat:
```
file1: /data/output/met_test_truth/point_stat/point_stat_NCMET_NAM_NDAS_SEEPS_360000L_20120410_120000V.stat
file1: /data/output/met_test_truth/point_stat/point_stat_NCMET_NAM_NDAS_SEEPS_360000L_20120410_120000V_seeps.txt
file1: /data/output/met_test_truth/point_stat/point_stat_NCMET_NAM_NDAS_SEEPS_360000L_20120410_120000V_seeps_mpr.txt
```
  - For SEEPS_MPR, the P2 column for the same point locations have changed. For example, for `71940   55.18 -118.88` P2 changes from 0.78 to 0.927. Is this expected?
  - For SEEPS, the TOTAL column generally decreases from 249 to 230. I assume that's because we're doing more filtering and is expected. The MEAN_FCST, MEAN_OBS, and SEEPS columns change, but that makes sense with a different number of points used.
  - For SEEPS, the S, PF, and PV columns remain set as a value of 0. Is this expected? If we can populate those columns in the output of Grid-Stat, why aren't they populated for Point-Stat?

3. Diffs in 4 files TC-Pairs and TC-Stat that can safely be ignored:
```
file1: /data/output/met_test_truth/tc_pairs/al092022_20220926_DIAGNOSTICS.tcst
file1: /data/output/met_test_truth/tc_pairs/al132020_CONSENSUS.tcst
file1: /data/output/met_test_truth/tc_stat/DIAGNOSTICS_filter_match_points.tcst
file1: /data/output/met_test_truth/tc_stat/DIAGNOSTICS_stat.out
```

**Comment by JohnHalleyGotway** [comment]
@hsoh-u I see the details you sent me separately via email. Sorry if I raised issues you already addressed there.

Please just confirm that all diffs I noted in my comment above are expected, and I'll approve the PR.

**Comment by hsoh-u** [comment]
> @hsoh-u I see the details you sent me separately via email. Sorry if I raised issues you already addressed there.
> 
> Please just confirm that all diffs I noted in my comment above are expected, and I'll approve the PR.

The differences are expected:
- point_stat
  - Compute S12, S13, S21, S23, S31, S32, PV1, PV2, PV3, PF1, PF2, PF3 columns
  - All of them are 0 because the density_vector is zero with density_radius 0.75.
  - If density_radius is big enough, non zero density_vector is generated
  - The SEEPS QC is enabled (0.1 <= p1 <= 0.85, so less SEEPS MPR lines are saved
  - It supposed to save the weighted SEEPS score, but  averaged SEEPS score is printed out for SEEPS line type (becuase weighted SEEPS score is 0)
- grid_stat
  - three new output files with new unit test.

**Review by JohnHalleyGotway — APPROVED** [review]
After @hsoh-u confirmed that all diffs are expected, I approve of these changes.

I do suspect that testing from @RachelNorth may reveal that some tweaks to the logic are needed, but let's proceed with these changes now.

Thanks for all your work on this @hsoh-u!

**Pull request merged**
