### PR TITLE
Feature 1580 2d time

### LINKED ISSUE #1580: point2grid: support the 2D time variable
Requested from RT ticket (Binyu, https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=97459)

## Describe the New Feature ##
The sample file of RT-Ticket 97459 has (x,y) dimensions for coordinate variables (lat/lon/time) and MET's  NCCF library does not support 2 dimensional time variable. The 2D time variable does not make sense for the gridded data. But it could be used for the point observation data (sparse point data). It would be nice to support 2D time variable for the point2grid.

**Background assessment from helpdesk ticket:**

**From John:**
Binyu,

I'm adding my response here and will then reassign this ticket to Howard Soh to see if he has any more ideas.

I downloaded your file to our anonymous ftp site:

ftp://ftp.rap.ucar.edu/incoming/irap/met_help/wang_data_20201116/VOLCAT_HIMAWARI-8_FLDK_s2020296_173000_v300250_VCB_w167_FLDK_b2020295_204000_g001.nc

I'm able to replicate the same error you're getting:

terminate called after throwing an instance of 'netCDF::exceptions::NcInvalidCoords'

After some testing I see that this is caused by the time variable having 2 dimensions:        int time(y, x) ;

When reading 2-D gridded data, the code expects the time variable to be 1 dimensional. A file may contain multiple timesteps and a coordinate variable defines what those timesteps are. To sidestep this issue, I just removed the "time(y, x)" variable entirely. But then MET isn't able to read the projection info:

ERROR  : NcCfFile::read_netcdf_grid() -> Couldn't figure out projection from information in netCDF file.

Looking closely at the latitude and longitude variables, I see that this really is not gridded data at all. Instead, it's a dense set of pixels, but it doesn't appear that the lat/lon's are evenly spaced or follow any sort of projection (e.g. Lambert Conformal, Mercator, PolarStereographic, and so on).

Since this is a dense collection of individual points, you'll still need to run the Point2Grid tool to place them onto a real grid. And that's the question to Howard. Is there anyway that Binyu could format this NetCDF file that would enable it to be read easily by the Point2Grid tool?

**From Howard:**
The point2grid handles a CF complaint NetCDF which has
1) 2D variables with lat/lon dimensions and the time variable with 1 value OR
2) 3D variables with time/lat/lon dimensions and the time variable with 1 dimension.

The point2grid should be enhanced to support the 2-dimensional time variable (if the enhancement is approved).

The sample NetCDF has two time offsets: 1603387817 and 1603387833 ("seconds since 1970-01-01 00:00:00"). One possible way without changing MET applications is generating two files (one file with time offset 1603387817 and the other file with time offset 1603387817).

netcdf1:
   int time(1);
   time = 1603387817
   fill the missing value for the time 1603387833

netcdf2:
   int time(1);
   time = 1603387833
   fill the missing value for the time 1603387817

### Acceptance Testing ###
point2grid should process the file at /d3/personal/hsoh/data/RT-97459//VOLCAT_HIMAWARI-8_FLDK_s2020296_173000_v300250_VCB_w167_FLDK_b2020295_204000_g001.nc

### Time Estimate ###
1 or 2 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE.

### Funding Source ###
2791541 

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
  - One new output: point2grid/point2grid_2D_time_G231.nc
  - No changes for the existing outputs

- [x] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[No]**</br>
  - Will delete the branch later after making sure no side effect with updating library codes

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

## Summary ##
- nccf_file.cc/nccf_file.h
  - added get_grid_from_lat_lon_vars from existing code and reuse
  - added _latVar and _lonVar
  - if time variable has 2D values
    - do not set tDim 
    - Get the latest time and set it to ValidTime (not 1D array)
- nc_utils.cc: get_nc_data()
  - removed checking add_offset & scale_factor before calling _apply_scale_factor (the 2D time variable at the 
  - merged two for loops to one
- point2grid.cc
  - added one more condition to identify GOES (global attribute project = "GOES"). The sample file with 2D time variable also has the "scene_id" global attributes
  - added filtering by time for CF NetCDF input (only if the time variable is 2D)
  - cellMapping is adjusted by obs time if valid_time is given at the config file
- pb2nc.cc: to avoid the compilation warning
- Added unit test with 2D time variable input (point2grid_2D_time)

The input file for new unit test:
- Added standard_name attribute for lat/lon/time variables manually
- dakota:/d3/projects/MET/MET_test_data/unit_test/obs_data/point_obs/VOLCAT_HIMAWARI-8_FLDK_s2020296_173000_v300250_VCB_w167_FLDK_b2020295_204000_g001.nc
- kiowa:/d1/projects/MET/MET_test_data/unit_test/obs_data/point_obs/VOLCAT_HIMAWARI-8_FLDK_s2020296_173000_v300250_VCB_w167_FLDK_b2020295_204000_g001.nc

The command from the unit test:

./point2grid \
      /d3/projects/MET/MET_test_data/unit_test/obs_data/point_obs/VOLCAT_HIMAWARI-8_FLDK_s2020296_173000_v300250_VCB_w167_FLDK_b2020295_204000_g001.nc \
      G231 \
      point2grid_2D_time_G231.nc \
      -field 'name="brightness_temperature_4micron"; level="(*,*)";' \
      -v 1

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
Working on this review now in kiowa:/d1/projects/MET/MET_pull_requests/met-10.0.0_beta3/feature_1580
Compiled the code and running the unit tests.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
Reviewed the changes, compiled the code, ran the full set of unit tests, and diffed the results against develop. This adds new unit test output which will cause the NB to fail, which is fine:
test_output/point2grid/point2grid_NCCF_TO_G231.nc

Two questions:
(1) The grid for the new unit test seems like an odd choice. Here's the output:
Screen Shot 2021-01-12 at 1 17 26 PM

Unless there's a good reason for using this particular grid, I'd recommend defining one that better contains the data. Could replace "G231" on the command line with a grid specification string like "latlon Nx Ny lat_ll lon_ll delta_lat delta_lon".

(2) I noticed that the User's Guide lacks a section about the Point2Grid config file, like the one that's there for madis2nc (https://github.com/dtcenter/MET/blob/feature_1580_2d_time/met/docs/Users_Guide/reformat_point.rst#madis2nc-configuration-file). Do you want to add that now as part of this PR? Or would you rather create a separate GitHub issue to do it?

**Comment by hsoh-u** [comment]
The unittest "point2grid_NCCF_TO_G231":
- renamed to "point2grid_NCCF_UK"
- changed TO_GRID to "latlon 500 300 40 -30 0.1 0.1" ==> The output is changed, too
- changed output name "point2grid_NCCF_TO_G231.nc" to "point2grid_NCCF_UKMet.nc"

The TO_GRID of point2grid_2D_time is changed to "latlon 150 150 45 155 0.1 0.1".

**Review by JohnHalleyGotway — APPROVED** [review]
Thanks Howard for updating that unit test. The resulting output looks much better. Here's an ncview view of it.
Screen Shot 2021-01-13 at 9 08 55 AM

Looks much better. I approve of these changes. And I'll rerun last night's nightly build right now.

**Comment by JohnHalleyGotway** [comment]
Note that I am NOT deleting this development branch, per the instructions in the Pull Request.

**Pull request merged**
