### PR TITLE
Feature 1020 set_attrs

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
After merging the latest version of develop in feature_1020_set_attrs, I ran a regression test in kiowa:/d1/projects/MET/MET_pull_requests/met-9.1_beta2/feature_1020/regression

The only differences should new set_attr output files generated by Grid-Stat.

Please read the last comment on #1020 which explains the change I had to make, replacing set_attr_... bareword entries instead of grouping them together into a set_attrs dictionary.

### CODE REVIEW

**Review by georgemccabe — CHANGES_REQUESTED** [review]
I had issues building from this branch on my laptop, so I added a single docker image for this specific feature branch. I was able to run a METplus use case (GridStat.conf) in docker. I changed the GridStatConfig file to write a raw NC file. I added a couple set_attrs values to the forecast data (based on the unit test example) and reran. The level value updated to "TROPO" as expected, but the long name appears to be different than the explicit value I provided.

My configuration:
FCST_FIELD={ name="APCP"; level="A03"; cat_thresh=[ gt12.7,gt25.4,gt50.8,gt76.2 ]; set_attr_level = "TROPO";  set_attr_long_name = "Temperature at the tropopause"; }


netcdf grid_stat_WRF_APCP_vs_MC_PCP_APCP_03_120000L_20050807_120000V_pairs {
dimensions:
        lat = 129 ;
        lon = 185 ;
variables:
        float FCST_APCP_03_TROPO_FULL(lat, lon) ;
                FCST_APCP_03_TROPO_FULL:name = "FCST_APCP_03_TROPO_FULL" ;
                FCST_APCP_03_TROPO_FULL:long_name = "APCP_03 at TROPO" ;
                FCST_APCP_03_TROPO_FULL:level = "TROPO" ;

The value was overwritten by <name> at <level> instead of my value.

So good news, you are able to add set_attrs items to a METplus config via:

FCST_VAR1_OPTIONS = set_attr_level = "TROPO"; set_attr_long_name = "Temperature at the tropopause";

but bad news, not all of the options may be working as expected.

**Comment by JohnHalleyGotway** [comment]
Hey George, I’m not surprised by the long name behavior you describe. I think I realized that I wasn’t actually checking for that when setting up the long name in Grid-Star matched pairs file. Here’s the issue... each variable can result in multiple output fields in that file. The code constructs the long name to differentiate between them... and it wasn’t immediately obvious to me how to use the user-defined long name in that context... but I could try.

**Comment by JohnHalleyGotway** [comment]
OK George, I update Grid-Stat to include the user-specified long_name string in the NetCDF matched pairs output file from Grid-Stat.

**Comment by georgemccabe** [comment]
OK, the changes look good to me as far as I can tell. I will let you merge the changes so you can control the differences that will come up from the tests.

**Comment by JohnHalleyGotway** [comment]
Will do. Thanks George.

John

**Pull request merged**
