### PR TITLE
Feature #2966 local_solar_time

### LINKED ISSUE #2966: Enhance Gen-Vx-Mask to support a new local solar time masking region option
## Describe the Enhancement ##
The gen_vx_mask tool already supports solar altitude (`solar_alt`) and solar azimuth (`solar_azi`) masking by computing the solar altitude and azimuth values at each grid point for the time defined by the mask_file setting. mask_file may either be set to an explicit time string in YYYYMMDD[_HH[MMSS]] format or to a gridded data file. If set to a gridded data file, the -mask_field command line option specifies the field of data whose valid time should be used. If the -thresh command line option is not used, the raw solar altitude or azimuth value for each grid point will be written to the output. If it is used, the resulting binary mask field will be written. This option is useful when defining a day/night mask.

This issue will enhance gen_vx_mask to support a new option `-type solar_time` and provide a way to define the beginning/ending solar time to be included in the mask. 

Consider also writing up another development issue to add support for `mask.solar_time` directly in the configuration files for the STAT tools.

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
Note that the SWPC 2770493 funding ends in March 2025. So this work should be done during FY25 Q1 (NRL) or FY25 Q2 (SWPC) during the beta1 or beta2 development cycles.

### Funding Source ###
SWPC 2770493
or
NRL METplus 7730022

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] dtcenter/METplus#2586

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
Since the `main_v12.0` branch was created for the MET-12.0.0-rc1 release, the `develop` branch is now available to accept enhancements slated for the v12.1 release. This PR can proceed.

Add support for new `-type solar_time` masking type.
Also adds support for multiple `-type`, `-mask_field`, and `-thresh` settings for a single run, when all use the same **mask_file** setting. 

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[Yes]**</br>
If **yes**, please describe:</br>
Adds new `units` attribute to the NetCDF output from Gen-Vx-Mask.
Updates the `mask_type` attribute with additional details about the data processed.
Adds logic to concatenate masking type names when constructing the output variable name.

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Tested manually.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br> 
1. Confirm all differences in GitHub actions are expected:
- 1 new Gen-Vx-Mask output file.
- A `units` NetCDF variable attribute is added to existing Gen-Vx-Mask output files.
2. Carefully review updated Gen-Vx-Mask usage statement and User's Guide documentation for typos, accuracy, and clarity. 
3. Test out `seneca:/d1/projects/MET/MET_pull_requests/met-12.1.0/beta1/MET-feature_2966_local_solar_time/bin/gen_vx_mask` and try to "break it" ensuring it behaves as expected.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
Updated the chapter about spatial masking.

- [x] Do these changes include sufficient testing updates? **[Yes]**
Added two new Gen-Vx-Mask unit test to demonstrate:
- combining the `-type solar_alt` and `-type solar_time` options in a single run
- combining data/data/lat/lon masking types in a single run

- [x] Will this PR result in changes to the MET test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

Two new files described above and changes to the `units` and `mask_type` attributes of existing output files.

- [x] Will this PR result in changes to existing METplus Use Cases? **[Yes or No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.
The `units` variable attribute will be added and `mask_type` modified for existing Gen-Vx-Mask output files.

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:
While existing SonarQube findings will be flagged as being "new", the overall number of code smells is reduced from 18,315 to about 18,251.

- [x] Please complete this pull request review by **[Fri 11/22/24]**.</br>
Discussed timing during the METplus NRL meeting on 11/20/24. Recommend reviewing by Friday 11/22/24 or early the following week.

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
Based on [this issue comment](https://github.com/dtcenter/MET/issues/2966#issuecomment-2457912385), requesting this PR review from @CPKalb. Tina, please LMK if you have any questions or run into any issues.

**Comment by JohnHalleyGotway** [comment]
I'd previously found some differences in the presence of timing attributes being added to the Gen-Vx-Mask output files. I updated the logic with [this commit](https://github.com/dtcenter/MET/pull/3008/commits/0177be501f624def2e158caeb13f090ef8940210) to eliminate those diffs.

The remaining diffs flagged by the GHA testing workflow are all expected, including the addition of the `units` NetCDF variable attribute and changes to the `mask_type` attribute for data masking, like this:
```
COMPARING gen_vx_mask/DATA_INPUT_FIELD_APCP_24_where_TMP_Z2_le300.nc
file1: /data/output/met_test_truth/gen_vx_mask/DATA_INPUT_FIELD_APCP_24_where_TMP_Z2_le300.nc
file2: /data/output/met_test_output/gen_vx_mask/DATA_INPUT_FIELD_APCP_24_where_TMP_Z2_le300.nc
ERROR: NetCDF headers differ:
16a17
> 		APCP_24_where_TMP_Z2_le300:units = "kg/m^2" ;
18c19
< 		APCP_24_where_TMP_Z2_le300:mask_type = "data>300" ;
---
> 		APCP_24_where_TMP_Z2_le300:mask_type = "data(TMP/Z2)>300" ;
```

**Comment by JohnHalleyGotway** [comment]
@CPKalb based on you feedback over Slack, this morning I committed [these changes](https://github.com/dtcenter/MET/pull/3008/commits/f016f5d741dbc931e2f9c8314c18102c24d2c00e) to the usage statement and documentation. Please advise if those changes are sufficient or more are needed.

**Review by CPKalb — APPROVED** [review]
Did a number of tests and everything worked as expected.  Documentation of the changes looks good.

**Pull request merged**
